// scripts/battle-stats.mjs
//
// The battle numbers sync_offline_trainer_battle checks an offline battle's log against
// (supabase/migrations/20261007000000_offline_trainer_battles.sql), computed from the game's own
// code (lib/monsterConfig.ts, lib/curioQuality.ts) so the database never keeps a hand-typed copy.
//
//   node scripts/battle-stats.mjs --write   writes a new migration loading the current numbers;
//                                           run it whenever curio, skill or trainer stats change
//   node scripts/battle-stats.mjs --check   compares them with a running local database
//                                           (CI: .github/workflows/database-tests.yml)
//   node scripts/battle-stats.mjs           prints them as JSON
import { createJiti } from 'jiti';
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const jiti = createJiti(import.meta.url, { alias: { '@': root } });
const mc = await jiti.import(join(root, 'lib/monsterConfig.ts'));
const { QUALITY_STAT_MULTIPLIER } = await jiti.import(join(root, 'lib/curioQuality.ts'));

export function computeBattleStats() {
  // A player's curio can show up as any of its forms (guild level, graduation), so each species
  // keeps the highest base stats across them: the server only uses these as upper bounds.
  const species = {};
  for (const [id, def] of Object.entries(mc.ALL_MONSTERS)) {
    const forms = [def];
    if (mc.GUILD_MONSTERS[id]) for (let level = 1; level <= 200; level++) forms.push(mc.getGuildMonsterDisplay(def, level));
    const all = forms.flatMap(f => [0, 1, 2].map(t => mc.getOwnedMonsterDisplay(f, t) ?? f));
    species[id] = {
      hp: Math.max(...all.map(f => f.baseHp)),
      attack: Math.max(...all.map(f => f.baseAttack)),
      defense: Math.max(...all.map(f => f.baseDefense)),
    };
  }
  const skills = {};
  for (const [id, s] of Object.entries(mc.SKILLS)) skills[id] = s.baseDamageMultiplier ?? 0;
  // Trainer curios exactly as BattleScreen builds them (getScaledStats, getNpcSkill's tiers).
  const trainers = {};
  for (const t of mc.NPC_TRAINERS) {
    trainers[t.id] = {
      level_req: t.levelRequirement,
      reward_exp: t.reward?.exp ?? 0,
      curios: t.monsters.map(m => {
        const def = mc.ALL_MONSTERS[m.monsterId];
        const stats = mc.getScaledStats(def, m.level, m.quality);
        const tier = m.level >= 15 ? 3 : m.level >= 8 ? 2 : 1;
        return { hp: stats.hp, attack: stats.attack, defense: stats.defense, skill_multiplier: mc.SKILLS[def.skills[tier - 1]].baseDamageMultiplier };
      }),
    };
  }
  return {
    stat_growth: mc.BATTLE_CONSTANTS.STAT_GROWTH_PER_LEVEL,
    burn_damage: mc.BATTLE_CONSTANTS.BURN_DAMAGE_PER_TURN,
    // The biggest heal one skill gives (lifesteal of the damage, or flat of the curio's full HP),
    // and the biggest and most frequent Rest of any element.
    heal_fraction: Math.max(0, ...Object.values(mc.SKILLS).map(s => (s.effects ?? [])
      .filter(e => e.kind === 'lifesteal' || e.kind === 'flat_heal')
      .reduce((sum, e) => sum + (e.magnitude ?? 0), 0))),
    rest_fraction: Math.max(...Object.values(mc.REST_BY_ELEMENT).map(r => r.hpRestorePercent)),
    rest_uses: Math.max(...Object.values(mc.REST_BY_ELEMENT).map(r => r.maxUsesPerBattle)),
    qualities: { ...QUALITY_STAT_MULTIPLIER },
    species, skills, trainers,
  };
}

// Same order and number formatting on both sides, so the comparison is a string compare.
function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort().map(k => [k, canonical(value[k])]));
  }
  return typeof value === 'number' ? Number(value.toFixed(6)) : value;
}

const mode = process.argv[2];
const stats = canonical(computeBattleStats());
if (mode === '--write') {
  const now = new Date();
  const stamp = now.toISOString().replace(/[-:T]/g, '').slice(0, 14);
  const file = join(root, 'supabase/migrations', `${stamp}_battle_stats.sql`);
  const json = JSON.stringify(stats);
  writeFileSync(file, `-- Generated by scripts/battle-stats.mjs from lib/monsterConfig.ts; don't edit by hand.
-- The curio, skill and trainer numbers sync_offline_trainer_battle checks offline battle logs
-- against (20261007000000_offline_trainer_battles.sql). Replaces the previous set.
select public.load_battle_stats($battle_stats$${json}$battle_stats$::jsonb);
`);
  console.log(`wrote ${file}`);
} else if (mode === '--check') {
  const dbUrl = process.env.DB_URL ?? 'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
  const out = execFileSync('psql', [dbUrl, '-At', '-c', 'select public.battle_stats_snapshot()'], { encoding: 'utf8' });
  const db = canonical(JSON.parse(out.trim()));
  if (JSON.stringify(db) !== JSON.stringify(stats)) {
    const diff = [];
    for (const section of Object.keys(stats)) {
      if (JSON.stringify(db[section]) !== JSON.stringify(stats[section])) diff.push(section);
    }
    console.error(`::error::The database's battle stats don't match lib/monsterConfig.ts (${diff.join(', ')}). ` +
      'Run `node scripts/battle-stats.mjs --write` and commit the new migration.');
    process.exit(1);
  }
  console.log('Battle stats in the database match the game.');
} else {
  console.log(JSON.stringify(stats, null, 1));
}
