-- Grade 3 Lorekeeper content batch 2 of N — 94 questions, working toward
-- the 300-question-per-grade-per-guild target. Covers Science, AP, English,
-- and Filipino, distinct from the 115 questions in the first batch
-- (20260826060000_sq_lorekeeper_grade3_batch1.sql) — checked for exact-text
-- duplicates against that batch before writing this migration.

insert into public.sq_lorekeeper (term_id, is_active, grade_level, passage, question, choice_a, choice_b, choice_c, choice_d, correct_choice) values
  (1, true, 3, 'A plant needs four things to grow well: sunlight, water, air, and space to grow. If it is missing even one of these, it will not grow healthy and strong.', 'According to the passage, what does a plant need to grow well?', 'Sunlight, water, air, and space', 'Soil, sand, rocks, and shade', 'Only water and darkness', 'Only sunlight and wind', 'a'),
  (1, true, 3, NULL, 'What is the main purpose of a flower on a plant?', 'To take in water from the soil', 'To attract pollinators and help make seeds', 'To carry water to the leaves', 'To hold the plant upright', 'b'),
  (1, true, 3, NULL, 'Some seeds have fluffy parts, like a dandelion seed, so that they can', 'Be carried far away by the wind', 'Stay heavier and sink into the soil', 'Absorb more sunlight', 'Grow roots faster', 'a'),
  (1, true, 3, NULL, 'What do plant roots absorb from the soil besides water?', 'Oxygen bubbles', 'Minerals and nutrients', 'Sunlight', 'Carbon dioxide gas', 'b'),
  (1, true, 3, NULL, 'Which of these correctly lists animal classification groups?', 'Mammal, bird, fish, reptile, amphibian, insect', 'Loud, quiet, fast, slow', 'Big, medium, small', 'Wild, tame, lost, found', 'a'),
  (1, true, 3, NULL, 'An animal that only eats plants is called a', 'Carnivore', 'Omnivore', 'Herbivore', 'Predator', 'c'),
  (1, true, 3, NULL, 'An animal that eats both plants and other animals is called a(n)', 'Herbivore', 'Omnivore', 'Carnivore only', 'Producer', 'b'),
  (1, true, 3, 'A frog begins life as an egg in the water. The egg hatches into a tadpole, which has a tail and breathes with gills. As it grows, the tadpole slowly changes into a young frog with legs, and finally becomes an adult frog that can live on land and in water.', 'What is the correct order of a frog''s life cycle?', 'Egg → tadpole → young frog → adult frog', 'Adult frog → egg → tadpole → young frog', 'Tadpole → egg → adult frog → young frog', 'Egg → adult frog → tadpole → young frog', 'a'),
  (1, true, 3, 'A frog begins life as an egg in the water. The egg hatches into a tadpole, which has a tail and breathes with gills. As it grows, the tadpole slowly changes into a young frog with legs, and finally becomes an adult frog that can live on land and in water.', 'What body part does a tadpole use to breathe?', 'Lungs', 'Gills', 'Skin only', 'Nose', 'b'),
  (1, true, 3, NULL, 'How many legs does an insect have?', 'Four', 'Six', 'Eight', 'Ten', 'b'),
  (1, true, 3, NULL, 'An animal with a backbone, like a fish or a bird, is called a', 'Vertebrate', 'Invertebrate', 'Herbivore', 'Amphibian only', 'a'),
  (1, true, 3, NULL, 'Which of these animals lives its adult life mostly in a desert habitat?', 'Camel', 'Dolphin', 'Salmon', 'Frog', 'a'),
  (1, true, 3, NULL, 'A liquid like water has no fixed shape of its own, but does it have a fixed amount (volume)?', 'No, its amount changes on its own', 'Yes, its amount stays the same unless you add or remove some', 'It disappears completely over time', 'It only exists as a gas', 'b'),
  (1, true, 3, NULL, 'Which of these is an example of a solid changing shape only when a force is applied?', 'Water poured into a cup', 'Air filling a balloon', 'Clay being molded by hand', 'Steam rising from a pot', 'c'),
  (1, true, 3, NULL, 'Which of these is NOT an example of a gas?', 'The air inside a balloon', 'The oxygen we breathe', 'A block of ice', 'The steam from a boiling pot', 'c'),
  (1, true, 3, NULL, 'If you stir sand into water, what usually happens to the sand?', 'It dissolves completely like sugar', 'It settles at the bottom because it does not dissolve', 'It turns into a gas', 'It disappears forever', 'b'),
  (1, true, 3, NULL, 'During tag-ulan (rainy season) in the Philippines, what kind of weather is most common?', 'Hot and dry with no clouds', 'Frequent rain and thunderstorms', 'Snow and freezing temperatures', 'Constant strong winds with no rain', 'b'),
  (1, true, 3, NULL, 'During tag-init or tag-araw (dry/hot season) in the Philippines, what kind of weather is most common?', 'Heavy snowfall', 'Hot temperatures with little rain', 'Constant rain all day', 'Freezing winds', 'b'),
  (1, true, 3, NULL, 'What is the difference between a weather vane and an anemometer?', 'A weather vane shows wind direction; an anemometer measures wind speed', 'They both measure temperature only', 'A weather vane measures rainfall; an anemometer shows wind direction', 'There is no difference between them', 'a'),
  (1, true, 3, NULL, 'Before going outside on a day with dark, heavy clouds, what would be a smart thing to prepare?', 'Sunglasses only', 'An umbrella or raincoat', 'A fan for the heat', 'Nothing, since dark clouds mean sunny weather', 'b'),
  (1, true, 3, NULL, 'Farmers check the weather before planting crops mainly because', 'Weather has no effect on crops', 'Crops need the right amount of sun and rain to grow well', 'It helps them choose what color seeds to plant', 'It tells them what time to wake up', 'b'),
  (1, true, 3, NULL, 'Soil that is made up mostly of tiny rock particles and drains water very quickly is called', 'Clay soil', 'Loamy soil', 'Sandy soil', 'Wet soil', 'c'),
  (1, true, 3, NULL, 'Which property of a rock refers to how easily it can be scratched or broken?', 'Its hardness', 'Its color', 'Its name', 'Its price', 'a'),
  (1, true, 3, NULL, 'Why do farmers often add loamy soil or compost to sandy soil before planting?', 'To make the soil drain faster', 'To help the soil hold more water and nutrients for the plants', 'To make the soil look a different color', 'To stop plants from growing at all', 'b'),
  (1, true, 3, NULL, 'A knife or an axe blade that cuts through something is an example of which simple machine?', 'Wedge', 'Pulley', 'Wheel and axle', 'Lever', 'a'),
  (1, true, 3, NULL, 'A pair of scissors works mainly like which simple machine?', 'Wedge only', 'Lever', 'Pulley', 'Screw', 'b'),
  (1, true, 3, NULL, 'A wheelbarrow that helps carry heavy loads combines which two simple machines?', 'Pulley and screw', 'Lever and wheel and axle', 'Wedge and inclined plane', 'Screw and wedge', 'b'),
  (1, true, 3, NULL, 'A spiral staircase that winds upward is most similar to which simple machine?', 'Screw', 'Pulley', 'Wedge', 'Lever', 'a'),
  (1, true, 3, 'Long before the Spanish arrived, early Filipinos already traded goods with each other and with nearby countries. This trading of goods was called kalakalan. Barangays near the coast often traded fish and shells for rice and cloth from inland barangays.', 'What was the early Filipino practice of trading goods called?', 'Bayanihan', 'Kalakalan', 'Katipunan', 'Pamahalaan', 'b'),
  (1, true, 3, 'Long before the Spanish arrived, early Filipinos already traded goods with each other and with nearby countries. This trading of goods was called kalakalan. Barangays near the coast often traded fish and shells for rice and cloth from inland barangays.', 'What did coastal barangays often trade for rice and cloth?', 'Gold and jewelry', 'Fish and shells', 'Wood and stone', 'Books and paper', 'b'),
  (1, true, 3, NULL, 'Gabriela Silang is remembered in Philippine history as', 'A pre-colonial datu', 'A woman who led a revolt against Spanish rule', 'The first Philippine president', 'A famous painter', 'b'),
  (1, true, 3, NULL, 'Today, the leader of a barangay is called a', 'Datu', 'Barangay Captain', 'Governor', 'Senator', 'b'),
  (1, true, 3, NULL, 'The Philippines is made up mostly of', 'One large connected landmass', 'Thousands of islands', 'A single mountain range', 'A desert region', 'b'),
  (1, true, 3, NULL, 'Which of these is a basic responsibility of a good citizen, even for a child?', 'Following rules and respecting others'' rights', 'Ignoring laws when convenient', 'Taking things that belong to others', 'Refusing to help anyone', 'a'),
  (1, true, 3, NULL, 'Which of these is an example of a service, not a good?', 'A loaf of bread', 'A haircut from a barber', 'A bag of rice', 'A pair of shoes', 'b'),
  (1, true, 3, NULL, 'Which of these is an example of a good, not a service?', 'A doctor''s check-up', 'A teacher''s lesson', 'A basket of mangoes', 'A jeepney ride', 'c'),
  (1, true, 3, NULL, 'A market where people buy and sell fresh food and goods is an example of what kind of structure?', 'A natural structure', 'A human-made structure', 'Neither natural nor human-made', 'A type of animal habitat', 'b'),
  (1, true, 3, NULL, 'A coral reef found in the ocean is an example of what kind of structure?', 'A human-made structure', 'A natural structure', 'A type of vehicle', 'A type of clothing', 'b'),
  (1, true, 3, NULL, 'Which of these best shows a Filipino value of helping neighbors work together, like moving a house?', 'Kalakalan', 'Bayanihan', 'Kabataan', 'Kasaysayan', 'b'),
  (1, true, 3, NULL, 'Wearing a seatbelt or following pedestrian lanes are examples of a citizen''s', 'Wants', 'Responsibility to stay safe and follow rules', 'Hobbies', 'Favorite subjects', 'b'),
  (1, true, 3, 'Lola Mia loves to tell stories under the mango tree every evening. One night, she told a story about a turtle who outsmarted a hungry crocodile using only his wit. The children listened closely, amazed at how a small animal could be so clever.', 'Who told the story under the mango tree?', 'The turtle', 'The crocodile', 'Lola Mia', 'The children', 'c'),
  (1, true, 3, 'Lola Mia loves to tell stories under the mango tree every evening. One night, she told a story about a turtle who outsmarted a hungry crocodile using only his wit. The children listened closely, amazed at how a small animal could be so clever.', 'What is the setting of this story?', 'Inside a classroom', 'Under a mango tree in the evening', 'At the market in the morning', 'On a boat at sea', 'b'),
  (1, true, 3, NULL, 'In a story, the main problem the characters face and how they solve it is called the', 'Setting', 'Problem and solution', 'Title', 'Author', 'b'),
  (1, true, 3, NULL, 'A paragraph that explains WHY something happens, like why leaves change color, is an example of which text type?', 'Explanatory text', 'Procedural text', 'Persuasive text', 'Poetry', 'a'),
  (1, true, 3, NULL, 'Words like "first," "next," "then," and "finally" are often used to show', 'Opposite meanings', 'The sequence or order of events', 'A character''s feelings', 'The setting of a story', 'b'),
  (1, true, 3, NULL, 'The prefix "dis-" in the word "disagree" changes the meaning of "agree" to mean', 'To agree strongly', 'To not agree', 'To agree again', 'To agree quietly', 'b'),
  (1, true, 3, NULL, 'The prefix "pre-" in the word "preview" changes the meaning of "view" to mean', 'To view after', 'To view before', 'To never view', 'To view loudly', 'b'),
  (1, true, 3, NULL, 'Adding the suffix "-er" to the word "fast" to make "faster" is used to', 'Compare two things', 'Show the past tense', 'Make the word a noun', 'Show ownership', 'a'),
  (1, true, 3, NULL, 'Adding the suffix "-est" to the word "tall" to make "tallest" is used to', 'Compare exactly two things', 'Show the highest degree among three or more things', 'Make the word negative', 'Show a question', 'b'),
  (1, true, 3, NULL, 'Which sentence correctly uses a comma to separate items in a series?', 'I bought apples bananas and mangoes.', 'I bought apples, bananas, and mangoes.', 'I bought, apples bananas and mangoes.', 'I, bought apples bananas, and mangoes.', 'b'),
  (1, true, 3, NULL, 'Which word correctly uses an apostrophe to form a contraction of "do not"?', 'dont''', 'do''nt', 'don''t', 'do''not', 'c'),
  (1, true, 3, NULL, 'In the sentence "The happy dog ran quickly," which word is the adjective?', 'dog', 'ran', 'happy', 'quickly', 'c'),
  (1, true, 3, NULL, 'In the sentence "The happy dog ran quickly," which word is the verb?', 'happy', 'ran', 'dog', 'quickly', 'b'),
  (1, true, 3, NULL, 'Which word is a synonym for "large"?', 'Tiny', 'Huge', 'Narrow', 'Short', 'b'),
  (1, true, 3, NULL, 'Which word is an antonym for "loud"?', 'Noisy', 'Quiet', 'Booming', 'Roaring', 'b'),
  (1, true, 3, 'The word "ancient" means very, very old. In the sentence "The ancient temple had crumbling stone walls covered in vines," you can guess its meaning from the surrounding words.', 'Based on the passage, what does "ancient" most likely mean?', 'Very old', 'Very new', 'Very colorful', 'Very small', 'a'),
  (1, true, 3, NULL, 'Which sentence uses the irregular past tense of "go" correctly?', 'Yesterday, she goed to the market.', 'Yesterday, she went to the market.', 'Yesterday, she gone to the market.', 'Yesterday, she going to the market.', 'b'),
  (1, true, 3, NULL, 'Ang kwentong may hayop na tulad ng usa at pagong bilang tauhan, na may aral sa dulo, ay tinatawag na', 'Talambuhay', 'Pabula', 'Balita', 'Tula', 'b'),
  (1, true, 3, NULL, 'Ang alamat na nagpapaliwanag kung bakit umuulan ay isang halimbawa ng', 'Kwentong bayan tungkol sa pinagmulan ng isang bagay sa kalikasan', 'Balitang pang-araw-araw', 'Talaan ng pangalan', 'Aklat-aralin sa agham', 'a'),
  (1, true, 3, NULL, 'Ang "paksa" ng isang pangungusap ay tumutukoy sa', 'Salitang naglalarawan ng aksyon', 'Taong o bagay na pinag-uusapan sa pangungusap', 'Bantas sa dulo ng pangungusap', 'Pang-abay na ginamit', 'b'),
  (1, true, 3, NULL, 'Ang "panaguri" ng isang pangungusap ay tumutukoy sa', 'Bahaging naglalahad kung ano ang ginagawa o kalagayan ng paksa', 'Pangngalang pantangi lamang', 'Unang salita ng pangungusap', 'Bilang ng salita sa pangungusap', 'a'),
  (1, true, 3, NULL, 'Sa pangungusap na "Kumakain ang bata," alin ang panaguri?', 'Bata', 'Kumakain', 'Ang', 'Walang panaguri', 'b'),
  (1, true, 3, NULL, 'Ang salitang "matapang" ay kasingkahulugan ng', 'Matakot', 'Magiting', 'Mahina', 'Malungkot', 'b'),
  (1, true, 3, NULL, 'Ang salitang "maingay" ay kasalungat ng', 'Matunog', 'Tahimik', 'Malakas', 'Masigla', 'b'),
  (1, true, 3, NULL, 'Ang kasabihang "Kapag may tiyaga, may nilaga" ay nagtuturo ng', 'Kahalagahan ng pagtitiyaga at sipag', 'Kahalagahan ng pagtulog nang maaga', 'Kahalagahan ng paglalaro', 'Kahalagahan ng pananahimik', 'a'),
  (1, true, 3, NULL, 'Anong uri ng panitikan ang bugtong na "Bumbong kong walang lamang, patungan ng bulaklak"?', 'Salawikain', 'Bugtong', 'Alamat', 'Pabula', 'b'),
  (1, true, 3, NULL, 'Ang panghalip na "siya" ay ginagamit upang palitan ang', 'Isang pangalan ng tao', 'Isang bantas', 'Isang numero', 'Isang kulay', 'a'),
  (1, true, 3, NULL, 'Alin sa mga sumusunod ang pang-uri (describing word)?', 'Tumatakbo', 'Maganda', 'Bahay', 'Sila', 'b'),
  (1, true, 3, NULL, 'Alin sa mga sumusunod ang wastong baybay ng salitang tumutukoy sa taong nagtuturo sa paaralan?', 'guro', 'guruh', 'goro', 'guru', 'a'),
  (1, true, 3, NULL, 'Alin sa mga sumusunod ang tamang baybay ng salitang tumutukoy sa lugar na tinitirhan?', 'bahay', 'baha', 'bahai', 'bahayy', 'a'),
  (1, true, 3, NULL, 'Ang paggalang sa nakatatanda, tulad ng paggamit ng "po" at "opo," ay halimbawa ng', 'Kalakalan', 'Isang Filipino value', 'Isang uri ng laro', 'Isang uri ng pagkain', 'b'),
  (1, true, 3, NULL, 'Ang "masipag" ay kasalungat ng', 'Matiyaga', 'Tamad', 'Masigasig', 'Masikap', 'b'),
  (1, true, 3, NULL, 'Ang kwentong tungkol sa buhay ng isang tunay na tao, isinulat ng ibang tao, ay tinatawag na', 'Talambuhay', 'Alamat', 'Pabula', 'Bugtong', 'a'),
  (1, true, 3, NULL, 'Sa isang maikling kwento, ang bahaging naglalahad ng simula, gitna, at wakas ay tinatawag na', 'Tauhan', 'Tagpuan', 'Banghay', 'Aral', 'c'),
  (1, true, 3, NULL, 'Ang bugtong ay kadalasang may dalawang bahagi: ang paglalarawan at ang', 'Sagot', 'Titulo', 'May-akda', 'Petsa', 'a'),
  (1, true, 3, NULL, 'Which of these best describes the water cycle step called "evaporation"?', 'Water falling from clouds as rain', 'Water turning into vapor and rising into the air', 'Water freezing into ice', 'Water flowing into the ocean', 'b'),
  (1, true, 3, NULL, 'Which of these best describes the water cycle step called "condensation"?', 'Water vapor cooling and forming clouds', 'Water flowing downhill', 'Water being absorbed by roots', 'Water boiling in a pot', 'a'),
  (1, true, 3, NULL, 'Which sense organ do we use to detect smells?', 'Eyes', 'Ears', 'Nose', 'Tongue', 'c'),
  (1, true, 3, NULL, 'Which sense organ do we use to detect sounds?', 'Nose', 'Ears', 'Skin', 'Eyes', 'b'),
  (1, true, 3, NULL, 'Eating a balanced diet with fruits and vegetables is an example of', 'A bad habit', 'A healthy habit', 'A simple machine', 'A weather pattern', 'b'),
  (1, true, 3, NULL, 'Washing your hands before eating helps prevent', 'Sickness caused by germs', 'Plants from growing', 'Rain from falling', 'Rocks from breaking', 'a'),
  (1, true, 3, NULL, 'Which of these community helpers is most likely to help put out a fire?', 'A firefighter', 'A farmer', 'A teacher', 'A cashier', 'a'),
  (1, true, 3, NULL, 'Which of these community helpers is most likely to deliver mail and packages?', 'A doctor', 'A mail carrier', 'A police officer', 'A farmer', 'b'),
  (1, true, 3, NULL, 'A police officer''s main responsibility in a community is to', 'Grow crops for the market', 'Help keep people safe and enforce laws', 'Teach students in school', 'Repair broken machines', 'b'),
  (1, true, 3, NULL, 'Which of these is an example of a Philippine national symbol representing our country''s bird?', 'Philippine Eagle', 'Bald Eagle', 'Peacock', 'Penguin', 'a'),
  (1, true, 3, NULL, 'Which of these is the national flower of the Philippines?', 'Rose', 'Sunflower', 'Sampaguita', 'Tulip', 'c'),
  (1, true, 3, NULL, 'Which of these best shows a child exercising a basic right to education?', 'Being forced to work instead of studying', 'Attending school and learning new things', 'Being left alone all day', 'Skipping meals', 'b'),
  (1, true, 3, NULL, 'A budget helps a family decide', 'What color to paint their house', 'How to plan and spend their money wisely', 'What time to sleep', 'Which TV show to watch', 'b'),
  (1, true, 3, NULL, 'Which sentence is written using descriptive language?', 'Mix the flour and sugar together.', 'The golden sun sank slowly behind the misty hills.', 'First, turn on the oven.', 'Is the cake ready yet?', 'b'),
  (1, true, 3, NULL, 'Which of these best describes a persuasive text?', 'A text that tries to convince the reader to believe or do something', 'A text that gives step-by-step instructions', 'A text that only lists facts with no opinion', 'A text with no clear purpose', 'a'),
  (1, true, 3, NULL, 'In a story, the events that happen from beginning to end, in order, are called the', 'Setting', 'Sequence of events', 'Genre', 'Illustration', 'b'),
  (1, true, 3, NULL, 'Which of these words uses the suffix "-ness" correctly to mean "the state of being kind"?', 'kindful', 'kindness', 'kindable', 'kindless', 'b'),
  (1, true, 3, NULL, 'Which word means the opposite of "difficult"?', 'Hard', 'Tough', 'Easy', 'Complex', 'c'),
  (1, true, 3, NULL, 'Which word means almost the same as "quick"?', 'Slow', 'Fast', 'Lazy', 'Sleepy', 'b');