insert into public.budget_of_work (grade, subject, content_markdown, source_file)
values (
  3,
  'Mathematics',
  $bow$# Grade 3 Mathematics — Budget of Work

## Term 1
Wk1-2: Representing numbers up to 10,000 using pictorial models and numerals; reading and writing numbers up to 10,000 in numerals and in words | Wk2-3: Determining the place value of a digit in a 4-digit number, the value of a digit, and the digit given its place value; rounding numbers to the nearest ten, hundred, or thousand | Wk4: Comparing numbers up to 10,000 using =, >, and <; ordering numbers up to 10,000 from smallest to largest and vice versa; describing the position of objects using ordinal numbers up to 100th | Wk5-6: Illustrating and estimating the area of a square or rectangle using square tile units; exploring inductively the derivation of the area formulas for a square and a rectangle | Wk7: Finding the areas of squares and rectangles in sq. cm and sq. m; solving problems involving areas of squares and rectangles | Wk8-9: Recognizing and drawing a point, line, line segment, and ray using models; recognizing and drawing parallel, intersecting, and perpendicular lines | Wk10: Identifying and drawing line segments of equal length using a ruler; term review integrating number, area, and line-and-angle skills

**Special Science enrichment:** Combine skills from the term into one non-routine, multi-step problem (e.g. designing a rectangular garden plot with a given area that also uses parallel and perpendicular fence lines), rather than practicing each skill in isolation.

## Term 2
Wk1: Measuring mass in grams, kilograms, and/or milligrams using appropriate tools; estimating and comparing masses of objects, including using a balance scale | Wk2: Measuring capacity in liters and/or milliliters using appropriate tools; estimating and comparing capacities of two containers | Wk3: Reading and writing money in words and using Philippine currency symbols (₱ and PhP) up to ₱10,000, and the centavo sign | Wk4-5: Adding numbers with sums up to 10,000, with and without regrouping; estimating the sum of addends with up to 4 digits; solving addition word problems up to 10,000, including problems involving money | Wk5-6: Subtracting numbers where both numbers are less than 10,000, with and without regrouping; estimating the difference of two numbers of up to 4 digits; performing addition and subtraction of 3 to 4 numbers of up to 2 digits, observing correct order of operations, including problems involving money | Wk7: Collecting data from experiments with a small number of possible outcomes (e.g. rolling a die, tossing a coin); presenting data in tables and single bar graphs (horizontal and vertical) | Wk8: Interpreting data in tables and single bar graphs; solving problems using data presented in a bar graph; describing and comparing outcomes in real-life situations using equally likely, less/least likely, more/most likely, certain, and impossible | Wk9-10: Multiplying using the 6, 7, 8, and 9 multiplication tables; illustrating and applying properties of multiplication (identity, zero, commutative, associative, distributive); multiplying 2- to 4-digit numbers with and without regrouping; estimating products by rounding factors to the nearest multiple of 10; solving multiplication word problems, including problems involving money

**Special Science enrichment:** Have the learner pose their own data question, collect or simulate real data for it (e.g. a small class survey), and justify in writing why a bar graph is the appropriate way to represent it, rather than only interpreting a bar graph that is given.

## Term 3
Wk1: Determining the missing term(s) in, and generating, patterns with repeating and increasing or repeating and decreasing components | Wk2: Illustrating division through equal jumps on the number line and as the inverse of multiplication; dividing numbers using the 6, 7, 8, and 9 multiplication tables; finding the missing number in a multiplication or division number sentence | Wk3-4: Dividing 2- to 4-digit numbers with and without remainder (2- to 3-digit numbers by a 1-digit number without remainder; 2-digit numbers by a 1-digit number with remainder; 2- to 4-digit numbers by 10, 100, and 1000); estimating quotients by first rounding the divisor and dividend to the nearest multiple of 10 | Wk5: Solving 1- to 2-step division problems involving 2- to 3-digit numbers by a 1-digit number, including problems involving money | Wk6: Representing fractions that are equal to one and greater than one using models; adding and subtracting similar fractions using models | Wk7: Describing and drawing the effect of a two-direction multi-step slide (translation) in basic shapes and figures | Wk8: Identifying shapes or figures that show line symmetry and drawing the line of symmetry; completing a figure that is symmetric with respect to a line | Wk9-10: Term review and integration — combining division, fraction, and symmetry skills in extended problems

**Special Science enrichment:** Extend the Wk6 fraction work to a real, non-routine scenario (e.g. sharing a recipe or a strip of land fairly among a small group) that requires the learner to add or subtract similar fractions and justify why the model they drew correctly represents the situation.$bow$,
  'https://lrdepedtagbilaran.net/wp-content/uploads/2025/12/FINAL-MATATAG-Mathematics-CG-2023-Grades-1-10.pdf'
);
