INSERT INTO public.mtap_expansion_content
  (question_code, grade, strand, archetype, tier, params, question, options,
   correct_answer, distractor_rationale, solution_steps, technique, scaffold_note,
   time_budget_seconds, visual, generated_by, reviewed)
VALUES
  ('g2-s5-length_division-difficult-0007', 2, 5, 'length_division', 'difficult', '{"total": 44, "per_group": 5, "leftover": 4}'::jsonb, '44 candies are packed into bags of 5 candies each, with 4 candies left over that don''t fill a whole bag. How many FULL bags are there?', '["5", "9", "8", "44"]'::jsonb, '8', '["counted the leftover as an extra full bag", "gave the total number of candies instead of the number of bags", "gave only part of the full-bag count"]'::jsonb, '(44 - 4) / 5 = 8 full bags, with 4 candies left over.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s5-length_division-difficult-0008', 2, 5, 'length_division', 'difficult', '{"total": 34, "per_group": 4, "leftover": 2}'::jsonb, '34 candies are packed into bags of 4 candies each, with 2 candies left over that don''t fill a whole bag. How many FULL bags are there?', '["4", "9", "8", "34"]'::jsonb, '8', '["counted the leftover as an extra full bag", "gave the total number of candies instead of the number of bags", "gave only part of the full-bag count"]'::jsonb, '(34 - 2) / 4 = 8 full bags, with 2 candies left over.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0001', 2, 6, 'averages', 'easy', '{"vals": [42, 38, 58]}'::jsonb, 'What is the average of 42, 38, 58?', '["138", "46", "47", "58"]'::jsonb, '46', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(42+38+58) / 3 = 138/3 = 46.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0002', 2, 6, 'averages', 'easy', '{"vals": [18, 16, 35]}'::jsonb, 'What is the average of 18, 16, 35?', '["23", "24", "69", "35"]'::jsonb, '23', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(18+16+35) / 3 = 69/3 = 23.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0003', 2, 6, 'averages', 'easy', '{"vals": [58, 19, 22]}'::jsonb, 'What is the average of 58, 19, 22?', '["99", "33", "58", "34"]'::jsonb, '33', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(58+19+22) / 3 = 99/3 = 33.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0004', 2, 6, 'averages', 'easy', '{"vals": [12, 12, 18]}'::jsonb, 'What is the average of 12, 12, 18?', '["14", "15", "42", "18"]'::jsonb, '14', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(12+12+18) / 3 = 42/3 = 14.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0005', 2, 6, 'averages', 'easy', '{"vals": [49, 57, 29]}'::jsonb, 'What is the average of 49, 57, 29?', '["45", "135", "46", "57"]'::jsonb, '45', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(49+57+29) / 3 = 135/3 = 45.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0006', 2, 6, 'averages', 'easy', '{"vals": [40, 11, 33]}'::jsonb, 'What is the average of 40, 11, 33?', '["84", "28", "29", "40"]'::jsonb, '28', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(40+11+33) / 3 = 84/3 = 28.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0007', 2, 6, 'averages', 'easy', '{"vals": [40, 26, 51]}'::jsonb, 'What is the average of 40, 26, 51?', '["40", "39", "51", "117"]'::jsonb, '39', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(40+26+51) / 3 = 117/3 = 39.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-easy-0008', 2, 6, 'averages', 'easy', '{"vals": [57, 56, 13]}'::jsonb, 'What is the average of 57, 56, 13?', '["43", "42", "57", "126"]'::jsonb, '42', '["gave the total instead of dividing by the count", "gave the largest value instead of the average", "off by one from the correct average"]'::jsonb, '(57+56+13) / 3 = 126/3 = 42.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0001', 2, 6, 'averages', 'average', '{"known": [37, 30, 41], "target_avg": 40}'::jsonb, 'The average of 4 numbers is 40. Three of the numbers are 37, 30, 41. What is the fourth number?', '["40", "52", "56", "160"]'::jsonb, '52', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 40 sum to 160. Known numbers sum to 108, so the missing one is 160 - 108 = 52.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0002', 2, 6, 'averages', 'average', '{"known": [34, 49, 37], "target_avg": 35}'::jsonb, 'The average of 4 numbers is 35. Three of the numbers are 34, 49, 37. What is the fourth number?', '["20", "100", "140", "35"]'::jsonb, '20', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 35 sum to 140. Known numbers sum to 120, so the missing one is 140 - 120 = 20.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0003', 2, 6, 'averages', 'average', '{"known": [39, 35, 26], "target_avg": 55}'::jsonb, 'The average of 4 numbers is 55. Three of the numbers are 39, 35, 26. What is the fourth number?', '["120", "55", "220", "125"]'::jsonb, '120', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 55 sum to 220. Known numbers sum to 100, so the missing one is 220 - 100 = 120.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0004', 2, 6, 'averages', 'average', '{"known": [27, 50, 29], "target_avg": 49}'::jsonb, 'The average of 4 numbers is 49. Three of the numbers are 27, 50, 29. What is the fourth number?', '["16", "90", "196", "49"]'::jsonb, '90', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 49 sum to 196. Known numbers sum to 106, so the missing one is 196 - 106 = 90.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0005', 2, 6, 'averages', 'average', '{"known": [42, 42, 35], "target_avg": 35}'::jsonb, 'The average of 4 numbers is 35. Three of the numbers are 42, 42, 35. What is the fourth number?', '["21", "35", "98", "140"]'::jsonb, '21', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 35 sum to 140. Known numbers sum to 119, so the missing one is 140 - 119 = 21.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0006', 2, 6, 'averages', 'average', '{"known": [29, 23, 38], "target_avg": 46}'::jsonb, 'The average of 4 numbers is 46. Three of the numbers are 29, 23, 38. What is the fourth number?', '["94", "46", "99", "184"]'::jsonb, '94', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 46 sum to 184. Known numbers sum to 90, so the missing one is 184 - 90 = 94.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0007', 2, 6, 'averages', 'average', '{"known": [29, 21, 29], "target_avg": 55}'::jsonb, 'The average of 4 numbers is 55. Three of the numbers are 29, 21, 29. What is the fourth number?', '["220", "55", "146", "141"]'::jsonb, '141', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 55 sum to 220. Known numbers sum to 79, so the missing one is 220 - 79 = 141.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-average-0008', 2, 6, 'averages', 'average', '{"known": [40, 28, 43], "target_avg": 40}'::jsonb, 'The average of 4 numbers is 40. Three of the numbers are 40, 28, 43. What is the fourth number?', '["40", "160", "49", "62"]'::jsonb, '49', '["subtracted incorrectly when isolating the missing value", "gave the average itself instead of the missing number", "forgot to subtract the known numbers'' total at all"]'::jsonb, '4 numbers averaging 40 sum to 160. Known numbers sum to 111, so the missing one is 160 - 111 = 49.', NULL, '', 30, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0001', 2, 6, 'averages', 'difficult', '{"vals": [38, 36, 15, 39], "removed": 38}'::jsonb, 'The average of the numbers 38, 36, 15, 39 is 32. If 38 is removed, what is the new average of the remaining 3 numbers?', '["90", "30", "32", "31"]'::jsonb, '30', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 38 leaves a total of 128 - 38 = 90, and 90/3 = 30.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0002', 2, 6, 'averages', 'difficult', '{"vals": [31, 34, 16, 15], "removed": 15}'::jsonb, 'The average of the numbers 31, 34, 16, 15 is 24. If 15 is removed, what is the new average of the remaining 3 numbers?', '["27", "24", "81", "28"]'::jsonb, '27', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 15 leaves a total of 96 - 15 = 81, and 81/3 = 27.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0003', 2, 6, 'averages', 'difficult', '{"vals": [39, 17, 10, 18], "removed": 18}'::jsonb, 'The average of the numbers 39, 17, 10, 18 is 21. If 18 is removed, what is the new average of the remaining 3 numbers?', '["22", "66", "23", "21"]'::jsonb, '22', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 18 leaves a total of 84 - 18 = 66, and 66/3 = 22.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0004', 2, 6, 'averages', 'difficult', '{"vals": [36, 20, 17, 19], "removed": 20}'::jsonb, 'The average of the numbers 36, 20, 17, 19 is 23. If 20 is removed, what is the new average of the remaining 3 numbers?', '["24", "72", "25", "23"]'::jsonb, '24', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 20 leaves a total of 92 - 20 = 72, and 72/3 = 24.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0005', 2, 6, 'averages', 'difficult', '{"vals": [18, 16, 20, 30], "removed": 18}'::jsonb, 'The average of the numbers 18, 16, 20, 30 is 21. If 18 is removed, what is the new average of the remaining 3 numbers?', '["66", "22", "21", "23"]'::jsonb, '22', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 18 leaves a total of 84 - 18 = 66, and 66/3 = 22.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0006', 2, 6, 'averages', 'difficult', '{"vals": [37, 30, 34, 11], "removed": 37}'::jsonb, 'The average of the numbers 37, 30, 34, 11 is 28. If 37 is removed, what is the new average of the remaining 3 numbers?', '["25", "75", "28", "26"]'::jsonb, '25', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 37 leaves a total of 112 - 37 = 75, and 75/3 = 25.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0007', 2, 6, 'averages', 'difficult', '{"vals": [37, 22, 10, 19], "removed": 19}'::jsonb, 'The average of the numbers 37, 22, 10, 19 is 22. If 19 is removed, what is the new average of the remaining 3 numbers?', '["22", "69", "23", "24"]'::jsonb, '23', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 19 leaves a total of 88 - 19 = 69, and 69/3 = 23.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-averages-difficult-0008', 2, 6, 'averages', 'difficult', '{"vals": [28, 26, 15, 31], "removed": 31}'::jsonb, 'The average of the numbers 28, 26, 15, 31 is 25. If 31 is removed, what is the new average of the remaining 3 numbers?', '["69", "24", "23", "25"]'::jsonb, '23', '["gave the original average instead of recomputing", "gave the new total instead of dividing by the new count", "off by one from the correct new average"]'::jsonb, 'Removing 31 leaves a total of 100 - 31 = 69, and 69/3 = 23.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-data_graph_reading-easy-0001', 2, 6, 'data_graph_reading', 'easy', '{"vals": {"apples": 204, "bananas": 187, "mangoes": 302, "grapes": 124}, "target": "apples"}'::jsonb, 'A bar graph shows fruits picked in one day:

| Fruit | Amount Picked |
|---|---|
| apples | 204 |
| bananas | 187 |
| mangoes | 302 |
| grapes | 124 |

How many apples were picked?', '["204", "302", "124", "187"]'::jsonb, '204', '["read a different fruit''s bar instead", "read a different fruit''s bar instead", "read a different fruit''s bar instead"]'::jsonb, 'Reading the apples row directly from the table gives 204.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-data_graph_reading-easy-0002', 2, 6, 'data_graph_reading', 'easy', '{"vals": {"apples": 265, "bananas": 203, "mangoes": 297, "grapes": 450}, "target": "apples"}'::jsonb, 'A bar graph shows fruits picked in one day:

| Fruit | Amount Picked |
|---|---|
| apples | 265 |
| bananas | 203 |
| mangoes | 297 |
| grapes | 450 |

How many apples were picked?', '["450", "265", "203", "297"]'::jsonb, '265', '["read a different fruit''s bar instead", "read a different fruit''s bar instead", "read a different fruit''s bar instead"]'::jsonb, 'Reading the apples row directly from the table gives 265.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-data_graph_reading-easy-0003', 2, 6, 'data_graph_reading', 'easy', '{"vals": {"apples": 419, "bananas": 370, "mangoes": 303, "grapes": 354}, "target": "bananas"}'::jsonb, 'A bar graph shows fruits picked in one day:

| Fruit | Amount Picked |
|---|---|
| apples | 419 |
| bananas | 370 |
| mangoes | 303 |
| grapes | 354 |

How many bananas were picked?', '["419", "303", "370", "354"]'::jsonb, '370', '["read a different fruit''s bar instead", "read a different fruit''s bar instead", "read a different fruit''s bar instead"]'::jsonb, 'Reading the bananas row directly from the table gives 370.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true),
  ('g2-s6-data_graph_reading-easy-0004', 2, 6, 'data_graph_reading', 'easy', '{"vals": {"apples": 205, "bananas": 53, "mangoes": 252, "grapes": 220}, "target": "grapes"}'::jsonb, 'A bar graph shows fruits picked in one day:

| Fruit | Amount Picked |
|---|---|
| apples | 205 |
| bananas | 53 |
| mangoes | 252 |
| grapes | 220 |

How many grapes were picked?', '["220", "252", "205", "53"]'::jsonb, '220', '["read a different fruit''s bar instead", "read a different fruit''s bar instead", "read a different fruit''s bar instead"]'::jsonb, 'Reading the grapes row directly from the table gives 220.', NULL, '', 15, NULL, 'template-mtap-g2-v1', true)
ON CONFLICT (question_code) DO NOTHING;
