update public.sq_lexicon_arena set wrong_c = 'forset' where grade_level = 3 and correct_spelling = 'forest' and wrong_a = 'forrest' and wrong_b = 'foresst' and wrong_c = 'forest''';
update public.sq_lexicon_arena set wrong_c = 'undred' where grade_level = 3 and correct_spelling = 'hundred' and wrong_a = 'hundrid' and wrong_b = 'hunderd' and wrong_c = 'hundred''';
update public.sq_lexicon_arena set wrong_b = 'trianngle' where grade_level = 3 and correct_spelling = 'triangle' and wrong_a = 'triangel' and wrong_b = 'triangle''' and wrong_c = 'triangl';
update public.sq_lexicon_arena set wrong_b = 'hangi' where grade_level = 3 and correct_spelling = 'hangin' and wrong_a = 'hanggin' and wrong_b = 'hanggin''' and wrong_c = 'hangen';
update public.sq_lexicon_arena set wrong_a = 'bunok' where grade_level = 3 and correct_spelling = 'bundok' and wrong_a = 'bundok''' and wrong_b = 'bundak' and wrong_c = 'bundoc';
update public.sq_lexicon_arena set wrong_c = 'mabanog' where grade_level = 3 and correct_spelling = 'mabango' and wrong_a = 'mabanggo' and wrong_b = 'mabangoh' and wrong_c = 'mabango''';
update public.sq_lexicon_arena set wrong_c = 'tkaot' where grade_level = 3 and correct_spelling = 'takot' and wrong_a = 'takut' and wrong_b = 'takkot' and wrong_c = 'takot''';
update public.sq_lexicon_arena set wrong_b = 'probinsay' where grade_level = 3 and correct_spelling = 'probinsya' and wrong_a = 'probinsiya' and wrong_b = 'probinsya''' and wrong_c = 'probinsa';
update public.sq_lexicon_arena set wrong_c = 'lngsod' where grade_level = 3 and correct_spelling = 'lungsod' and wrong_a = 'lunsod' and wrong_b = 'lungsud' and wrong_c = 'lungsod''';
update public.sq_lexicon_arena set wrong_c = 'arall' where grade_level = 3 and correct_spelling = 'aral' and wrong_a = 'arral' and wrong_b = 'araal' and wrong_c = 'arral''';
update public.sq_lexicon_arena set wrong_c = 'iblog' where grade_level = 3 and correct_spelling = 'bilog' and wrong_a = 'bilogg' and wrong_b = 'bilug' and wrong_c = 'bilog''';
update public.sq_lexicon_arena set wrong_c = 'arw' where grade_level = 3 and correct_spelling = 'araw' and wrong_a = 'arraw' and wrong_b = 'arau' and wrong_c = 'araw''';
update public.sq_lexicon_arena set wrong_b = 'laih' where grade_level = 3 and correct_spelling = 'lahi' and wrong_a = 'lahee' and wrong_b = 'lahi''' and wrong_c = 'laahi';
update public.sq_lexicon_arena set wrong_c = 'yungbi' where grade_level = 3 and correct_spelling = 'yungib' and wrong_a = 'yunggib' and wrong_b = 'yungeeb' and wrong_c = 'yungib''';
update public.sq_lexicon_arena set wrong_c = 'simie' where grade_level = 4 and correct_spelling = 'simile' and wrong_a = 'simily' and wrong_b = 'simmile' and wrong_c = 'simile''';
update public.sq_lexicon_arena set wrong_c = 'portagonist' where grade_level = 4 and correct_spelling = 'protagonist' and wrong_a = 'protaganist' and wrong_b = 'protagonest' and wrong_c = 'protagonist''';
update public.sq_lexicon_arena set wrong_b = 'eqaivalent' where grade_level = 4 and correct_spelling = 'equivalent' and wrong_a = 'equivalant' and wrong_b = 'equivalent''' and wrong_c = 'equivelent';
update public.sq_lexicon_arena set wrong_c = 'vitaimns' where grade_level = 4 and correct_spelling = 'vitamins' and wrong_a = 'vitamens' and wrong_b = 'vitammins' and wrong_c = 'vitamins''';
update public.sq_lexicon_arena set wrong_b = 'prepositon' where grade_level = 4 and correct_spelling = 'preposition' and wrong_a = 'preposeition' and wrong_b = 'preposition''' and wrong_c = 'prepositoin';
update public.sq_lexicon_arena set wrong_b = 'cnter' where grade_level = 4 and correct_spelling = 'center' and wrong_a = 'centar' and wrong_b = 'centre''' and wrong_c = 'centerr';
update public.sq_lexicon_arena set wrong_c = 'kwentogn-bayan' where grade_level = 4 and correct_spelling = 'kwentong-bayan' and wrong_a = 'kwentong bayan' and wrong_b = 'kwentong-bayann' and wrong_c = 'kuwentong-bayan''';
update public.sq_lexicon_arena set wrong_c = 'aarl' where grade_level = 4 and correct_spelling = 'aral' and wrong_a = 'arral' and wrong_b = 'araal' and wrong_c = 'arral''';
update public.sq_lexicon_arena set wrong_c = 'bilo' where grade_level = 4 and correct_spelling = 'bilog' and wrong_a = 'bilogg' and wrong_b = 'bilug' and wrong_c = 'bilog''';
update public.sq_lexicon_arena set wrong_c = 'sukta' where grade_level = 4 and correct_spelling = 'sukat' and wrong_a = 'sukatt' and wrong_b = 'sukkat' and wrong_c = 'sukat''';
update public.sq_lexicon_arena set wrong_b = 'sastansya' where grade_level = 4 and correct_spelling = 'sustansya' and wrong_a = 'sustansiya' and wrong_b = 'sustansya''' and wrong_c = 'sustanssya';
update public.sq_lexicon_arena set wrong_b = 'root wod' where grade_level = 4 and correct_spelling = 'root word' and wrong_a = 'rootword' and wrong_b = 'root-word''' and wrong_c = 'rootwoard';
update public.sq_lexicon_arena set wrong_b = 'comaa' where grade_level = 4 and correct_spelling = 'comma' and wrong_a = 'comah' and wrong_b = 'comma''' and wrong_c = 'commma';
update public.sq_lexicon_arena set wrong_b = 'tandang panannong' where grade_level = 4 and correct_spelling = 'tandang pananong' and wrong_a = 'tandapananong' and wrong_b = 'tandang-pananong''' and wrong_c = 'tandangpananong';
update public.sq_lexicon_arena set wrong_b = 'sistamang paghinga' where grade_level = 4 and correct_spelling = 'sistemang paghinga' and wrong_a = 'sistemapaghinga' and wrong_b = 'sistemang-paghinga''' and wrong_c = 'sistemang paghingga';
update public.sq_lexicon_arena set wrong_c = 'eqator' where grade_level = 6 and correct_spelling = 'equator' and wrong_a = 'equater' and wrong_b = 'equatorr' and wrong_c = 'equater''';
update public.sq_lexicon_arena set wrong_c = 'tarde' where grade_level = 6 and correct_spelling = 'trade' and wrong_a = 'traed' and wrong_b = 'tradee' and wrong_c = 'trade''';
update public.sq_lexicon_arena set wrong_b = 'economixs' where grade_level = 6 and correct_spelling = 'economics' and wrong_a = 'economicks' and wrong_b = 'economics''' and wrong_c = 'econimics';
update public.sq_lexicon_arena set wrong_b = 'grund', wrong_c = 'gerun' where grade_level = 6 and correct_spelling = 'gerund' and wrong_a = 'gerrund' and wrong_b = 'gerrund''' and wrong_c = 'gerund''';
update public.sq_lexicon_arena set wrong_c = 'kontinenta' where grade_level = 6 and correct_spelling = 'kontinente' and wrong_a = 'kontinenteh' and wrong_b = 'kontinnente' and wrong_c = 'kontinente''';
update public.sq_lexicon_arena set wrong_b = 'ekonomikss' where grade_level = 6 and correct_spelling = 'ekonomiks' and wrong_a = 'ekonomicks' and wrong_b = 'ekonomiks''' and wrong_c = 'ekonimiks';
update public.sq_lexicon_arena set wrong_c = 'panenaw' where grade_level = 6 and correct_spelling = 'pananaw' and wrong_a = 'pananauw' and wrong_b = 'pananaww' and wrong_c = 'pananaw''';
update public.sq_lexicon_arena set wrong_c = 'pagmamaalbis' where grade_level = 6 and correct_spelling = 'pagmamalabis' and wrong_a = 'pagmamalabiss' and wrong_b = 'pagmamalabbis' and wrong_c = 'pagmamalabis''';
update public.sq_lexicon_arena set wrong_c = 'mmean' where grade_level = 6 and correct_spelling = 'mean' and wrong_a = 'meen' and wrong_b = 'meann' and wrong_c = 'mean''';
update public.sq_lexicon_arena set wrong_a = 'puberrty' where grade_level = 6 and correct_spelling = 'puberty' and wrong_a = 'puberty''' and wrong_b = 'puburty' and wrong_c = 'pubertty';
update public.sq_lexicon_arena set wrong_c = 'barryabol' where grade_level = 6 and correct_spelling = 'baryabol' and wrong_a = 'baryable' and wrong_b = 'baryabull' and wrong_c = 'baryabol''';
update public.sq_lexicon_arena set wrong_c = 'posibildiad' where grade_level = 6 and correct_spelling = 'posibilidad' and wrong_a = 'posibiliidad' and wrong_b = 'posibillidad' and wrong_c = 'posibiliidad''';
update public.sq_lexicon_arena set wrong_b = 'raniforest' where grade_level = 6 and correct_spelling = 'rainforest' and wrong_a = 'rainforrest' and wrong_b = 'rain forest''' and wrong_c = 'rainfores';
update public.sq_lexicon_arena set wrong_c = 'sesimograp' where grade_level = 6 and correct_spelling = 'seismograp' and wrong_a = 'seismograpp' and wrong_b = 'seysmograp' and wrong_c = 'seismograph''';
update public.sq_lexicon_arena set wrong_c = 'llindol' where grade_level = 6 and correct_spelling = 'lindol' and wrong_a = 'lindoll' and wrong_b = 'lindul' and wrong_c = 'lindoll''';