-- Baseline documentation migration: weekly progress tracking scope only.
--
-- Context: this repo's local supabase/migrations/ was missing ~138 migrations that already
-- exist live (only the boss_fight_schema migration was tracked). Reconciling the FULL history
-- requires `supabase db pull`/`db dump`, which needs Docker Desktop; that was blocked on this
-- machine by a BIOS-level virtualization setting. As a fallback, this migration hand-documents
-- (via SQL introspection against the live project) only the objects touched by the
-- weekly-progress redesign (see docs/weekly-progress-redesign-plan.md) so at least this scope
-- has an accurate, version-controlled record before Phase 1 adds new tables alongside it.
--
-- All objects below already exist in production as of 2026-08-11 — every statement is written
-- idempotently (IF NOT EXISTS / CREATE OR REPLACE / DROP+CREATE POLICY) so applying this is a
-- no-op against the live database. It exists for historical accuracy and future local dev
-- bootstrapping, not to change anything.
--
-- The other ~135 migrations outside this scope remain undocumented locally. That gap is tracked
-- as a known follow-up, not resolved here.

-- ============================================================================
-- TABLE: weekly_packages
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.weekly_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL DEFAULT 'damien',
  week_starting_date date NOT NULL,
  package_data jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  quiz_attempts jsonb DEFAULT '{}'::jsonb,
  character_stats jsonb DEFAULT '{"xp": 0, "gold": 0, "level": 1}'::jsonb,
  mastered_quizzes jsonb DEFAULT '[]'::jsonb,
  journal_logs jsonb DEFAULT '{}'::jsonb,
  mastery_count integer DEFAULT 0,
  purchased_items integer DEFAULT 0,
  honor_grants integer DEFAULT 0,
  achievements jsonb DEFAULT '{}'::jsonb,
  guild_sessions_count integer DEFAULT 0,
  monster_battles_won integer DEFAULT 0,
  sibling_battles_won integer DEFAULT 0,
  perfect_quizzes integer DEFAULT 0,
  dummy_battles_won integer DEFAULT 0,
  eggs_hatched integer DEFAULT 0,
  curios_graduated integer DEFAULT 0,
  trades_completed integer DEFAULT 0,
  legendaries_caught integer DEFAULT 0,
  tutor_rerolls integer DEFAULT 0,
  tatay_battles_won integer DEFAULT 0,
  tatay_battles_lost integer DEFAULT 0,
  CONSTRAINT weekly_packages_user_week_unique UNIQUE (user_id, week_starting_date)
);

CREATE INDEX IF NOT EXISTS idx_weekly_packages_user
  ON public.weekly_packages USING btree (user_id, week_starting_date);

ALTER TABLE public.weekly_packages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "weekly_packages: read all" ON public.weekly_packages;
CREATE POLICY "weekly_packages: read all" ON public.weekly_packages
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "weekly_packages: insert own" ON public.weekly_packages;
CREATE POLICY "weekly_packages: insert own" ON public.weekly_packages
  FOR INSERT TO authenticated WITH CHECK (current_app_user_id() = user_id);

DROP POLICY IF EXISTS "weekly_packages: update own" ON public.weekly_packages;
CREATE POLICY "weekly_packages: update own" ON public.weekly_packages
  FOR UPDATE TO authenticated
  USING (current_app_user_id() = user_id)
  WITH CHECK (current_app_user_id() = user_id);

-- ============================================================================
-- TABLE: grade_content_owners  (grade -> canonical content-author user_id)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.grade_content_owners (
  grade integer PRIMARY KEY CHECK (grade >= 2 AND grade <= 6),
  user_id text NOT NULL
);

ALTER TABLE public.grade_content_owners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "grade_content_owners: read all" ON public.grade_content_owners;
CREATE POLICY "grade_content_owners: read all" ON public.grade_content_owners
  FOR SELECT TO public USING (true);

-- ============================================================================
-- TABLE: user_completed_questions  (text-hash based Monster Arena answered-state)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.user_completed_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id text NOT NULL DEFAULT 'damien',
  quest_type text NOT NULL,
  question_id uuid NOT NULL,
  completed_at timestamptz DEFAULT now(),
  CONSTRAINT user_completed_questions_user_id_quest_type_question_id_key
    UNIQUE (user_id, quest_type, question_id)
);

CREATE INDEX IF NOT EXISTS idx_completed_lookup
  ON public.user_completed_questions USING btree (user_id, quest_type);

ALTER TABLE public.user_completed_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_completed_questions: read all" ON public.user_completed_questions;
CREATE POLICY "user_completed_questions: read all" ON public.user_completed_questions
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "user_completed_questions: insert own" ON public.user_completed_questions;
CREATE POLICY "user_completed_questions: insert own" ON public.user_completed_questions
  FOR INSERT TO authenticated WITH CHECK (current_app_user_id() = user_id);

-- ============================================================================
-- VIEW: weekly_packages_public  (strips correct_answer from embedded quiz JSON)
-- ============================================================================
CREATE OR REPLACE VIEW public.weekly_packages_public AS
SELECT
  id,
  week_starting_date,
  created_at,
  quiz_attempts,
  character_stats,
  mastered_quizzes,
  journal_logs,
  mastery_count,
  purchased_items,
  honor_grants,
  achievements,
  user_id,
  guild_sessions_count,
  monster_battles_won,
  sibling_battles_won,
  perfect_quizzes,
  dummy_battles_won,
  strip_weekly_quiz_answers(package_data) AS package_data,
  eggs_hatched,
  curios_graduated,
  trades_completed,
  legendaries_caught,
  tutor_rerolls,
  tatay_battles_won,
  tatay_battles_lost
FROM public.weekly_packages;

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Strips `correct_answer` out of every embedded quiz question in package_data,
-- for the public/student-facing view.
CREATE OR REPLACE FUNCTION public.strip_weekly_quiz_answers(data jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
declare
  day_key text;
  subject_key text;
  day_obj jsonb;
  subj_obj jsonb;
  quiz_arr jsonb;
  new_quiz jsonb;
  q jsonb;
  result jsonb := data;
begin
  if data is null or jsonb_typeof(data) <> 'object' then
    return data;
  end if;

  for day_key in select jsonb_object_keys(data) loop
    day_obj := data -> day_key;
    if jsonb_typeof(day_obj) = 'object' then
      for subject_key in select jsonb_object_keys(day_obj) loop
        subj_obj := day_obj -> subject_key;
        if jsonb_typeof(subj_obj) = 'object' then
          quiz_arr := subj_obj -> 'quiz';
          if jsonb_typeof(quiz_arr) = 'array' then
            new_quiz := '[]'::jsonb;
            for q in select * from jsonb_array_elements(quiz_arr) loop
              new_quiz := new_quiz || jsonb_build_array(q - 'correct_answer');
            end loop;
            result := jsonb_set(result, array[day_key, subject_key, 'quiz'], new_quiz);
          end if;
        end if;
      end loop;
    end if;
  end loop;

  return result;
end;
$function$;

-- Atomically applies xp/gold deltas to a user's current-week character_stats and
-- resolves level-ups. NOTE: the level-up threshold formula (500 + level*100) is
-- duplicated in hooks/useWeeklyData.ts (TypeScript) — see redesign plan's failure-mode #6.
CREATE OR REPLACE FUNCTION public.apply_character_deltas(p_user_id text, p_week_starting_date date, p_xp_delta integer DEFAULT 0, p_gold_delta integer DEFAULT 0)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  cur_xp integer;
  cur_gold integer;
  cur_level integer;
  final_xp integer;
  final_level integer;
  final_gold integer;
  result jsonb;
begin
  select
    coalesce((character_stats->>'xp')::int, 0),
    coalesce((character_stats->>'gold')::int, 0),
    coalesce((character_stats->>'level')::int, 1)
  into cur_xp, cur_gold, cur_level
  from public.weekly_packages
  where user_id = p_user_id and week_starting_date = p_week_starting_date
  for update;

  if not found then
    raise exception 'No weekly_packages row for user % week %', p_user_id, p_week_starting_date;
  end if;

  final_xp := cur_xp + p_xp_delta;
  final_level := cur_level;
  final_gold := cur_gold + p_gold_delta;

  while final_xp >= (500 + final_level * 100) loop
    final_xp := final_xp - (500 + final_level * 100);
    final_level := final_level + 1;
  end loop;

  update public.weekly_packages
  set character_stats = jsonb_build_object('xp', final_xp, 'level', final_level, 'gold', final_gold)
  where user_id = p_user_id and week_starting_date = p_week_starting_date
  returning character_stats into result;

  return result;
end;
$function$;

-- Increments one of a fixed allowlist of weekly counters by 1 for "this week" (computed
-- server-side via date_trunc, but with no explicit timezone -- uses the DB session default).
-- NOTE: only 5 of the 12 weekly counter columns are reachable through this RPC; the other 7
-- (eggs_hatched, curios_graduated, trades_completed, legendaries_caught, tutor_rerolls,
-- tatay_battles_won/lost) are written through other paths.
CREATE OR REPLACE FUNCTION public.increment_weekly_counter(p_user_id text, p_column text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  current_sunday date := date_trunc('week', CURRENT_DATE)::date;
BEGIN
  IF p_column NOT IN (
    'guild_sessions_count', 'monster_battles_won', 'sibling_battles_won',
    'perfect_quizzes', 'dummy_battles_won'
  ) THEN
    RAISE EXCEPTION 'invalid counter column: %', p_column;
  END IF;

  EXECUTE format(
    'UPDATE weekly_packages SET %I = COALESCE(%I, 0) + 1 WHERE user_id = $1 AND week_starting_date = $2',
    p_column, p_column
  ) USING p_user_id, current_sunday;
END;
$function$;

-- Grades a single Monster Arena question by matching question text against package_data
-- (no stable question id -- see redesign plan's failure-mode #9).
CREATE OR REPLACE FUNCTION public.grade_monster_question(p_user_id text, p_week_starting_date date, p_question_text text, p_selected text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  pkg jsonb;
  day_key text;
  subj_key text;
  quiz_arr jsonb;
  q jsonb;
  found_correct text := null;
begin
  select package_data into pkg
  from public.weekly_packages
  where user_id = p_user_id and week_starting_date = p_week_starting_date;

  if pkg is not null then
    <<day_loop>>
    for day_key in select jsonb_object_keys(pkg) loop
      continue when jsonb_typeof(pkg -> day_key) <> 'object';
      for subj_key in select jsonb_object_keys(pkg -> day_key) loop
        continue when jsonb_typeof(pkg -> day_key -> subj_key) <> 'object';
        quiz_arr := coalesce(pkg -> day_key -> subj_key -> 'quiz', pkg -> day_key -> subj_key -> 'questions');
        if jsonb_typeof(quiz_arr) = 'array' then
          for q in select * from jsonb_array_elements(quiz_arr) loop
            if (q ->> 'question') = p_question_text or (q ->> 'problem_prompt') = p_question_text then
              found_correct := q ->> 'correct_answer';
              exit day_loop;
            end if;
          end loop;
        end if;
      end loop;
    end loop day_loop;
  end if;

  return jsonb_build_object(
    'correct', (found_correct is not null and p_selected = found_correct),
    'correct_answer', found_correct
  );
end;
$function$;

-- Grades a full day/subject quiz array in one call.
CREATE OR REPLACE FUNCTION public.grade_weekly_quiz(p_user_id text, p_week_starting_date date, p_day text, p_subject text, p_selected jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  quiz_arr jsonb;
  q jsonb;
  idx int := 0;
  correct_count int := 0;
  total int := 0;
  correct_answers jsonb := '[]'::jsonb;
  selected_opt text;
begin
  select package_data -> p_day -> p_subject -> 'quiz'
  into quiz_arr
  from public.weekly_packages
  where user_id = p_user_id and week_starting_date = p_week_starting_date;

  if quiz_arr is null or jsonb_typeof(quiz_arr) <> 'array' then
    return jsonb_build_object('correct_count', 0, 'total', 0, 'is_perfect', false, 'correct_answers', '[]'::jsonb);
  end if;

  for q in select * from jsonb_array_elements(quiz_arr) loop
    total := total + 1;
    selected_opt := p_selected ->> idx::text;
    if selected_opt = (q ->> 'correct_answer') then
      correct_count := correct_count + 1;
    end if;
    correct_answers := correct_answers || jsonb_build_array(q -> 'correct_answer');
    idx := idx + 1;
  end loop;

  return jsonb_build_object(
    'correct_count', correct_count,
    'total', total,
    'is_perfect', (total > 0 and correct_count = total),
    'correct_answers', correct_answers
  );
end;
$function$;

-- Grades an ad-hoc set of answers (weekly review) by matching question text across the whole
-- package_data blob, same text-matching fragility as grade_monster_question.
CREATE OR REPLACE FUNCTION public.grade_weekly_review_quiz(p_user_id text, p_week_starting_date date, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  pkg jsonb;
  day_key text;
  subj_key text;
  quiz_arr jsonb;
  q jsonb;
  ans jsonb;
  total int := 0;
  correct_count int := 0;
  correct_answers jsonb := '[]'::jsonb;
  found_correct text;
  qtext text;
  selected_opt text;
begin
  select package_data into pkg
  from public.weekly_packages
  where user_id = p_user_id and week_starting_date = p_week_starting_date;

  if pkg is null then
    return jsonb_build_object('correct_count', 0, 'total', 0, 'is_perfect', false, 'correct_answers', '[]'::jsonb);
  end if;

  for ans in select * from jsonb_array_elements(p_answers) loop
    total := total + 1;
    qtext := ans ->> 'question';
    selected_opt := ans ->> 'selected';
    found_correct := null;

    <<day_loop>>
    for day_key in select jsonb_object_keys(pkg) loop
      continue when jsonb_typeof(pkg -> day_key) <> 'object';
      for subj_key in select jsonb_object_keys(pkg -> day_key) loop
        continue when jsonb_typeof(pkg -> day_key -> subj_key) <> 'object';
        quiz_arr := coalesce(pkg -> day_key -> subj_key -> 'quiz', pkg -> day_key -> subj_key -> 'questions');
        if jsonb_typeof(quiz_arr) = 'array' then
          for q in select * from jsonb_array_elements(quiz_arr) loop
            if (q ->> 'question') = qtext then
              found_correct := q ->> 'correct_answer';
              exit day_loop;
            end if;
          end loop;
        end if;
      end loop;
    end loop day_loop;

    if found_correct is not null and selected_opt = found_correct then
      correct_count := correct_count + 1;
    end if;
    correct_answers := correct_answers || jsonb_build_array(found_correct);
  end loop;

  return jsonb_build_object(
    'correct_count', correct_count,
    'total', total,
    'is_perfect', (total > 0 and correct_count = total),
    'correct_answers', correct_answers
  );
end;
$function$;

-- Admin (passcode-gated): upserts a grade's authored content for a given week. On a brand-new
-- future week, stat columns are deliberately left NULL (the "pre-staged" sentinel -- see
-- redesign plan's failure-mode #3) so useWeeklyData carries forward real progress instead of
-- freezing stats at today's snapshot.
CREATE OR REPLACE FUNCTION public.admin_upsert_weekly_package_data(p_passcode text, p_user_id text, p_week_starting_date date, p_package_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  PERFORM public.check_admin_passcode(p_passcode);

  INSERT INTO public.weekly_packages (
    user_id, week_starting_date, package_data,
    character_stats, journal_logs, achievements, mastery_count, purchased_items,
    honor_grants, quiz_attempts, mastered_quizzes, guild_sessions_count,
    monster_battles_won, sibling_battles_won, perfect_quizzes, dummy_battles_won
  ) VALUES (
    p_user_id, p_week_starting_date, p_package_data,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
  )
  ON CONFLICT (user_id, week_starting_date) DO UPDATE SET package_data = EXCLUDED.package_data;
END;
$function$;

-- Admin (passcode-gated): overwrites a user's character_stats for a given week outright.
CREATE OR REPLACE FUNCTION public.admin_set_character_stats(p_passcode text, p_user_id text, p_week_starting_date date, p_character_stats jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  PERFORM public.check_admin_passcode(p_passcode);

  UPDATE public.weekly_packages
  SET character_stats = p_character_stats
  WHERE user_id = p_user_id AND week_starting_date = p_week_starting_date;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'no weekly package row for this user/week';
  END IF;
END;
$function$;

-- Admin (passcode-gated): awards gold and bumps honor_grants for a given week.
CREATE OR REPLACE FUNCTION public.admin_award_gold(p_passcode text, p_user_id text, p_week_starting_date date, p_amount integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  new_stats jsonb;
BEGIN
  PERFORM public.check_admin_passcode(p_passcode);

  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'amount must be positive';
  END IF;

  UPDATE public.weekly_packages
  SET character_stats = jsonb_set(
        character_stats, '{gold}',
        to_jsonb(COALESCE((character_stats->>'gold')::integer, 0) + p_amount)
      ),
      honor_grants = COALESCE(honor_grants, 0) + 1
  WHERE user_id = p_user_id AND week_starting_date = p_week_starting_date
  RETURNING character_stats INTO new_stats;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'no weekly package row for this user/week';
  END IF;

  RETURN new_stats;
END;
$function$;
