-- Lexicon Arena Grade 6 -- 206 entries to meet the 200-per-grade target.
insert into public.sq_lexicon_arena (term_id, is_active, grade_level, language, definition, correct_spelling, wrong_a, wrong_b, wrong_c) values
  (1, true, 6, 'English', 'The basic structural and functional unit of all living things', 'cell', 'sel', 'celll', 'cel'),
  (1, true, 6, 'English', 'The part of the cell that controls its activities and contains DNA', 'nucleus', 'nucleous', 'nukleus', 'nucleuss'),
  (1, true, 6, 'English', 'A chemical change that produces a new substance', 'reaction', 'reacton', 'reacshun', 'reakction'),
  (1, true, 6, 'English', 'The smallest unit of an element that retains its properties', 'atom', 'attom', 'atoom', 'atum'),
  (1, true, 6, 'English', 'A pure substance made of only one type of atom', 'element', 'elament', 'elemant', 'elementt'),
  (1, true, 6, 'English', 'A substance formed when two or more elements chemically combine', 'compound', 'compownd', 'compond', 'compoundd'),
  (1, true, 6, 'English', 'The amount of matter in an object', 'mass', 'mas', 'masss', 'mmass'),
  (1, true, 6, 'English', 'The force of gravity acting on an object''s mass', 'weight', 'wieght', 'weightt', 'waight'),
  (1, true, 6, 'English', 'The amount of space a substance or object occupies', 'volume', 'volum', 'volumme', 'voluume'),
  (1, true, 6, 'English', 'Mass per unit of volume of a substance', 'density', 'densety', 'densitty', 'densiti'),
  (1, true, 6, 'English', 'The transfer of thermal energy from a hotter to a cooler object', 'heat transfer', 'heat-transfer', 'heat transfar', 'heattransfer'),
  (1, true, 6, 'English', 'A push or pull that changes an object''s motion', 'force', 'forse', 'forcce', 'forc'),
  (1, true, 6, 'English', 'The rate at which an object''s velocity changes', 'acceleration', 'acceleraton', 'accelerashun', 'acceleraation'),
  (1, true, 6, 'English', 'The tendency of an object to resist a change in motion', 'inertia', 'inertea', 'inirtia', 'inertiaa'),
  (1, true, 6, 'English', 'A simple machine consisting of a rod that pivots on a fixed point', 'lever', 'levar', 'levver', 'leverr'),
  (1, true, 6, 'English', 'A simple machine with a slanted surface used to raise objects', 'inclined plane', 'inclined-plane', 'incline plane', 'inclindeplane'),
  (1, true, 6, 'English', 'A wheel with a groove that redirects the force of a pulled rope', 'pulley', 'pully', 'pulleyy', 'puley'),
  (1, true, 6, 'English', 'The process by which plants make their own food using sunlight', 'photosynthesis', 'photosinthesis', 'photosynthessis', 'fotosynthesis'),
  (1, true, 6, 'English', 'The process by which living things release energy from food', 'respiration', 'respiraton', 'respirashun', 'respireation'),
  (1, true, 6, 'English', 'A gas produced by plants during photosynthesis, needed by animals', 'oxygen', 'oxegen', 'oxygenn', 'oxigen'),
  (1, true, 6, 'English', 'A gas that plants absorb during photosynthesis', 'carbon dioxide', 'carbon-dioxide', 'carbondioxide', 'carbon dioxid'),
  (1, true, 6, 'English', 'The transfer of energy from one organism to another through food', 'food chain', 'foodchain', 'food-chain', 'food chian'),
  (1, true, 6, 'English', 'A network of interconnected food chains in an ecosystem', 'food web', 'foodweb', 'food-web', 'food wep'),
  (1, true, 6, 'English', 'An organism that makes its own food, like a plant', 'producer', 'produser', 'produccer', 'producerr'),
  (1, true, 6, 'English', 'An organism that eats other organisms for energy', 'consumer', 'consumar', 'consummer', 'consumerr'),
  (1, true, 6, 'English', 'An organism that breaks down dead matter for nutrients', 'decomposer', 'decomposar', 'decomposser', 'decomposerr'),
  (1, true, 6, 'English', 'The passing of traits from parents to offspring', 'heredity', 'hereddity', 'hereditty', 'hereditey'),
  (1, true, 6, 'English', 'A segment of DNA that determines a specific trait', 'gene', 'geen', 'genne', 'gean'),
  (1, true, 6, 'English', 'A structure in the cell nucleus that carries genetic information', 'chromosome', 'chromozome', 'chromosoome', 'chromosom'),
  (1, true, 6, 'English', 'A change in an organism''s genetic material', 'mutation', 'mutaton', 'mutashun', 'mutattion'),
  (1, true, 6, 'English', 'A large landmass made up of several countries', 'continent', 'continant', 'continentt', 'continnent'),
  (1, true, 6, 'English', 'The line of latitude that divides earth into northern and southern halves', 'equator', 'equater', 'equatorr', 'equater'''),
  (1, true, 6, 'English', 'An imaginary line used to measure longitude and time zones', 'meridian', 'meridean', 'meridiann', 'meredian'),
  (1, true, 6, 'English', 'A large region of the ocean between continents', 'ocean', 'oshun', 'oceon', 'oceann'),
  (1, true, 6, 'English', 'The physical features of a region, such as mountains and rivers', 'topography', 'topografy', 'topograpy', 'topograhpy'),
  (1, true, 6, 'English', 'The buying and selling of goods between countries', 'trade', 'traed', 'tradee', 'trade'''),
  (1, true, 6, 'English', 'Goods imported or exported between nations', 'commerce', 'commerse', 'comerce', 'commercee'),
  (1, true, 6, 'English', 'A group of countries joined for a common purpose', 'alliance', 'allience', 'alliancce', 'alliancee'),
  (1, true, 6, 'English', 'The study of how people use limited resources', 'economics', 'economicks', 'economics''', 'econimics'),
  (1, true, 6, 'English', 'Goods and services a country sells to other countries', 'exports', 'exportts', 'exportss', 'expots'),
  (1, true, 6, 'English', 'Goods a country buys from other countries', 'imports', 'importts', 'importss', 'impots'),
  (1, true, 6, 'English', 'A tax placed on imported or exported goods', 'tariff', 'tarrif', 'tariph', 'tarif'),
  (1, true, 6, 'English', 'The total value of goods and services a country produces in a year', 'gross domestic product', 'gross-domestic-product', 'gross domestic produkt', 'grossdomesticproduct'),
  (1, true, 6, 'English', 'A system where private individuals own and control businesses', 'capitalism', 'capitalisim', 'capitallism', 'capitalisem'),
  (1, true, 6, 'English', 'A system where the government owns and controls the economy', 'socialism', 'socialisim', 'sociallism', 'socialisem'),
  (1, true, 6, 'English', 'A sentence that contains one independent clause', 'simple sentence', 'simple-sentence', 'simple sentance', 'simplesentence'),
  (1, true, 6, 'English', 'A sentence made of two independent clauses joined by a conjunction', 'compound sentence', 'compound-sentence', 'compound sentance', 'compoundsentence'),
  (1, true, 6, 'English', 'A sentence with one independent and one dependent clause', 'complex sentence', 'complex-sentence', 'complex sentance', 'complexsentence'),
  (1, true, 6, 'English', 'A group of words with a subject and verb that cannot stand alone', 'dependent clause', 'dependent-clause', 'dependant clause', 'dependentclause'),
  (1, true, 6, 'English', 'A phrase that begins with a preposition and ends with a noun or pronoun', 'prepositional phrase', 'prepositional-phrase', 'preposicional phrase', 'prepositionalphrase'),
  (1, true, 6, 'English', 'A verb form ending in -ing that acts as a noun', 'gerund', 'gerrund', 'gerrund''', 'gerund'''),
  (1, true, 6, 'English', 'The basic form of a verb, often preceded by to', 'infinitive', 'infinitiv', 'infinitve', 'infinnitive'),
  (1, true, 6, 'English', 'A word or phrase that renames or explains a nearby noun', 'appositive', 'appositiv', 'appositve', 'appossitive'),
  (1, true, 6, 'English', 'A writer''s attitude toward the subject or audience', 'tone', 'toan', 'tonne', 'toane'),
  (1, true, 6, 'English', 'The overall feeling or atmosphere created by a piece of writing', 'mood', 'moode', 'moodd', 'moad'),
  (1, true, 6, 'English', 'The perspective from which a story is told', 'point of view', 'point-of-view', 'pointofview', 'point of veiw'),
  (1, true, 6, 'English', 'A story told using the pronouns I and we', 'first person', 'first-person', 'firstperson', 'first persoin'),
  (1, true, 6, 'English', 'A story told using pronouns like he, she, and they', 'third person', 'third-person', 'thirdperson', 'third persoin'),
  (1, true, 6, 'English', 'A writer''s use of exaggeration for emphasis or humor', 'hyperbole', 'hyperbol', 'hyperbolee', 'hiperbole'),
  (1, true, 6, 'English', 'A figure of speech that says one thing is another, without like or as', 'metaphor', 'metafor', 'metaphore', 'metaphour'),
  (1, true, 6, 'Filipino', 'Ang pinakamaliit na yunit ng buhay na organismo', 'selula', 'selyula', 'seluula', 'selulla'),
  (1, true, 6, 'Filipino', 'Ang bahagi ng selula na kumokontrol sa mga gawain nito', 'nukleus', 'nukleuss', 'nucleus', 'nukliyus'),
  (1, true, 6, 'Filipino', 'Ang proseso kung paano gumagawa ng sariling pagkain ang halaman', 'potosintesis', 'fotosintesis', 'potosinthesis', 'photosintesis'),
  (1, true, 6, 'Filipino', 'Ang proseso ng paglabas ng enerhiya mula sa pagkain', 'respirasyon', 'respirasyonn', 'respirassyon', 'respirasion'),
  (1, true, 6, 'Filipino', 'Ang hanay ng mga organismong nagpapasa ng enerhiya sa isa''t isa', 'tanikalang-pagkain', 'tanikalang pagkain', 'tanikalangpagkain', 'tanikalang-pagkaen'),
  (1, true, 6, 'Filipino', 'Ang organismong gumagawa ng sariling pagkain', 'tagagawa', 'taggagawa', 'tagagaawa', 'tagagawaa'),
  (1, true, 6, 'Filipino', 'Ang organismong kumakain ng ibang organismo', 'mamimili', 'mammimili', 'mamimilih', 'mamimilli'),
  (1, true, 6, 'Filipino', 'Ang organismong nagbubuwag ng patay na bagay', 'mapagtunaw', 'mapagtunauw', 'mapagtunnaw', 'mapagtunaww'),
  (1, true, 6, 'Filipino', 'Ang paglipat ng mga katangian mula sa magulang patungo sa anak', 'mana', 'manah', 'mannah', 'manaa'),
  (1, true, 6, 'Filipino', 'Ang pagbabago sa henetikong sangkap ng isang organismo', 'pagbabagong-anyo', 'pagbabagong anyo', 'pagbabagonganyo', 'pagbabagong-anyoh'),
  (1, true, 6, 'Filipino', 'Ang lakas na dahilan ng paggalaw o pagbabago ng galaw', 'puwersa', 'pwersa', 'puersa', 'puwerssa'),
  (1, true, 6, 'Filipino', 'Ang bilis ng pagbabago ng bilis ng galaw ng isang bagay', 'pabilis', 'pabiliss', 'pabbilis', 'pabilliss'),
  (1, true, 6, 'Filipino', 'Ang katangiang lumalaban sa pagbabago ng galaw', 'pagkawalang-galaw', 'pagkawalang galaw', 'pagkawalanggalaw', 'pagkawalang-gallaw'),
  (1, true, 6, 'Filipino', 'Ang simpleng makinang may pivot na ginagamit upang itaas ang bagay', 'paltik', 'palanka', 'paltikk', 'palankaa'),
  (1, true, 6, 'Filipino', 'Ang gulong na may guhit na nagbabago ng direksyon ng lubid', 'kalo', 'kaloh', 'kallo', 'kaloo'),
  (1, true, 6, 'Filipino', 'Ang malaking lupain na binubuo ng maraming bansa', 'kontinente', 'kontinenteh', 'kontinnente', 'kontinente'''),
  (1, true, 6, 'Filipino', 'Ang guhit na naghahati sa mundo sa hilaga at timog', 'ekwador', 'ekwadorr', 'ekwadur', 'ekuwador'),
  (1, true, 6, 'Filipino', 'Ang malaking bahagi ng dagat sa pagitan ng mga kontinente', 'karagatan', 'karagatann', 'karagataan', 'karaagatan'),
  (1, true, 6, 'Filipino', 'Ang pisikal na anyo ng lupa gaya ng bundok at ilog', 'tanawin', 'tanawinn', 'tanaawin', 'tanawiin'),
  (1, true, 6, 'Filipino', 'Ang pagbili at pagbenta ng kalakal sa pagitan ng mga bansa', 'kalakalan', 'kalakalann', 'kalakallan', 'kalakaalan'),
  (1, true, 6, 'Filipino', 'Ang grupo ng mga bansang nagkakaisa para sa iisang layunin', 'alyansa', 'alyanssa', 'aliyansa', 'allyansa'),
  (1, true, 6, 'Filipino', 'Ang pag-aaral kung paano ginagamit ng tao ang limitadong yaman', 'ekonomiks', 'ekonomicks', 'ekonomiks''', 'ekonimiks'),
  (1, true, 6, 'Filipino', 'Ang mga kalakal na ipinapadala palabas ng bansa', 'luwas', 'luwass', 'luwaas', 'luwaz'),
  (1, true, 6, 'Filipino', 'Ang mga kalakal na ipinapasok mula sa ibang bansa', 'angkat', 'angkatt', 'angkaat', 'angkatth'),
  (1, true, 6, 'Filipino', 'Ang buwis na ipinapataw sa mga kalakal na ipinapasok o inilalabas', 'taripa', 'taripah', 'tarripa', 'taripaa'),
  (1, true, 6, 'Filipino', 'Ang sistemang pribadong indibidwal ang nagmamay-ari ng negosyo', 'kapitalismo', 'kapitalismoh', 'kapitallismo', 'kapitalizmo'),
  (1, true, 6, 'Filipino', 'Ang sistemang ang pamahalaan ang nagmamay-ari ng ekonomiya', 'sosyalismo', 'sosyalismoh', 'sosyallismo', 'sosyalizmo'),
  (1, true, 6, 'Filipino', 'Ang pangungusap na may isang malayang sugnay', 'payak na pangungusap', 'payak na pangunguzap', 'payaknapangungusap', 'payak na panguusap'),
  (1, true, 6, 'Filipino', 'Ang pangungusap na may dalawang malayang sugnay', 'tambalang pangungusap', 'tambalang pangunguzap', 'tambalangpangungusap', 'tambalang panguusap'),
  (1, true, 6, 'Filipino', 'Ang pangungusap na may malaya at di-malayang sugnay', 'hugnayang pangungusap', 'hugnayang pangunguzap', 'hugnayangpangungusap', 'hugnayang panguusap'),
  (1, true, 6, 'Filipino', 'Ang grupo ng salitang may paksa at panaguri ngunit hindi kumpleto ang diwa', 'di-malayang sugnay', 'dimalayang sugnay', 'di-malayang sugnai', 'di malayang sugnay'),
  (1, true, 6, 'Filipino', 'Ang saloobin ng manunulat sa paksa o mambabasa', 'himig', 'himigg', 'himmig', 'himigh'),
  (1, true, 6, 'Filipino', 'Ang kabuuang damdamin o kapaligiran na nadarama sa isang akda', 'kalagayang-damdamin', 'kalagayang damdamin', 'kalagayangdamdamin', 'kalagayang-damdameen'),
  (1, true, 6, 'Filipino', 'Ang pananaw kung saan isinalaysay ang isang kwento', 'pananaw', 'pananauw', 'pananaww', 'pananaw'''),
  (1, true, 6, 'Filipino', 'Ang paggamit ng pagmamalabis para bigyang-diin ang isang bagay', 'pagmamalabis', 'pagmamalabiss', 'pagmamalabbis', 'pagmamalabis'''),
  (1, true, 6, 'Filipino', 'Ang paghahambing ng dalawang bagay nang hindi gumagamit ng tulad o parang', 'talinghaga', 'talinghagah', 'talinghagga', 'talinghagaa'),
  (1, true, 6, 'Filipino', 'Ang salitang idinaragdag upang linawin o baguhin ang kahulugan ng ibang salita', 'panlapi', 'panlappi', 'panllapi', 'panlaapi'),
  (1, true, 6, 'Filipino', 'Ang uri ng pananalitang naglalarawan ng damdamin sa masining na paraan', 'tulang-tuluyan', 'tulang tuluyan', 'tulangtuluyan', 'tulang-tuluyann'),
  (1, true, 6, 'Filipino', 'Ang pangkat ng mga taong may iisang wika, kaugalian, at pinagmulan', 'angkan', 'angkann', 'angkaan', 'angkaanh'),
  (1, true, 6, 'Filipino', 'Ang paraan ng pagsasalaysay gamit ang unang panauhan', 'unang panauhan', 'unang-panauhan', 'unangpanauhan', 'unang panauhaan'),
  (1, true, 6, 'Filipino', 'Ang paraan ng pagsasalaysay gamit ang pangatlong panauhan', 'pangatlong panauhan', 'pangatlong-panauhan', 'pangatlongpanauhan', 'pangatlong panauhaan'),
  (1, true, 6, 'Filipino', 'Ang kabuuang aral o mensahe ng isang akda', 'paksang-diwa', 'paksang diwa', 'paksangdiwa', 'paksang-diwah'),
  (1, true, 6, 'English', 'A comparison of two quantities by division', 'ratio', 'ratioh', 'ratioo', 'ratioe'),
  (1, true, 6, 'English', 'A ratio comparing a number to 100', 'percent', 'persent', 'percentt', 'persant'),
  (1, true, 6, 'English', 'A number that includes both positive and negative whole numbers', 'integer', 'integar', 'intiger', 'integger'),
  (1, true, 6, 'English', 'A letter used to represent an unknown number in an equation', 'variable', 'variabel', 'variabl', 'varriable'),
  (1, true, 6, 'English', 'A number multiplied by a variable in an algebraic expression', 'coefficient', 'coeficient', 'coefficiant', 'coefficent'),
  (1, true, 6, 'English', 'An algebraic statement showing two expressions are equal', 'equation', 'equaton', 'equashun', 'equasion'),
  (1, true, 6, 'English', 'A comparison of two ratios that are equal', 'proportion', 'proporton', 'proporshun', 'propotion'),
  (1, true, 6, 'English', 'The likelihood that an event will happen', 'probability', 'probabillity', 'probabilty', 'probabillty'),
  (1, true, 6, 'English', 'The middle value in a set of ordered numbers', 'median', 'medean', 'mediann', 'medien'),
  (1, true, 6, 'English', 'The value that appears most often in a data set', 'mode', 'moad', 'modde', 'mod'),
  (1, true, 6, 'English', 'The average of a set of numbers', 'mean', 'meen', 'meann', 'mean'''),
  (1, true, 6, 'English', 'The difference between the highest and lowest values in a data set', 'range', 'ranje', 'rangee', 'rainge'),
  (1, true, 6, 'English', 'A number raised to a power', 'exponent', 'exponant', 'exponentt', 'expoonent'),
  (1, true, 6, 'English', 'The number being multiplied by itself in a power expression', 'base', 'bace', 'basse', 'bas'),
  (1, true, 6, 'English', 'A whole number greater than 1 with exactly two factors', 'prime number', 'prime-number', 'prime numbar', 'primenumber'),
  (1, true, 6, 'English', 'A whole number with more than two factors', 'composite number', 'composite-number', 'composite numbar', 'compositenumber'),
  (1, true, 6, 'English', 'The largest number that divides two or more numbers evenly', 'greatest common factor', 'greatest-common-factor', 'greatest comon factor', 'greatestcommonfactor'),
  (1, true, 6, 'English', 'The smallest number that is a multiple of two or more numbers', 'least common multiple', 'least-common-multiple', 'least comon multiple', 'leastcommonmultiple'),
  (1, true, 6, 'English', 'The period of rapid physical and emotional change between childhood and adulthood', 'puberty', 'puberty''', 'puburty', 'pubertty'),
  (1, true, 6, 'English', 'The physical, mental, and social well-being of a person', 'wellness', 'wellnes', 'welness', 'wellnesss'),
  (1, true, 6, 'English', 'The body''s ability to fight off harmful germs', 'immunity', 'imunity', 'immunety', 'immunitty'),
  (1, true, 6, 'English', 'A harmful substance that causes illness when it enters the body', 'toxin', 'toksin', 'toxinn', 'toxen'),
  (1, true, 6, 'English', 'The regular pattern of sleeping and waking', 'sleep cycle', 'sleep-cycle', 'sleep cyle', 'sleepcycle'),
  (1, true, 6, 'English', 'A balanced intake of nutrients needed by the body', 'balanced diet', 'balanced-diet', 'balansed diet', 'balanceddiet'),
  (1, true, 6, 'English', 'Physical activity that keeps the body fit and strong', 'exercise', 'excercise', 'exersize', 'exercize'),
  (1, true, 6, 'English', 'The state of being free from injury or danger', 'safety', 'safty', 'saftey', 'safetey'),
  (1, true, 6, 'English', 'A written agreement between two or more nations', 'treaty', 'treatty', 'treety', 'treatey'),
  (1, true, 6, 'English', 'The supreme power or authority of a state to govern itself', 'sovereignty', 'sovereignety', 'soverignty', 'sovreignty'),
  (1, true, 6, 'English', 'A person who represents their country in another nation', 'ambassador', 'ambassadour', 'embassador', 'ambasador'),
  (1, true, 6, 'English', 'A formal meeting between leaders to discuss issues', 'summit', 'sumit', 'summitt', 'summet'),
  (1, true, 6, 'English', 'The act of helping others without expecting anything in return', 'volunteerism', 'voluntarism', 'volunteerisim', 'voluntereism'),
  (1, true, 6, 'English', 'Fair and equal treatment of all people', 'justice', 'justise', 'justicce', 'justis'),
  (1, true, 6, 'English', 'The quality of being honest and having strong moral principles', 'integrity', 'integrety', 'integritty', 'intergrity'),
  (1, true, 6, 'English', 'Respect and appreciation for one''s own country', 'patriotism', 'patriotisim', 'patriotisem', 'patriottism'),
  (1, true, 6, 'Filipino', 'Ang paghahambing ng dalawang bagay gamit ang dibisyon', 'ratio', 'ratyo', 'ratioh', 'raatio'),
  (1, true, 6, 'Filipino', 'Ang ratio na inihahambing sa isang daan', 'porsyento', 'porsiyento', 'porsyentoh', 'porsyentto'),
  (1, true, 6, 'Filipino', 'Ang bilang na kabilang ang positibo at negatibong buong bilang', 'integer', 'intiger', 'integerr', 'integger'),
  (1, true, 6, 'Filipino', 'Ang letrang gamit upang katawanin ang di-alam na bilang', 'baryabol', 'baryable', 'baryabull', 'baryabol'''),
  (1, true, 6, 'Filipino', 'Ang pahayag na nagpapakita na magkapantay ang dalawang ekspresyon', 'ekwasyon', 'ekwasyonn', 'ekwassyon', 'ekwasion'),
  (1, true, 6, 'Filipino', 'Ang posibilidad na magaganap ang isang pangyayari', 'posibilidad', 'posibiliidad', 'posibillidad', 'posibiliidad'''),
  (1, true, 6, 'Filipino', 'Ang gitnang halaga sa isang hanay ng mga bilang', 'median', 'medeean', 'mediaan', 'medyan'),
  (1, true, 6, 'Filipino', 'Ang halagang madalas lumitaw sa isang set ng datos', 'moda', 'modah', 'modda', 'modaa'),
  (1, true, 6, 'Filipino', 'Ang katamtamang halaga ng isang set ng bilang', 'katamtamang halaga', 'katamtamang halagah', 'katamtamanghalaga', 'katamtamang halagaa'),
  (1, true, 6, 'Filipino', 'Ang pagkakaiba ng pinakamataas at pinakamababang halaga', 'hanay', 'hanayy', 'hannay', 'hanaay'),
  (1, true, 6, 'Filipino', 'Ang buong bilang na higit sa isa na may eksaktong dalawang salik', 'primong bilang', 'primong bilangg', 'primongbilang', 'primong bilanng'),
  (1, true, 6, 'Filipino', 'Ang buong bilang na may higit sa dalawang salik', 'tambalang bilang', 'tambalang bilangg', 'tambalangbilang', 'tambalang bilanng'),
  (1, true, 6, 'Filipino', 'Ang pinakamalaking bilang na pantay na naghahati sa dalawa o higit pang bilang', 'pinakamalaking panlahat na salik', 'pinakamalaking panlahat na salic', 'pinakamalaking-panlahat na salik', 'pinakamalaking panlahat nasalik'),
  (1, true, 6, 'Filipino', 'Ang yugto ng mabilis na pagbabagong pisikal at emosyonal sa pagitan ng pagkabata at pagtanda', 'pagbibinata', 'pagbibinatah', 'pagbibbinata', 'pagbibinataa'),
  (1, true, 6, 'Filipino', 'Ang kabuuang kalusugang pisikal, mental, at panlipunan ng isang tao', 'kagalingan', 'kagalinggan', 'kagalingann', 'kagaalingan'),
  (1, true, 6, 'Filipino', 'Ang kakayahan ng katawan na labanan ang nakakapinsalang mikrobyo', 'imunidad', 'imunidadd', 'imunniidad', 'imuniidad'),
  (1, true, 6, 'Filipino', 'Ang sangkap na nakakapinsala kapag pumasok sa katawan', 'lason', 'lasonn', 'lasoon', 'lasoan'),
  (1, true, 6, 'Filipino', 'Ang balanseng pagkain na kailangan ng katawan', 'balanseng pagkain', 'balanseng pagkaen', 'balansengpagkain', 'balanseng pagkaan'),
  (1, true, 6, 'Filipino', 'Ang pisikal na gawain na nagpapanatili ng lakas at kalusugan ng katawan', 'ehersisyo', 'ehersisyoh', 'ehersissyo', 'ehersisyoo'),
  (1, true, 6, 'Filipino', 'Ang kalagayan ng kaligtasan mula sa panganib o pinsala', 'kaligtasan', 'kaligtasann', 'kaligtaasan', 'kaligtaasann'),
  (1, true, 6, 'Filipino', 'Ang nakasulat na kasunduan sa pagitan ng dalawa o higit pang bansa', 'kasunduan', 'kasunduann', 'kasunduaan', 'kasunduaann'),
  (1, true, 6, 'Filipino', 'Ang kapangyarihan ng isang bansa na mamahala sa sarili nito', 'soberanya', 'soveranya', 'soberaniya', 'soberanyah'),
  (1, true, 6, 'Filipino', 'Ang taong kumakatawan sa kanilang bansa sa ibang bansa', 'embahador', 'embahadorr', 'embajador', 'embahaadorr'),
  (1, true, 6, 'Filipino', 'Ang pormal na pagtitipon ng mga pinuno upang pag-usapan ang isang isyu', 'kumperensya', 'kumperensiya', 'kumperensyah', 'kumperenssya'),
  (1, true, 6, 'Filipino', 'Ang pagtulong sa iba nang kusa at walang inaasahang kapalit', 'boluntarismo', 'boluntarismoh', 'boluntarizmo', 'bolunttarismo'),
  (1, true, 6, 'Filipino', 'Ang patas at pantay na pagtrato sa lahat ng tao', 'katarungan', 'katarunggan', 'katarungann', 'kataarungan'),
  (1, true, 6, 'Filipino', 'Ang katangian ng pagiging tapat at may matibay na moral na prinsipyo', 'integridad', 'integridadd', 'integriidad', 'integridaad'),
  (1, true, 6, 'Filipino', 'Ang paggalang at pagmamahal sa sariling bansa', 'pagkamakabayan', 'pagkamakabayann', 'pagkamakabaayan', 'pagkamakabayaan'),
  (1, true, 6, 'English', 'A shape with all sides and angles equal', 'regular polygon', 'regular-polygon', 'regullar polygon', 'regular polygonn'),
  (1, true, 6, 'English', 'The point where two rays meet to form an angle', 'vertex', 'vertexx', 'vertx', 'vertexs'),
  (1, true, 6, 'English', 'An angle that measures exactly 90 degrees', 'right angle', 'right-angle', 'rite angle', 'rightangle'),
  (1, true, 6, 'English', 'An angle that measures less than 90 degrees', 'acute angle', 'acute-angle', 'acutte angle', 'acuteangle'),
  (1, true, 6, 'English', 'An angle that measures more than 90 but less than 180 degrees', 'obtuse angle', 'obtuse-angle', 'obtus angle', 'obtuseangle'),
  (1, true, 6, 'English', 'Two angles that add up to 90 degrees', 'complementary angles', 'complementary-angles', 'complimentary angles', 'complementaryangles'),
  (1, true, 6, 'English', 'Two angles that add up to 180 degrees', 'supplementary angles', 'supplementary-angles', 'suplementary angles', 'supplementaryangles'),
  (1, true, 6, 'English', 'Lines that meet at a right angle', 'perpendicular lines', 'perpendicular-lines', 'perpendiculer lines', 'perpendicularlines'),
  (1, true, 6, 'English', 'Lines that never meet and stay the same distance apart', 'parallel lines', 'parallel-lines', 'paralel lines', 'parallellines'),
  (1, true, 6, 'English', 'A figure formed by two rays sharing a common endpoint', 'angle', 'angel', 'anggle', 'anglee'),
  (1, true, 6, 'English', 'The study of celestial bodies and the universe', 'astronomy', 'astronamy', 'astronomey', 'astronmy'),
  (1, true, 6, 'English', 'A huge collection of stars, gas, and dust held together by gravity', 'galaxy', 'galaxie', 'galaxxy', 'galexy'),
  (1, true, 6, 'English', 'The scientific study of weather patterns', 'meteorology', 'meteorologie', 'meteorollogy', 'meteorlogy'),
  (1, true, 6, 'English', 'A device used to measure earthquakes', 'seismograph', 'seizmograph', 'seismogaph', 'seismogrph'),
  (1, true, 6, 'English', 'The movement of tectonic plates beneath the earth''s surface', 'plate tectonics', 'plate-tectonics', 'plate tektonics', 'platetectonics'),
  (1, true, 6, 'English', 'A sudden shaking of the ground caused by movement of rock', 'earthquake', 'earthquak', 'erthquake', 'earthquacke'),
  (1, true, 6, 'English', 'A mountain that can erupt, releasing lava and ash', 'volcano', 'volcanoe', 'volcanno', 'volcanoh'),
  (1, true, 6, 'English', 'The process by which rock is broken down and moved by wind or water', 'erosion', 'erosin', 'errosion', 'erosionn'),
  (1, true, 6, 'English', 'The gradual wearing away of rock and soil', 'weathering', 'wethering', 'weatherring', 'weatheringg'),
  (1, true, 6, 'English', 'A large area of trees and vegetation that produces much of earth''s oxygen', 'rainforest', 'rainforrest', 'rain forest''', 'rainfores'),
  (1, true, 6, 'Filipino', 'Ang hugis na may magkakaparehong sukat ang lahat ng gilid at anggulo', 'reguler na poligono', 'reguler na poligonoh', 'regulernapoligono', 'reguler na poligonno'),
  (1, true, 6, 'Filipino', 'Ang punto kung saan nagtatagpo ang dalawang tuwid na linya upang bumuo ng anggulo', 'tuktok', 'tuktokk', 'tuktuk', 'tuktook'),
  (1, true, 6, 'Filipino', 'Ang anggulong sumusukat ng eksaktong siyamnapung digri', 'tuwid na anggulo', 'tuwid na angguloh', 'tuwidnaangguloh', 'tuwid na angguloo'),
  (1, true, 6, 'Filipino', 'Ang anggulong mas mababa sa siyamnapung digri', 'matalim na anggulo', 'matalim na angguloh', 'matalimnaangguloh', 'matalim na angguloo'),
  (1, true, 6, 'Filipino', 'Ang anggulong higit sa siyamnapu ngunit mas mababa sa isandaan walumpung digri', 'malapad na anggulo', 'malapad na angguloh', 'malapadnaangguloh', 'malapad na angguloo'),
  (1, true, 6, 'Filipino', 'Ang mga linyang hindi kailanman nagtatagpo at pantay ang distansya', 'kahanay na linya', 'kahanay na linyah', 'kahanaynalinyah', 'kahanay na linyaa'),
  (1, true, 6, 'Filipino', 'Ang mga linyang nagtatagpo sa isang tuwid na anggulo', 'patayong linya', 'patayong linyah', 'patayongnalinyah', 'patayong linyaa'),
  (1, true, 6, 'Filipino', 'Ang pag-aaral ng mga bagay sa kalawakan at himpapawid', 'astronomiya', 'astronomiyah', 'astronommiya', 'astronomia'),
  (1, true, 6, 'Filipino', 'Ang malaking pangkat ng mga bituin, gas, at alabok na hawak ng grabidad', 'galaksiya', 'galaksiyah', 'galaksya', 'galaksiyaa'),
  (1, true, 6, 'Filipino', 'Ang pang-agham na pag-aaral ng pattern ng panahon', 'meteorolohiya', 'meteorolohiyah', 'meteorollohiya', 'meteorolohia'),
  (1, true, 6, 'Filipino', 'Ang kagamitang ginagamit upang sukatin ang lakas ng lindol', 'seismograp', 'seismograpp', 'seysmograp', 'seismograph'''),
  (1, true, 6, 'Filipino', 'Ang biglaang pagyanig ng lupa dulot ng galaw ng bato sa ilalim', 'lindol', 'lindoll', 'lindul', 'lindoll'''),
  (1, true, 6, 'Filipino', 'Ang bundok na maaaring pumutok at maglabas ng lava at abo', 'bulkan', 'bulkann', 'bulcan', 'bulkaan'),
  (1, true, 6, 'Filipino', 'Ang proseso ng pagguho at paglipat ng lupa dulot ng hangin o tubig', 'pagguho', 'pagguhoh', 'paggguho', 'pagguhoo'),
  (1, true, 6, 'Filipino', 'Ang unti-unting pagkasira ng bato at lupa', 'pagkasira ng bato', 'pagkasira ng batoh', 'pagkasiranngbato', 'pagkasira ng batoo'),
  (1, true, 6, 'Filipino', 'Ang malawak na kagubatang gumagawa ng malaking bahagi ng oxygen ng mundo', 'gubat na tropikal', 'gubat na tropikall', 'gubatnatropikal', 'gubat na tropikaal'),
  (1, true, 6, 'Filipino', 'Ang panuntunang sinusunod ng lipunan tungkol sa tama at mali', 'moralidad', 'moralidadd', 'morallidad', 'moraliidad'),
  (1, true, 6, 'Filipino', 'Ang kakayahang unawain at damhin ang saloobin ng iba', 'empatiya', 'empatiyah', 'empattiya', 'empatia'),
  (1, true, 6, 'Filipino', 'Ang pagsisikap na patuloy sa kabila ng hirap o pagsubok', 'pagtitiyaga', 'pagtitiyagah', 'pagtittiyaga', 'pagtitiyagaa'),
  (1, true, 6, 'Filipino', 'Ang paninindigan sa tama kahit walang kasamang tao', 'katatagan', 'katatagann', 'katataagan', 'katataaganh'),
  (1, true, 6, 'Filipino', 'Ang pagiging bukas-palad at handang magbigay ng tulong', 'pagkabukas-palad', 'pagkabukas palad', 'pagkabukaspalad', 'pagkabukas-palaad'),
  (1, true, 6, 'Filipino', 'Ang paggamit ng oras nang wasto at may disiplina', 'disiplina sa oras', 'disiplina sa oraz', 'disiplinasaoras', 'disiplina sa oraas');