insert into public.budget_of_work (grade, subject, content_markdown, source_file)
values (
  3,
  'Science',
  $bow$# Grade 3 Science — Budget of Work

## Term 1
Wk1: Science in our daily life — identifying objects, activities, or natural events in the local environment that can be explained by science | Wk2: Science processes — participating in guided science activities by asking questions and tinkering with materials; describing the uses of science equipment and materials (ruler, hand lens, scissors, balloons, modeling clay, cardboard) | Wk3: Describing science process skills used in simple activities — observing, predicting, and measuring using units such as millimeter, centimeter, and meter | Wk4-5: Describing the physical properties of solid materials (hard, shiny, or stretchable) | Wk6: Explaining that changes in materials can be harmful to living and non-living things in the environment (e.g. trash disposal, burning household materials) | Wk7: Demonstrating proper handling and disposal of materials according to their properties (reusing objects, disposing of excess oil into garbage, recycling paper, plastic, or glass) | Wk8: Describing how changes in solid materials make them useful — shaped, pressed, hammered, joined, or cut | Wk9-10: Identifying the properties and uses of metals used by the local community (iron, gold, silver, copper); term integration — designing a useful product out of recyclable materials

**Special Science enrichment:** Have the learner design their own small test of a solid material's physical properties — pick 2-3 household objects, sort them by a property they choose (hard/soft, shiny/dull, stretchable/not), and explain in their own words which single property decided each answer.

## Term 2
Wk1: Using the skills of observing, predicting, and measuring in performing simple guided science activities | Wk2: Observing and describing the difference between living and non-living things, giving examples of each found in the local environment | Wk3: Describing the characteristics of living things — they grow, respond, and reproduce | Wk4: Observing and describing the outer body parts of animals (head, legs, wings) and identifying their role in moving and gathering food | Wk5: Observing the outer parts of plants (leaves, roots, stems) and identifying their role in getting water and nutrients from the soil | Wk6: Identifying the basic needs of all living things (air, food, water, shelter); explaining how living things depend on one another and the environment to meet these needs; recognizing the need to protect and conserve the environment | Wk7: Exploring and demonstrating different ways to make objects move by natural causes (wind, water) or by people (pushing, pulling, rolling, carrying); exploring what affects the movement of objects (size, shape, heaviness, material, surface texture) | Wk8: Measuring and describing changes in the position of people or objects relative to their original position (closer, farther, left, right) | Wk9: Exploring and describing how sound is made and transferred in everyday situations; describing sources of light and their use in everyday situations | Wk10: Explaining how light and sound can be harmful and suggesting ways to protect oneself; exploring ways to use movement, sound, and light to send information between two people

**Special Science enrichment:** For the Wk7 movement unit, have the learner change only one factor at a time (e.g. surface texture, keeping the push the same) across three or more trial objects, and describe in writing which factor made the biggest difference and why, rather than only naming factors that affect movement in general.

## Term 3
Wk1-2: Participating in guided activities to locate and describe different types of non-living things found in and around the school (rocks, soil, water, air, metals, clouds, rain, sunlight) | Wk3: Identifying useful things people have made from non-living materials and the natural materials used to make them; recognizing that non-living materials making up the environment are called "earth materials" | Wk4-5: Observing and recording changes in the weather during a day or over several days; describing the different types and patterns of weather that occur in the local area | Wk6: Describing how changes in the weather can affect daily activities and explaining how some types of weather can be dangerous for people | Wk7-8: Participating in guided activities to carefully observe and describe the natural objects commonly seen in the sky during daytime and nighttime, including the Sun, the Moon, planets, and stars | Wk9: Exploring and recording how and when the Sun, the Moon, planets, and stars can be seen moving across the sky | Wk10: Explaining how natural objects in the sky affect the activities of people; describing safety measures to avoid the harmful effects of the Sun's light

**Special Science enrichment:** During Wk4-5, have the learner keep a real multi-day weather log with dates, using their own simple notation for sunny/rainy/cloudy/windy conditions, and then identify which day showed the sharpest change and propose one possible reason for it, rather than only reading about weather types from a table.$bow$,
  'https://eduksama.com/wp-content/uploads/2024/10/FINAL-MATATAG-Science-CG-2023-Grades-3-10.pdf'
);
