-- Grade 4 Lorekeeper content batch 1 of 2 — 134 questions, working toward
-- the 300-question-per-grade-per-guild target. Covers Science, AP, English,
-- and Filipino per docs/guild-question-prompts/lorekeeper-grade-4.md.
insert into public.sq_lorekeeper (term_id, is_active, grade_level, passage, question, choice_a, choice_b, choice_c, choice_d, correct_choice) values
  (1, true, 4, 'Physical changes alter the form of a material but do not create a new substance. Cutting paper, melting ice, and dissolving sugar in water are examples of physical changes. Chemical changes, on the other hand, create a brand-new substance with different properties.', 'Which of the following is a physical change?', 'Burning wood', 'Rusting iron', 'Melting butter', 'Cooking an egg', 'c'),
  (1, true, 4, 'Physical changes alter the form of a material but do not create a new substance. Cutting paper, melting ice, and dissolving sugar in water are examples of physical changes. Chemical changes, on the other hand, create a brand-new substance with different properties.', 'Which of the following is a chemical change?', 'Tearing paper', 'Rusting iron', 'Freezing water', 'Folding cloth', 'b'),
  (1, true, 4, NULL, 'Which property of matter refers to how much space an object takes up?', 'Mass', 'Volume', 'Texture', 'Color', 'b'),
  (1, true, 4, NULL, 'Which property of matter refers to the amount of matter in an object?', 'Mass', 'Volume', 'Shape', 'Texture', 'a'),
  (1, true, 4, NULL, 'A mixture of sand and pebbles, where you can still see the individual parts, is an example of a', 'Solution', 'Heterogeneous mixture', 'Chemical compound', 'Pure element', 'b'),
  (1, true, 4, NULL, 'A mixture like salt water, where the parts are evenly spread out and you cannot see them separately, is called a', 'Heterogeneous mixture', 'Solution', 'Physical barrier', 'Chemical reaction', 'b'),
  (1, true, 4, NULL, 'Which separation method would work best to separate sand from water?', 'Filtering', 'Magnetism', 'Melting', 'Burning', 'a'),
  (1, true, 4, NULL, 'Which separation method would work best to get salt back from salt water?', 'Filtering', 'Evaporation', 'Freezing only', 'Magnetism', 'b'),
  (1, true, 4, NULL, 'Slowly pouring off the clear liquid from the top of a settled mixture, leaving the solid behind, is called', 'Decanting', 'Evaporating', 'Melting', 'Condensing', 'a'),
  (1, true, 4, NULL, 'Which of these is a common misconception about chemical changes?', 'Thinking a chemical change always creates a new substance', 'Thinking that boiling water to make steam is a chemical change, when it is actually a physical change', 'Thinking iron can rust', 'Thinking burning wood produces ash', 'b'),
  (1, true, 4, NULL, 'Which property of matter can you observe just by looking, without touching an object?', 'Texture', 'Color', 'Mass', 'Temperature', 'b'),
  (1, true, 4, NULL, 'A force that you apply by directly touching an object, like pushing a cart, is called a', 'Non-contact force', 'Contact force', 'Magnetic force only', 'Gravitational pull', 'b'),
  (1, true, 4, NULL, 'Gravity is an example of what type of force?', 'Contact force', 'Non-contact force', 'Frictional force only', 'Push force', 'b'),
  (1, true, 4, NULL, 'The force that slows down or opposes motion between two surfaces rubbing together is called', 'Gravity', 'Magnetism', 'Friction', 'Tension', 'c'),
  (1, true, 4, NULL, 'Which of these best describes what a force can do to an object?', 'Only make it move faster', 'Move it, stop it, change its direction, or change its shape', 'Only change its color', 'Only make it disappear', 'b'),
  (1, true, 4, NULL, 'Magnetism is an example of what type of force?', 'Contact force', 'Non-contact force', 'Frictional force', 'Push force only', 'b'),
  (1, true, 4, NULL, 'If a car travels 100 kilometers in 2 hours, what is its speed?', '200 km/h', '50 km/h', '100 km/h', '2 km/h', 'b'),
  (1, true, 4, NULL, 'Speed is calculated by dividing', 'Time by distance', 'Distance by time', 'Mass by volume', 'Force by mass', 'b'),
  (1, true, 4, NULL, 'Which surface would create MORE friction when an object slides across it?', 'A smooth, polished tile floor', 'A rough, sandy pavement', 'A sheet of ice', 'A slippery wet floor', 'b'),
  (1, true, 4, NULL, 'A magnet can attract objects made of which material?', 'Iron', 'Plastic', 'Wood', 'Glass', 'a'),
  (1, true, 4, NULL, 'Which of these is a form of energy?', 'Heat', 'Weight', 'Distance', 'Volume', 'a'),
  (1, true, 4, NULL, 'The energy stored in food or fuel that is released through chemical reactions is called', 'Mechanical energy', 'Chemical energy', 'Light energy', 'Sound energy', 'b'),
  (1, true, 4, NULL, 'Heat transfer through direct contact between two objects, like touching a hot pan, is called', 'Convection', 'Radiation', 'Conduction', 'Reflection', 'c'),
  (1, true, 4, NULL, 'Heat transfer through the movement of a liquid or gas, like boiling water circulating in a pot, is called', 'Conduction', 'Convection', 'Radiation', 'Refraction', 'b'),
  (1, true, 4, NULL, 'Heat transfer through waves, without needing to touch anything, like heat from the sun, is called', 'Conduction', 'Convection', 'Radiation', 'Absorption', 'c'),
  (1, true, 4, NULL, 'A material that allows heat or electricity to pass through it easily, like metal, is called a', 'Conductor', 'Insulator', 'Reflector', 'Producer', 'a'),
  (1, true, 4, NULL, 'A material that does NOT allow heat or electricity to pass through easily, like rubber, is called an', 'Conductor', 'Insulator', 'Absorber', 'Amplifier', 'b'),
  (1, true, 4, NULL, 'Which of these is an example of mechanical energy?', 'A moving bicycle', 'A ray of sunlight', 'The smell of flowers', 'A cold breeze', 'a'),
  (1, true, 4, NULL, 'Electrical energy is best described as energy from', 'The movement of electric charges', 'Sound waves only', 'The sun''s light only', 'Solid objects at rest', 'a'),
  (1, true, 4, NULL, 'When light bounces off a shiny surface like a mirror, this is called', 'Refraction', 'Reflection', 'Absorption', 'Conduction', 'b'),
  (1, true, 4, NULL, 'When light bends as it passes from air into water, this is called', 'Reflection', 'Refraction', 'Convection', 'Radiation', 'b'),
  (1, true, 4, NULL, 'When a dark object takes in light instead of bouncing it back, this is called', 'Reflection', 'Refraction', 'Absorption', 'Conduction', 'c'),
  (1, true, 4, NULL, 'How high or low a sound is called its', 'Volume', 'Pitch', 'Echo', 'Wavelength only', 'b'),
  (1, true, 4, NULL, 'How loud or soft a sound is called its', 'Pitch', 'Volume', 'Frequency only', 'Reflection', 'b'),
  (1, true, 4, NULL, 'A sound that bounces off a surface and repeats is called an', 'Echo', 'Refraction', 'Vibration only', 'Absorption', 'a'),
  (1, true, 4, NULL, 'We are able to see objects because light', 'Is absorbed by our ears', 'Bounces off objects and enters our eyes', 'Is created inside our eyes', 'Never touches objects', 'b'),
  (1, true, 4, NULL, 'We are able to hear sounds because our ears detect', 'Light waves', 'Vibrations traveling through the air', 'Magnetic fields', 'Heat waves', 'b'),
  (1, true, 4, 'In a food web, many food chains connect together. Grass is eaten by grasshoppers. Grasshoppers are eaten by frogs. Frogs are eaten by snakes, and snakes are eaten by hawks.', 'In this food web, what eats the grasshoppers?', 'Grass', 'Frogs', 'Hawks', 'Snakes only', 'b'),
  (1, true, 4, 'In a food web, many food chains connect together. Grass is eaten by grasshoppers. Grasshoppers are eaten by frogs. Frogs are eaten by snakes, and snakes are eaten by hawks.', 'In this food web, which organism is the producer?', 'Grass', 'Grasshopper', 'Frog', 'Hawk', 'a'),
  (1, true, 4, NULL, 'An animal that eats other animals as its primary food source, like a hawk eating a snake, is called a', 'Primary consumer', 'Secondary consumer', 'Producer', 'Decomposer only', 'b'),
  (1, true, 4, NULL, 'An organism that breaks down dead plants and animals, returning nutrients to the soil, is called a', 'Producer', 'Primary consumer', 'Decomposer', 'Predator only', 'c'),
  (1, true, 4, NULL, 'A special feature that helps an animal survive in its environment, like a polar bear''s thick fur, is called an', 'Adaptation', 'Ecosystem', 'Food web', 'Habitat only', 'a'),
  (1, true, 4, NULL, 'A desert animal with large ears that release body heat, like a fennec fox, shows an adaptation for', 'Staying cool in hot climates', 'Swimming faster', 'Flying long distances', 'Living underwater', 'a'),
  (1, true, 4, NULL, 'The place where an organism naturally lives, providing food, water, and shelter, is called its', 'Adaptation', 'Habitat', 'Food chain', 'Decomposer', 'b'),
  (1, true, 4, NULL, 'A rabbit that eats only plants is what kind of consumer in a food chain?', 'Primary consumer', 'Secondary consumer', 'Decomposer', 'Producer', 'a'),
  (1, true, 4, 'Archaeologists discovered ancient human fossils in the Tabon Caves in Palawan. These fossils, called Tabon Man, are among the oldest human remains found in the Philippines, showing that people lived here tens of thousands of years ago.', 'Where were the fossils known as Tabon Man discovered?', 'Cebu', 'Palawan', 'Davao', 'Baguio', 'b'),
  (1, true, 4, 'Archaeologists discovered ancient human fossils in the Tabon Caves in Palawan. These fossils, called Tabon Man, are among the oldest human remains found in the Philippines, showing that people lived here tens of thousands of years ago.', 'What do the Tabon Man fossils show about the Philippines?', 'That people have lived there for tens of thousands of years', 'That no one ever lived there before Spanish colonization', 'That the islands were formed recently', 'That dinosaurs once lived there', 'a'),
  (1, true, 4, NULL, 'Early Malay settlers who came to the Philippines are believed to have arrived mainly by', 'Airplane', 'Boat, across the sea', 'Train', 'Walking across a land bridge only', 'b'),
  (1, true, 4, NULL, 'The Laguna Copperplate Inscription is important in Philippine history because it', 'Is one of the earliest known written records found in the Philippines', 'Was the first Philippine flag', 'Was a type of boat', 'Was written during Spanish colonization', 'a'),
  (1, true, 4, NULL, 'The ancient trading kingdoms of Srivijaya and Majapahit influenced early Philippine communities mainly through', 'Warfare only', 'Trade and cultural exchange', 'Building modern cities', 'Introducing electricity', 'b'),
  (1, true, 4, NULL, 'Which of these best describes a pre-colonial trading kingdom''s relationship with early Philippine settlements?', 'They had no contact at all', 'They exchanged goods and ideas through maritime trade routes', 'They were always at war', 'They only exchanged letters by mail', 'b'),
  (1, true, 4, NULL, 'The three major island groups of the Philippines, from north to south, are', 'Luzon, Visayas, Mindanao', 'Mindanao, Visayas, Luzon', 'Visayas, Luzon, Mindanao', 'Luzon, Mindanao, Visayas', 'a'),
  (1, true, 4, NULL, 'Which of these is a major body of water surrounding the Philippines?', 'The South China Sea', 'The Mediterranean Sea', 'The Baltic Sea', 'The Caribbean Sea', 'a'),
  (1, true, 4, NULL, 'The Sierra Madre is an example of a Philippine', 'Ocean', 'Mountain range', 'Desert', 'Island group', 'b'),
  (1, true, 4, NULL, 'Which of these is an active volcano found in the Philippines?', 'Mount Mayon', 'Mount Fuji', 'Mount Everest', 'Mount Kilimanjaro', 'a'),
  (1, true, 4, NULL, 'Mindanao is located in which part of the Philippines?', 'The northernmost part', 'The southern part', 'The central part only', 'Outside the Philippines', 'b'),
  (1, true, 4, NULL, 'ASEAN stands for', 'Association of Southeast Asian Nations', 'Alliance of South American Nations', 'Association of European Nations', 'Alliance of Southeast African Nations', 'a'),
  (1, true, 4, NULL, 'Which of these countries is a member of ASEAN?', 'Japan', 'Thailand', 'China', 'India', 'b'),
  (1, true, 4, NULL, 'Which of these Southeast Asian countries belongs to ASEAN?', 'Vietnam', 'Australia', 'South Korea', 'Russia', 'a'),
  (1, true, 4, NULL, 'The capital of Malaysia, a fellow ASEAN member of the Philippines, is', 'Bangkok', 'Kuala Lumpur', 'Jakarta', 'Hanoi', 'b'),
  (1, true, 4, NULL, 'The capital of Indonesia, a fellow ASEAN member of the Philippines, is', 'Jakarta', 'Manila', 'Singapore City', 'Bangkok', 'a'),
  (1, true, 4, NULL, 'One main purpose of ASEAN is to', 'Promote peace, cooperation, and economic growth among member countries', 'Create conflict between Southeast Asian nations', 'Merge all member countries into one nation', 'Stop all trade between countries', 'a'),
  (1, true, 4, NULL, 'Which of these is a goal shared by ASEAN member countries?', 'Working together on trade, security, and cultural exchange', 'Isolating themselves from other countries', 'Competing to eliminate each other''s economies', 'Ignoring regional problems', 'a'),
  (1, true, 4, NULL, 'Which of these is an example of a Philippine mineral resource?', 'Copper', 'Rice', 'Mango', 'Coconut', 'a'),
  (1, true, 4, NULL, 'Which of these is an example of a Philippine forest resource?', 'Timber (wood)', 'Copper', 'Fish', 'Gold', 'a'),
  (1, true, 4, NULL, 'Which of these is an example of a Philippine marine resource?', 'Rice', 'Fish and seafood', 'Iron ore', 'Timber', 'b'),
  (1, true, 4, NULL, 'Which of these is an example of an agricultural resource in the Philippines?', 'Rice', 'Copper ore', 'Marble', 'Coal', 'a'),
  (1, true, 4, NULL, 'Using natural resources in a way that does not use them all up, so future generations can also use them, is called', 'Overconsumption', 'Sustainable use', 'Deforestation', 'Pollution', 'b'),
  (1, true, 4, NULL, 'Cutting down too many trees without replanting is an example of', 'Sustainable use', 'Unsustainable use of forest resources', 'Conservation', 'Recycling', 'b'),
  (1, true, 4, NULL, 'Growing crops like rice and corn for food is an example of what economic activity?', 'Manufacturing', 'Farming', 'Mining', 'Banking', 'b'),
  (1, true, 4, NULL, 'Catching fish from rivers, lakes, or the ocean for food or income is an example of what economic activity?', 'Fishing', 'Farming', 'Manufacturing', 'Mining', 'a'),
  (1, true, 4, NULL, 'Turning raw materials into finished products, like turning coconut into oil, is an example of what economic activity?', 'Farming', 'Fishing', 'Manufacturing', 'Trading only', 'c'),
  (1, true, 4, NULL, 'Buying and selling goods between different places or countries is called', 'Trade and commerce', 'Manufacturing only', 'Sustainable use', 'Adaptation', 'a'),
  (1, true, 4, NULL, 'Which of these economic activities relies most directly on the country''s rich marine resources?', 'Fishing', 'Mining', 'Banking', 'Manufacturing electronics', 'a'),
  (1, true, 4, NULL, 'A story that tells about events happening to characters, often in order, is what text type?', 'Narrative', 'Expository', 'Persuasive', 'Descriptive only', 'a'),
  (1, true, 4, NULL, 'A paragraph that explains facts and information about a topic, like how volcanoes form, is what text type?', 'Narrative', 'Descriptive', 'Expository', 'Persuasive', 'c'),
  (1, true, 4, NULL, 'A paragraph that uses vivid details to help the reader imagine a scene is what text type?', 'Descriptive', 'Expository', 'Persuasive', 'Narrative only', 'a'),
  (1, true, 4, NULL, 'A letter trying to convince the reader to recycle more is what text type?', 'Narrative', 'Descriptive', 'Persuasive', 'Expository only', 'c'),
  (1, true, 4, 'Miguel noticed his younger sister crying near the broken vase. He saw the family cat sitting nearby, looking guilty. Even though Miguel had not seen what happened, he had a good idea of what occurred.', 'What conclusion can you draw about what likely happened to the vase?', 'Miguel broke the vase himself', 'The cat likely knocked over and broke the vase', 'The vase broke on its own', 'The sister broke the vase on purpose', 'b'),
  (1, true, 4, NULL, 'Making a logical guess based on clues in the text and your own knowledge is called', 'Summarizing', 'Making an inference', 'Skimming', 'Predicting the ending only', 'b'),
  (1, true, 4, NULL, 'An author who writes a story mainly to make readers laugh has what purpose?', 'To entertain', 'To inform', 'To persuade', 'To confuse', 'a'),
  (1, true, 4, NULL, 'Which of these is a FACT, not an opinion?', 'The Philippines has over 7,000 islands.', 'Basketball is the most exciting sport.', 'Adobo is the tastiest Filipino dish.', 'Summer vacation is too short.', 'a'),
  (1, true, 4, NULL, 'Which of these is an OPINION, not a fact?', 'Water boils at 100 degrees Celsius at sea level.', 'Mangoes are the best-tasting fruit.', 'The Philippines is located in Southeast Asia.', 'A triangle has three sides.', 'b'),
  (1, true, 4, NULL, 'In the sentence "The stars winked at us from the night sky," which figure of speech is used?', 'Simile', 'Personification', 'Hyperbole', 'Onomatopoeia', 'b'),
  (1, true, 4, NULL, 'In the sentence "Her smile was as bright as the sun," which figure of speech is used?', 'Metaphor', 'Simile', 'Personification', 'Hyperbole', 'b'),
  (1, true, 4, NULL, 'In the sentence "The classroom was a zoo during recess," which figure of speech is used?', 'Simile', 'Metaphor', 'Onomatopoeia', 'Hyperbole', 'b'),
  (1, true, 4, NULL, 'In the sentence "I''ve told you a million times to clean your room," which figure of speech is used?', 'Hyperbole', 'Simile', 'Personification', 'Onomatopoeia', 'a'),
  (1, true, 4, NULL, 'In the sentence "The bacon sizzled and popped in the pan," which figure of speech is used?', 'Simile', 'Metaphor', 'Onomatopoeia', 'Personification', 'c'),
  (1, true, 4, NULL, 'What literary device compares two unlike things using the words ''like'' or ''as''?', 'Metaphor', 'Simile', 'Personification', 'Hyperbole', 'b'),
  (1, true, 4, NULL, 'What literary device gives human qualities to something that is not human?', 'Simile', 'Hyperbole', 'Personification', 'Onomatopoeia', 'c'),
  (1, true, 4, NULL, 'What literary device uses extreme exaggeration for effect?', 'Hyperbole', 'Simile', 'Onomatopoeia', 'Metaphor', 'a'),
  (1, true, 4, NULL, 'What literary device uses words that imitate sounds, like "buzz" or "crash"?', 'Onomatopoeia', 'Simile', 'Metaphor', 'Hyperbole', 'a'),
  (1, true, 4, NULL, 'In the sentence "Life is a journey," which figure of speech is used?', 'Simile', 'Metaphor', 'Hyperbole', 'Onomatopoeia', 'b'),
  (1, true, 4, NULL, 'Which sentence is a complex sentence with a main clause and a subordinate clause?', 'The dog barked.', 'Because it was raining, we stayed inside.', 'The dog barked and ran.', 'We stayed inside.', 'b'),
  (1, true, 4, NULL, 'Which sentence correctly uses a relative pronoun?', 'The book which I read was interesting.', 'The book what I read was interesting.', 'The book whose I read was interesting.', 'The book them I read was interesting.', 'a'),
  (1, true, 4, NULL, 'Which word is a relative pronoun that refers to a person?', 'which', 'who', 'that only', 'what', 'b'),
  (1, true, 4, NULL, 'Which sentence correctly uses the present perfect tense?', 'She has finished her homework.', 'She finish her homework.', 'She finishing her homework.', 'She will finished her homework.', 'a'),
  (1, true, 4, NULL, 'Which sentence is written in the active voice?', 'The ball was thrown by Juan.', 'Juan threw the ball.', 'The ball was caught.', 'It was thrown.', 'b'),
  (1, true, 4, NULL, 'Which sentence is written in the passive voice?', 'Juan threw the ball.', 'The ball was thrown by Juan.', 'Juan is throwing the ball.', 'Juan will throw the ball.', 'b'),
  (1, true, 4, NULL, 'The root word in "unbelievable" is', 'un', 'believe', 'able', 'unbeliev', 'b'),
  (1, true, 4, NULL, 'The suffix "-tion" in the word "celebration" changes the verb "celebrate" into what part of speech?', 'A noun', 'A verb', 'An adjective', 'An adverb', 'a'),
  (1, true, 4, NULL, 'The suffix "-ment" in the word "enjoyment" changes the verb "enjoy" into what part of speech?', 'An adjective', 'A noun', 'A verb', 'An adverb', 'b'),
  (1, true, 4, NULL, 'Which word means the same thing as "stubborn" but with a more negative connotation?', 'Determined', 'Persistent', 'Pig-headed', 'Focused', 'c'),
  (1, true, 4, NULL, 'Which of these words has a more positive connotation for someone who doesn''t spend much money?', 'Cheap', 'Stingy', 'Thrifty', 'Greedy', 'c'),
  (1, true, 4, NULL, 'Which word is a synonym for "enormous"?', 'Tiny', 'Massive', 'Narrow', 'Delicate', 'b'),
  (1, true, 4, NULL, 'Which word is an antonym for "generous"?', 'Kind', 'Selfish', 'Giving', 'Charitable', 'b'),
  (1, true, 4, NULL, 'Ang tekstong naglalarawan gamit ang matingkad na detalye upang makita ng mambabasa ang isang tagpo ay tinatawag na', 'Paglalarawang-salita', 'Nagbibigay-impormasyon', 'Salaysay', 'Persuasibo', 'a'),
  (1, true, 4, NULL, 'Ang tekstong nagbibigay ng kaalaman o katotohanan tungkol sa isang paksa ay tinatawag na', 'Salaysay', 'Nagbibigay-impormasyon', 'Persuasibo', 'Paglalarawang-salita only', 'b'),
  (1, true, 4, NULL, 'Ang tekstong nagkukwento ng mga pangyayari, karaniwang may simula, gitna, at wakas, ay tinatawag na', 'Salaysay', 'Nagbibigay-impormasyon', 'Persuasibo', 'Paglalarawang-salita', 'a'),
  (1, true, 4, NULL, 'Ang tekstong sinusubukang kumbinsihin ang mambabasa na maniwala o gumawa ng isang bagay ay tinatawag na', 'Salaysay', 'Paglalarawang-salita', 'Persuasibo', 'Nagbibigay-impormasyon only', 'c'),
  (1, true, 4, NULL, 'Sa pangungusap na "Ang mga bituin ay ngumingiti sa akin," anong tayutay ang ginamit?', 'Simili', 'Personipikasyon', 'Pagmamalabis', 'Onomatopeya', 'b'),
  (1, true, 4, NULL, 'Sa pangungusap na "Kasing puti ng niyebe ang kanyang balat," anong tayutay ang ginamit?', 'Simili', 'Metapora', 'Personipikasyon', 'Onomatopeya', 'a'),
  (1, true, 4, NULL, 'Sa pangungusap na "Ang buhay ay isang laro," anong tayutay ang ginamit?', 'Simili', 'Metapora', 'Onomatopeya', 'Pagmamalabis', 'b'),
  (1, true, 4, NULL, 'Sa pangungusap na "Sinabi ko na sa iyo ng sanlibong beses," anong tayutay ang ginamit?', 'Pagmamalabis', 'Simili', 'Personipikasyon', 'Onomatopeya', 'a'),
  (1, true, 4, NULL, 'Ang salitang "kaluskos" na tumutukoy sa tunog ng dahon ay halimbawa ng anong tayutay?', 'Simili', 'Metapora', 'Onomatopeya', 'Personipikasyon', 'c'),
  (1, true, 4, NULL, 'Ang epiko ay isang uri ng panitikan na kadalasang naglalarawan ng', 'Kabayanihan ng isang bida sa mahabang kwento', 'Balitang pang-araw-araw', 'Talaan ng mga numero', 'Aklat-aralin sa agham', 'a'),
  (1, true, 4, NULL, 'Ang pabula ay kwento tungkol sa mga hayop na may layuning', 'Magbigay ng balita', 'Magturo ng aral sa buhay', 'Magbilang ng numero', 'Magpakita ng talambuhay', 'b'),
  (1, true, 4, NULL, 'Ang alamat ay kwentong bayan na nagpapaliwanag tungkol sa', 'Pinagmulan ng isang bagay o lugar sa kalikasan', 'Kasalukuyang pangyayari sa balita', 'Isang aklat-aralin', 'Isang talaan ng pangalan', 'a'),
  (1, true, 4, NULL, 'Sa isang maikling kwento, ang mahahalagang bahagi ay kinabibilangan ng tauhan, tagpuan, at', 'Banghay', 'Bantas', 'Pahina', 'Titulo lamang', 'a'),
  (1, true, 4, NULL, 'Alin sa mga sumusunod ang pangngalan (noun)?', 'Bahay', 'Tumatakbo', 'Maganda', 'Mabilis', 'a'),
  (1, true, 4, NULL, 'Alin sa mga sumusunod ang pandiwa (verb)?', 'Bahay', 'Kumakain', 'Maganda', 'Siya', 'b'),
  (1, true, 4, NULL, 'Alin sa mga sumusunod ang pang-uri (adjective)?', 'Tumatakbo', 'Maganda', 'Bahay', 'Sila', 'b'),
  (1, true, 4, NULL, 'Alin sa mga sumusunod ang pang-abay (adverb)?', 'Mabilis', 'Bahay', 'Maganda', 'Bata', 'a'),
  (1, true, 4, NULL, 'Sa pangungusap na "Mabilis tumakbo ang bata," alin ang pang-abay?', 'Bata', 'Tumakbo', 'Mabilis', 'Ang', 'c'),
  (1, true, 4, NULL, 'Sa pangungusap na "Ang malaking bahay ay maganda," alin ang pang-uri?', 'Bahay', 'Malaking', 'Ang', 'Ay', 'b'),
  (1, true, 4, NULL, 'Ang unang pangungusap sa isang talata na naglalahad ng pangunahing ideya ay tinatawag na', 'Paksang pangungusap', 'Pangwakas na pangungusap', 'Detalyeng sumusuporta', 'Bantas', 'a'),
  (1, true, 4, NULL, 'Ang mga pangungusap na nagbibigay ng karagdagang impormasyon tungkol sa paksang pangungusap ay tinatawag na', 'Pangwakas na pangungusap', 'Mga detalyeng sumusuporta', 'Paksang pangungusap', 'Bantas', 'b'),
  (1, true, 4, NULL, 'Ang huling pangungusap sa isang talata na bumubuod sa pangunahing ideya ay tinatawag na', 'Paksang pangungusap', 'Detalyeng sumusuporta', 'Pangwakas na pangungusap', 'Panimulang pangungusap only', 'c'),
  (1, true, 4, NULL, 'Kapag sumusulat ng isang talata, dapat bang may kaugnayan ang bawat pangungusap sa paksa?', 'Oo, dapat magkaugnay ang lahat ng pangungusap sa paksang pangungusap', 'Hindi, maaaring iba-iba ang paksa ng bawat pangungusap', 'Hindi mahalaga ang pagkakaugnay', 'Dapat lahat ay tanong', 'a'),
  (1, true, 4, NULL, 'Which of these best shows understanding of why the Philippines has both mineral and marine resources?', 'Because it is made up of many islands surrounded by seas, with mountains and rock formations inland', 'Because it has no coastline at all', 'Because it is located in a desert region', 'Because it has no natural resources', 'a'),
  (1, true, 4, NULL, 'Which of these best explains why ASEAN countries work together on trade agreements?', 'To make trade between member countries easier and boost their economies', 'To stop all trade between member countries', 'To merge into a single country', 'To avoid working with other countries entirely', 'a'),
  (1, true, 4, NULL, 'Which of these best explains the difference between a physical and chemical change?', 'A physical change alters the form of matter without creating a new substance; a chemical change creates a new substance', 'A physical change always creates a new substance', 'There is no real difference between them', 'A chemical change never changes color or smell', 'a'),
  (1, true, 4, NULL, 'Which of these best explains why insulators like rubber are used to cover electrical wires?', 'To prevent electricity from passing through and causing shocks', 'To help electricity flow faster', 'To make the wires heavier', 'To change the wire''s color', 'a'),
  (1, true, 4, NULL, 'Which of these best explains the relationship between producers, consumers, and decomposers in an ecosystem?', 'Producers make food, consumers eat producers or other consumers, and decomposers break down dead matter to recycle nutrients', 'Producers eat consumers', 'Decomposers only eat living plants', 'Consumers make their own food', 'a');