-- Grade 3 Lorekeeper content batch 3 of 3 — 91 questions, completing the
-- 300-question-per-grade-per-guild target for Grade 3 (209 + 91 = 300).
insert into public.sq_lorekeeper (term_id, is_active, grade_level, passage, question, choice_a, choice_b, choice_c, choice_d, correct_choice) values
  (1, true, 3, NULL, 'Leaves lose extra water into the air through tiny openings, in a process called', 'Photosynthesis', 'Transpiration', 'Pollination', 'Germination', 'b'),
  (1, true, 3, NULL, 'Plants are able to make their own food, which is why they are called', 'Consumers', 'Predators', 'Producers', 'Decomposers', 'c'),
  (1, true, 3, NULL, 'The process of a seed beginning to sprout and grow is called', 'Germination', 'Evaporation', 'Condensation', 'Classification', 'a'),
  (1, true, 3, 'In a food chain, energy passes from one living thing to another. Grass uses sunlight to make its own food. A rabbit eats the grass. Then a fox eats the rabbit.', 'In this food chain, what does the fox eat?', 'Grass', 'The rabbit', 'Sunlight', 'Soil', 'b'),
  (1, true, 3, 'In a food chain, energy passes from one living thing to another. Grass uses sunlight to make its own food. A rabbit eats the grass. Then a fox eats the rabbit.', 'In this food chain, which living thing is the producer?', 'The fox', 'The rabbit', 'The grass', 'The sun', 'c'),
  (1, true, 3, NULL, 'An animal that is active mostly at night, like an owl, is called', 'Diurnal', 'Nocturnal', 'Herbivore', 'Vertebrate', 'b'),
  (1, true, 3, NULL, 'A chameleon changing color to blend into its surroundings is an example of', 'Migration', 'Camouflage', 'Hibernation', 'Germination', 'b'),
  (1, true, 3, NULL, 'Some animals, like bears, sleep through the cold winter months in a state called', 'Migration', 'Hibernation', 'Photosynthesis', 'Pollination', 'b'),
  (1, true, 3, NULL, 'Some birds fly to warmer places when it gets cold, in a yearly journey called', 'Hibernation', 'Migration', 'Camouflage', 'Germination', 'b'),
  (1, true, 3, NULL, 'When ice is heated, it turns into liquid water. This change is called', 'Freezing', 'Melting', 'Evaporating', 'Condensing', 'b'),
  (1, true, 3, NULL, 'When liquid water is cooled enough, it turns into solid ice. This change is called', 'Melting', 'Boiling', 'Freezing', 'Evaporating', 'c'),
  (1, true, 3, NULL, 'When water is heated until it turns into steam, this change is called', 'Boiling', 'Freezing', 'Melting', 'Settling', 'a'),
  (1, true, 3, NULL, 'Which word best describes a cloudy day with no rain?', 'Overcast', 'Stormy', 'Freezing', 'Foggy only', 'a'),
  (1, true, 3, NULL, 'A bagyo (typhoon) usually brings which kind of weather?', 'Calm skies and light breeze', 'Strong winds and heavy rain', 'Dry heat with no clouds', 'Snow and ice', 'b'),
  (1, true, 3, NULL, 'A weather forecast is useful because it helps people', 'Prepare for the kind of weather expected that day', 'Change the weather to what they want', 'Avoid going to school forever', 'Grow crops instantly', 'a'),
  (1, true, 3, NULL, 'Rocks are often used by builders mainly because they are', 'Soft and bendable', 'Hard and durable for building', 'Always colorful', 'Able to grow over time', 'b'),
  (1, true, 3, NULL, 'Planting trees on a hillside helps prevent soil from', 'Becoming too fertile', 'Washing away during heavy rain', 'Turning into rock', 'Attracting more sunlight', 'b'),
  (1, true, 3, NULL, 'A fishing rod that helps lift a fish out of the water works mainly like which simple machine?', 'Lever', 'Pulley', 'Screw', 'Wedge', 'a'),
  (1, true, 3, NULL, 'A crowbar used to pry open a heavy lid works mainly like which simple machine?', 'Wheel and axle', 'Lever', 'Pulley', 'Screw', 'b'),
  (1, true, 3, NULL, 'The pedals and wheel of a bicycle work together mainly like which simple machine?', 'Wheel and axle', 'Wedge', 'Inclined plane', 'Pulley', 'a'),
  (1, true, 3, NULL, 'A doorstop that wedges under a door to hold it open works mainly like which simple machine?', 'Pulley', 'Screw', 'Wedge', 'Lever', 'c'),
  (1, true, 3, 'In pre-colonial times, the babaylan was an important person in the barangay. She (or sometimes he) led religious ceremonies, healed the sick using herbal medicine, and gave advice to the datu.', 'What was the main role of a babaylan in a pre-colonial barangay?', 'Leading trade with other countries', 'Leading religious ceremonies and healing the sick', 'Building houses for the community', 'Fishing for the barangay''s food', 'b'),
  (1, true, 3, NULL, 'Before money was commonly used, early Filipinos often traded goods directly for other goods. This is called', 'Barter', 'Taxation', 'Banking', 'Investing', 'a'),
  (1, true, 3, NULL, 'Lapu-Lapu is remembered in Philippine history as the chieftain who', 'Wrote the country''s first novel', 'Led his warriors to resist Ferdinand Magellan''s forces', 'Founded the city of Manila', 'Was the first Philippine president', 'b'),
  (1, true, 3, NULL, 'Melchora Aquino, also known as "Tandang Sora," is remembered in Philippine history for', 'Helping and caring for Filipino revolutionaries', 'Being a pre-colonial datu', 'Writing the Philippine constitution', 'Leading a foreign trade expedition', 'a'),
  (1, true, 3, NULL, 'The Philippine national anthem is called', 'Bayan Ko', 'Lupang Hinirang', 'Anak ng Bayan', 'Sa Kabukiran', 'b'),
  (1, true, 3, NULL, 'Every child has a right to rest and play, in addition to the right to', 'Skip all responsibilities', 'Education and safety', 'Avoid all rules', 'Ignore their family', 'b'),
  (1, true, 3, NULL, 'Throwing trash in proper bins instead of on the street is an example of a citizen''s', 'Want', 'Responsibility to keep the community clean', 'Hobby', 'Punishment', 'b'),
  (1, true, 3, NULL, 'Following traffic rules, like crossing at a pedestrian lane, helps keep', 'Everyone safe from accidents', 'The weather calm', 'Plants growing faster', 'Animals in their habitats', 'a'),
  (1, true, 3, NULL, 'When there is not enough of something for everyone who wants it, this situation is called', 'Abundance', 'Scarcity', 'Bayanihan', 'Kalakalan', 'b'),
  (1, true, 3, NULL, 'The three major island groups of the Philippines are', 'Luzon, Visayas, and Mindanao', 'Manila, Cebu, and Davao', 'North, South, and Central', 'Rizal, Bonifacio, and Aguinaldo', 'a'),
  (1, true, 3, NULL, 'A smaller area within a region, usually governed by a governor, is called a', 'Barangay', 'Province', 'Household', 'Classroom', 'b'),
  (1, true, 3, NULL, 'Which of these is an example of a Filipino community showing bayanihan today?', 'Neighbors ignoring each other during a flood', 'Neighbors working together to help a family after a disaster', 'Only the barangay captain helping', 'Everyone staying inside their own homes', 'b'),
  (1, true, 3, 'Every morning, Mrs. Santos sells vegetables at the market. She wakes up early to pick fresh vegetables from her garden, then travels to the market to sell them to her neighbors.', 'What can you infer about Mrs. Santos based on the passage?', 'She dislikes gardening', 'She works hard to provide fresh vegetables for her community', 'She never leaves her house', 'She only sells vegetables once a year', 'b'),
  (1, true, 3, NULL, 'A story written mainly to entertain the reader has what author''s purpose?', 'To entertain', 'To persuade', 'To inform only', 'To confuse', 'a'),
  (1, true, 3, NULL, 'A textbook chapter written mainly to teach facts has what author''s purpose?', 'To entertain', 'To inform', 'To persuade', 'To confuse the reader', 'b'),
  (1, true, 3, NULL, 'Which of these is a FACT, not an opinion?', 'Mangoes are the best fruit.', 'The Philippines has more than 7,000 islands.', 'Summer is more fun than winter.', 'Blue is the prettiest color.', 'b'),
  (1, true, 3, NULL, 'Which of these is an OPINION, not a fact?', 'Water freezes at 0 degrees Celsius.', 'Dogs make the best pets.', 'The Philippines is in Southeast Asia.', 'A triangle has three sides.', 'b'),
  (1, true, 3, NULL, 'A story that tells about made-up characters and events, often with a beginning, middle, and end, is called', 'Narrative text', 'Persuasive text', 'Procedural text', 'A dictionary entry', 'a'),
  (1, true, 3, NULL, 'What is the correct plural form of "box"?', 'boxs', 'boxes', 'boxies', 'box''s', 'b'),
  (1, true, 3, NULL, 'What is the correct plural form of "child"?', 'childs', 'childes', 'children', 'childrens', 'c'),
  (1, true, 3, NULL, 'Which sentence uses commas correctly to write a date?', 'The event happened on July 4 2020.', 'The event happened on July 4, 2020.', 'The event happened on, July 4 2020.', 'The event, happened on July 4 2020.', 'b'),
  (1, true, 3, NULL, 'Which question word would you use to ask about a location?', 'Who', 'Where', 'Why', 'When', 'b'),
  (1, true, 3, NULL, 'Which question word would you use to ask about a reason?', 'Who', 'What', 'Why', 'Where', 'c'),
  (1, true, 3, NULL, 'In the sentence "She is reading a book," which word is the helping verb?', 'She', 'is', 'reading', 'book', 'b'),
  (1, true, 3, NULL, 'Which sentence shows correct subject-verb agreement?', 'The dogs barks loudly.', 'The dogs bark loudly.', 'The dog bark loudly.', 'The dogs barking loudly.', 'b'),
  (1, true, 3, NULL, 'A word made by joining two smaller words together, like "sunflower," is called a', 'Compound word', 'Prefix', 'Suffix', 'Contraction', 'a'),
  (1, true, 3, NULL, '"Sun" and "flower" combine to form which compound word?', 'Sunset', 'Sunflower', 'Flowerpot', 'Sunshine only', 'b'),
  (1, true, 3, NULL, 'Words that sound the same but have different spellings and meanings, like "to," "too," and "two," are called', 'Synonyms', 'Antonyms', 'Homophones', 'Compound words', 'c'),
  (1, true, 3, NULL, 'Which sentence uses "their," "there," or "they''re" correctly?', 'Their going to the park.', 'They''re going to the park.', 'There going to the park.', 'Theyre going to the park.', 'b'),
  (1, true, 3, NULL, 'Which sentence correctly uses quotation marks to show someone speaking?', 'Maria said, I am hungry.', 'Maria said, "I am hungry."', '"Maria said, I am hungry.', 'Maria said I am, "hungry."', 'b'),
  (1, true, 3, NULL, 'Which word in this sentence should be capitalized: "we visited manila last week"?', 'we', 'visited', 'manila', 'last', 'c'),
  (1, true, 3, NULL, 'Ang tawag sa pangngalang tumutukoy sa tiyak na pangalan ng tao, lugar, o bagay, tulad ng "Rizal" o "Maynila," ay', 'Pangngalang pambalana', 'Pangngalang pantangi', 'Panghalip', 'Pang-uri', 'b'),
  (1, true, 3, NULL, 'Ang tawag sa pangngalang pangkalahatan, tulad ng "bata" o "lungsod," ay', 'Pangngalang pantangi', 'Pangngalang pambalana', 'Pang-abay', 'Pandiwa', 'b'),
  (1, true, 3, NULL, 'Ang salitang nagsasaad ng kilos o galaw, tulad ng "tumatakbo" o "kumakain," ay tinatawag na', 'Pangngalan', 'Pandiwa', 'Pang-uri', 'Pang-abay', 'b'),
  (1, true, 3, NULL, 'Ang salitang naglalarawan kung paano ginawa ang isang kilos, tulad ng "mabilis" sa "tumakbo nang mabilis," ay tinatawag na', 'Pang-abay', 'Pangngalan', 'Panghalip', 'Pandiwa', 'a'),
  (1, true, 3, NULL, 'Ang salitang "mga bata" ay nagpapakita ng anong bilang ng pangngalan?', 'Isahan', 'Maramihan', 'Walang bilang', 'Pantangi', 'b'),
  (1, true, 3, NULL, 'Ang salitang "araw" ay maaaring tumukoy sa "sun" o sa "day." Ito ay halimbawa ng salitang', 'May dalawa o higit pang kahulugan', 'Walang kahulugan', 'Kasingkahulugan lamang', 'Kasalungat lamang', 'a'),
  (1, true, 3, NULL, 'Ang idyomatikong pananalitang "nagpuputok ang tainga" ay ginagamit kapag', 'May bagong bahay', 'Sobrang lakas ng ingay o tunog', 'May bagong damit', 'May bagong laruan', 'b'),
  (1, true, 3, NULL, 'Ang "matapat" ay kasalungat ng', 'Sinungaling', 'Tapat', 'Totoo', 'Wagas', 'a'),
  (1, true, 3, NULL, 'Ang "malapit" ay kasalungat ng', 'Malayo', 'Malaki', 'Mabilis', 'Matalino', 'a'),
  (1, true, 3, NULL, 'Ang pagmamahal at katapatan sa bansang Pilipinas ay tinatawag na', 'Kalakalan', 'Pagkamakabayan', 'Bugtong', 'Salawikain', 'b'),
  (1, true, 3, NULL, 'Ang kasabihang "Ang taong hindi lumingon sa pinanggalingan ay hindi makararating sa paroroonan" ay nagtuturo tungkol sa', 'Kahalagahan ng pagiging masipag', 'Kahalagahan ng pag-alaala sa nakaraan at pagpapahalaga rito', 'Kahalagahan ng pagtulog nang maaga', 'Kahalagahan ng paglalaro', 'b'),
  (1, true, 3, NULL, 'Anong uri ng panitikan ang bugtong na "Dalawang paruparong magkapatid, di magkalapit ang paglipad"?', 'Bugtong', 'Alamat', 'Pabula', 'Talambuhay', 'a'),
  (1, true, 3, NULL, 'Ang alamat tungkol sa pinagmulan ng bahaghari (rainbow) ay isang halimbawa ng kwentong nagpapaliwanag tungkol sa', 'Isang tunay na pangyayari sa balita', 'Pinagmulan ng isang bagay sa kalikasan', 'Isang aklat-aralin', 'Isang talaan ng numero', 'b'),
  (1, true, 3, NULL, 'Alin sa mga sumusunod ang wastong baybay ng salitang tumutukoy sa unang hapunan sa gabi?', 'hapunan', 'hapunann', 'hapunn', 'hapoonan', 'a'),
  (1, true, 3, NULL, 'Alin sa mga sumusunod ang tamang baybay ng salitang tumutukoy sa gulay o pagkain mula sa halaman?', 'gulai', 'gulay', 'gulaay', 'gulaiy', 'b'),
  (1, true, 3, NULL, 'Alin sa mga sumusunod ang tamang gamit ng salitang "salamat" sa pangungusap?', 'Salamat sa iyong tulong.', 'Sa salamat iyong tulong.', 'Tulong salamat sa iyong.', 'Iyong salamat sa tulong.', 'a'),
  (1, true, 3, NULL, 'The prefix "mis-" in the word "misspell" changes the meaning of "spell" to mean', 'To spell correctly', 'To spell wrongly', 'To spell again', 'To never spell', 'b'),
  (1, true, 3, NULL, 'Adding the suffix "-able" to the word "wash" creates the word "washable," which means', 'Cannot be washed', 'Able to be washed', 'Already washed', 'Never needs washing', 'b'),
  (1, true, 3, NULL, 'Which word means almost the same as "begin"?', 'End', 'Start', 'Stop', 'Finish', 'b'),
  (1, true, 3, NULL, 'Which word means the opposite of "empty"?', 'Hollow', 'Full', 'Bare', 'Vacant', 'b'),
  (1, true, 3, NULL, 'Which of these best describes a barangay''s location near rivers or coasts in pre-colonial times?', 'It made trade and fishing easier', 'It had no effect on daily life', 'It made farming impossible', 'It stopped all forms of travel', 'a'),
  (1, true, 3, NULL, 'Which of these best describes why early Filipino communities valued cooperation like bayanihan?', 'It made work faster and easier for everyone', 'It was required by foreign traders', 'It replaced the need for farming', 'It had no real benefit', 'a'),
  (1, true, 3, NULL, 'Which of these best explains why a community needs both producers and consumers?', 'Producers make goods, and consumers use or buy them, so both are needed to keep the economy working', 'Only producers are necessary; consumers are optional', 'Only consumers are necessary; producers are optional', 'Neither role matters in a community', 'a'),
  (1, true, 3, NULL, 'Which of these correctly shows a cause and its effect: "It did not rain for weeks, so the plants wilted."', 'The plants wilting caused the lack of rain', 'The lack of rain caused the plants to wilt', 'The two events are unrelated', 'The plants caused it to rain', 'b'),
  (1, true, 3, NULL, 'Which of these correctly shows a cause and its effect: "Ana studied hard, so she passed the test."', 'Passing the test caused Ana to study hard', 'Studying hard caused Ana to pass the test', 'The two events are unrelated', 'The test caused Ana to study', 'b'),
  (1, true, 3, NULL, 'If a character in a story forgets to water their plant for many days, what can you predict will happen to the plant?', 'It will grow taller and healthier', 'It will likely wilt or dry out', 'It will turn into a different plant', 'Nothing will change at all', 'b'),
  (1, true, 3, NULL, 'Which of these best summarizes a story about a boy who works hard every day to help his family sell goods at the market?', 'The boy is lazy and avoids helping his family', 'The boy shows diligence and care for his family', 'The boy never goes to the market', 'The boy dislikes his family', 'b'),
  (1, true, 3, NULL, 'Which of these is the best example of a procedural (how-to) text?', 'A recipe with numbered steps', 'A poem about the moon', 'A persuasive letter', 'A description of a sunset', 'a'),
  (1, true, 3, NULL, 'Which of these is the best example of a descriptive text?', 'Instructions to build a birdhouse', 'A vivid paragraph describing a colorful garden', 'A list of math steps', 'A weather report with only numbers', 'b'),
  (1, true, 3, NULL, 'Which sentence correctly uses the word "because" to explain a reason?', 'She stayed home because she was sick.', 'Because she stayed home she was sick.', 'She, because was sick stayed home.', 'She stayed because home sick was.', 'a'),
  (1, true, 3, NULL, 'In the sentence "The bright red kite soared high," which words describe the kite?', 'soared, high', 'bright, red', 'the, kite', 'kite, soared', 'b'),
  (1, true, 3, NULL, 'Which of these words is a synonym for "brave"?', 'Fearful', 'Courageous', 'Timid', 'Nervous', 'b'),
  (1, true, 3, NULL, 'Which of these words is an antonym for "strong"?', 'Powerful', 'Weak', 'Sturdy', 'Mighty', 'b'),
  (1, true, 3, NULL, 'A rice terrace carved into a mountainside is an example of what kind of structure?', 'A completely natural structure with no human effort', 'A human-made structure built by farmers over generations', 'A structure found only underwater', 'A type of weather pattern', 'b'),
  (1, true, 3, NULL, 'Which of these best shows why simple machines are useful in daily life?', 'They make work harder and slower', 'They help people do work with less effort', 'They only work in factories', 'They have no real purpose', 'b'),
  (1, true, 3, NULL, 'Which of these best explains why we classify animals into groups like mammals and reptiles?', 'It helps scientists study and understand their similarities and differences', 'It has no scientific purpose', 'It changes what the animals eat', 'It only matters for pets', 'a'),
  (1, true, 3, NULL, 'Which of these best explains why the water cycle is important for living things?', 'It has no real effect on plants or animals', 'It moves water around the Earth, providing rain for plants, animals, and people', 'It only affects the ocean', 'It stops all rainfall permanently', 'b'),
  (1, true, 3, NULL, 'Ang tawag sa isang kwentong nagpapahayag ng damdamin gamit ang tula ay', 'Balita', 'Tula', 'Talaarawan', 'Sanaysay', 'b'),
  (1, true, 3, NULL, 'Ang "malinis" ay kasalungat ng', 'Marumi', 'Maayos', 'Malinaw', 'Magaan', 'a');