-- Lexicon Arena Grade 3 -- 201 entries to meet the 200-per-grade target.
insert into public.sq_lexicon_arena (term_id, is_active, grade_level, language, definition, correct_spelling, wrong_a, wrong_b, wrong_c) values
  (1, true, 3, 'English', 'A type of weather with heavy rain and loud noise in the sky', 'thunderstorm', 'thunderstrom', 'thundestorm', 'thunderstrorm'),
  (1, true, 3, 'English', 'A colorful arc that appears in the sky after rain', 'rainbow', 'ranibow', 'rainbowe', 'rainboww'),
  (1, true, 3, 'English', 'A long period with little or no rain', 'drought', 'draught', 'drouhgt', 'droght'),
  (1, true, 3, 'English', 'Too much water covering land that is usually dry', 'flood', 'floud', 'flod', 'floood'),
  (1, true, 3, 'English', 'A gentle wind', 'breeze', 'breaze', 'breez', 'breeeze'),
  (1, true, 3, 'English', 'An animal that feeds its young with milk and has fur or hair', 'mammal', 'mamal', 'mammel', 'mammul'),
  (1, true, 3, 'English', 'A cold-blooded animal with scales, like a snake or lizard', 'reptile', 'reptil', 'reptiel', 'repitle'),
  (1, true, 3, 'English', 'A small animal with six legs, like an ant or bee', 'insect', 'insekt', 'incect', 'insict'),
  (1, true, 3, 'English', 'The natural home of a plant or animal', 'habitat', 'habitit', 'habbitat', 'habitate'),
  (1, true, 3, 'English', 'The way an animal hides by blending into its surroundings', 'camouflage', 'camoflage', 'camouflag', 'camoflauge'),
  (1, true, 3, 'English', 'Matter that keeps its own shape, like a rock', 'solid', 'solad', 'solidd', 'solide'),
  (1, true, 3, 'English', 'Matter that takes the shape of its container, like water', 'liquid', 'liqiud', 'liquad', 'liquide'),
  (1, true, 3, 'English', 'How hot or cold something is', 'temperature', 'temperture', 'tempreture', 'temperatur'),
  (1, true, 3, 'English', 'When a liquid changes into a gas by heating', 'boiling', 'boyling', 'boilling', 'boilng'),
  (1, true, 3, 'English', 'When a solid changes into a liquid by heating', 'melting', 'meltting', 'meltin', 'meltiing'),
  (1, true, 3, 'English', 'When a liquid changes into a solid by cooling', 'freezing', 'freazing', 'freeezing', 'friezing'),
  (1, true, 3, 'English', 'The system that leads and makes rules for a country', 'government', 'goverment', 'govermment', 'governmen'),
  (1, true, 3, 'English', 'A person who legally belongs to a country', 'citizen', 'citzen', 'citisen', 'citizin'),
  (1, true, 3, 'English', 'A group of people living in the same area', 'community', 'comunity', 'commuinty', 'comminity'),
  (1, true, 3, 'English', 'A local government area smaller than a city', 'municipality', 'municipalty', 'municipallity', 'munisipality'),
  (1, true, 3, 'English', 'The act of choosing leaders by voting', 'election', 'electon', 'eleciton', 'electshun'),
  (1, true, 3, 'English', 'Telling the truth and not lying', 'honest', 'honist', 'onest', 'honnest'),
  (1, true, 3, 'English', 'Willing to give freely to others', 'generous', 'generuos', 'genarous', 'generas'),
  (1, true, 3, 'English', 'Showing polite regard for someone', 'respectful', 'respectfull', 'respecful', 'respektful'),
  (1, true, 3, 'English', 'Being reliable and doing what you should do', 'responsible', 'responsable', 'responsibel', 'responcible'),
  (1, true, 3, 'English', 'To keep trying even when something is hard', 'persevere', 'perservere', 'persevear', 'presevere'),
  (1, true, 3, 'English', 'The ability to wait calmly without complaining', 'patience', 'patiense', 'pashence', 'patients'),
  (1, true, 3, 'English', 'Being brave when facing something difficult', 'courage', 'curage', 'courrage', 'corage'),
  (1, true, 3, 'English', 'A word that names a person, place, or thing', 'noun', 'nuon', 'nowne', 'noune'),
  (1, true, 3, 'English', 'A word that shows an action or state of being', 'verb', 'verrb', 'verbe', 'verv'),
  (1, true, 3, 'English', 'A word that describes a noun', 'adjective', 'adjectiv', 'adjectve', 'adjecktive'),
  (1, true, 3, 'English', 'A word that describes a verb, adjective, or another adverb', 'adverb', 'advverb', 'adverrb', 'adverbe'),
  (1, true, 3, 'English', 'A word used in place of a noun, like he or she', 'pronoun', 'pronuon', 'pronowne', 'pronoune'),
  (1, true, 3, 'English', 'A word that joins two words or sentences, like and or but', 'conjunction', 'conjuction', 'conjunktion', 'conjunccion'),
  (1, true, 3, 'English', 'A group of words that expresses a complete thought', 'sentence', 'sentance', 'sentense', 'senntence'),
  (1, true, 3, 'English', 'A group of sentences about one main idea', 'paragraph', 'paragrap', 'paragrapgh', 'paragrath'),
  (1, true, 3, 'English', 'Putting numbers together to find a total', 'addition', 'adition', 'additon', 'adddition'),
  (1, true, 3, 'English', 'Taking one number away from another', 'subtraction', 'substraction', 'subtracton', 'subtracsion'),
  (1, true, 3, 'English', 'Combining equal groups to find a total, faster than adding', 'multiplication', 'multiplacation', 'multipication', 'multiplecation'),
  (1, true, 3, 'English', 'Splitting a number into equal groups', 'division', 'divison', 'divission', 'diviosn'),
  (1, true, 3, 'English', 'A part of a whole, like one half or one third', 'fraction', 'fracton', 'fracction', 'fraktion'),
  (1, true, 3, 'English', 'The top number in a fraction', 'numerator', 'numorator', 'numeratar', 'numarator'),
  (1, true, 3, 'English', 'The bottom number in a fraction', 'denominator', 'denomenator', 'denomintor', 'denominater'),
  (1, true, 3, 'English', 'An animal that hunts other animals for food', 'predator', 'preditor', 'predater', 'predatore'),
  (1, true, 3, 'English', 'An animal that is hunted by another animal', 'prey', 'pray', 'preey', 'prei'),
  (1, true, 3, 'English', 'The community of living and non-living things in an area', 'ecosystem', 'ecosystim', 'ecosytem', 'ecosysten'),
  (1, true, 3, 'English', 'A flash of light in the sky during a storm', 'lightning', 'lightening', 'litening', 'lighning'),
  (1, true, 3, 'English', 'A loud rumbling sound heard during a storm', 'thunder', 'thundar', 'thundr', 'thundher'),
  (1, true, 3, 'English', 'A large mass of tiny water droplets floating in the sky', 'cloud', 'clowd', 'cloude', 'clound'),
  (1, true, 3, 'English', 'A violent storm with strong swirling winds', 'storm', 'strom', 'storme', 'sotrm'),
  (1, true, 3, 'English', 'Not honest or fair', 'unfair', 'unfare', 'infair', 'unfaire'),
  (1, true, 3, 'English', 'Full of energy and life', 'lively', 'livley', 'livly', 'lievely'),
  (1, true, 3, 'English', 'Something that happens by surprise', 'unexpected', 'unexpeted', 'unexpectid', 'uneexpected'),
  (1, true, 3, 'English', 'A place where people can borrow books', 'library', 'libary', 'librery', 'librairy'),
  (1, true, 3, 'English', 'A tool used to find directions like north and south', 'compass', 'compas', 'compess', 'compasse'),
  (1, true, 3, 'English', 'A large area of trees and wildlife', 'forest', 'forrest', 'foresst', 'forest'''),
  (1, true, 3, 'English', 'A place where crops are grown and animals are raised', 'farm', 'farrm', 'faram', 'fahrm'),
  (1, true, 3, 'English', 'A large area of very dry land with little rain', 'desert', 'dessert', 'desart', 'desurt'),
  (1, true, 3, 'English', 'A tall landform that rises much higher than the surrounding land', 'mountain', 'mountian', 'mounten', 'mountaine'),
  (1, true, 3, 'English', 'A large body of salt water', 'ocean', 'oshun', 'oceon', 'oceann'),
  (1, true, 3, 'English', 'Land completely surrounded by water', 'island', 'iland', 'islande', 'islend'),
  (1, true, 3, 'English', 'A large stream of water flowing into the sea', 'river', 'rivar', 'rivver', 'riverr'),
  (1, true, 3, 'English', 'The season with the coldest weather', 'winter', 'wintar', 'wintter', 'wintre'),
  (1, true, 3, 'English', 'The season when plants begin to grow after winter', 'spring', 'sprring', 'spirng', 'sprin'),
  (1, true, 3, 'English', 'The hottest season of the year', 'summer', 'sumer', 'summar', 'summerr'),
  (1, true, 3, 'English', 'The season when leaves fall from trees', 'autumn', 'autum', 'atumn', 'auttumn'),
  (1, true, 3, 'English', 'A young frog before it grows legs', 'tadpole', 'tadpol', 'tadpolle', 'tadpoal'),
  (1, true, 3, 'English', 'An insect that starts as a caterpillar', 'butterfly', 'buterfly', 'butterflie', 'buttterfly'),
  (1, true, 3, 'English', 'A place that sells goods, like fruits and vegetables', 'market', 'markit', 'markett', 'markat'),
  (1, true, 3, 'English', 'Money paid to the government to fund public services', 'tax', 'taxx', 'taks', 'tacs'),
  (1, true, 3, 'English', 'A person who grows crops or raises animals for a living', 'farmer', 'farmar', 'farrmer', 'farmerr'),
  (1, true, 3, 'English', 'A person who catches fish for a living', 'fisherman', 'fisharman', 'fishermann', 'fisherrman'),
  (1, true, 3, 'English', 'A doctor who treats sick people', 'physician', 'phisician', 'physican', 'phisitian'),
  (1, true, 3, 'English', 'A person who teaches students', 'teacher', 'teachar', 'teachher', 'teachier'),
  (1, true, 3, 'English', 'A building where sick people are treated', 'hospital', 'hospitel', 'hospitle', 'hospitol'),
  (1, true, 3, 'English', 'A meal eaten in the early morning', 'breakfast', 'brakfast', 'breackfast', 'breakfest'),
  (1, true, 3, 'English', 'The last meal of the day, eaten in the evening', 'dinner', 'diner', 'dinnar', 'dinnner'),
  (1, true, 3, 'English', 'A story that teaches a lesson, often using animals as characters', 'fable', 'fabel', 'fabble', 'faible'),
  (1, true, 3, 'English', 'A traditional story explaining something in nature', 'legend', 'legand', 'legennd', 'leggend'),
  (1, true, 3, 'English', 'A wise saying that gives advice about life', 'proverb', 'provverb', 'proverbe', 'provurb'),
  (1, true, 3, 'English', 'A puzzle in the form of a question with a tricky answer', 'riddle', 'riddel', 'ridle', 'riddell'),
  (1, true, 3, 'English', 'A piece of writing with rhythm, sometimes with rhyme', 'poem', 'poeme', 'poam', 'poemm'),
  (1, true, 3, 'English', 'A person who writes books or stories', 'author', 'authar', 'auther', 'authorr'),
  (1, true, 3, 'English', 'The place and time where a story happens', 'setting', 'settin', 'settting', 'settingg'),
  (1, true, 3, 'English', 'A person in a story', 'character', 'charecter', 'charactar', 'charater'),
  (1, true, 3, 'English', 'A problem that characters face in a story', 'conflict', 'conflikt', 'confflict', 'confilct'),
  (1, true, 3, 'English', 'How a story ends and the problem is solved', 'resolution', 'resoluton', 'resolusion', 'resollution'),
  (1, true, 3, 'English', 'A word that means almost the same as another word', 'synonym', 'synonim', 'sinonym', 'synnonym'),
  (1, true, 3, 'English', 'A word that means the opposite of another word', 'antonym', 'antonim', 'antynom', 'anttonym'),
  (1, true, 3, 'English', 'A group of letters added to the beginning of a word', 'prefix', 'prefixe', 'prefics', 'prefex'),
  (1, true, 3, 'English', 'A group of letters added to the end of a word', 'suffix', 'sufix', 'suffics', 'suffex'),
  (1, true, 3, 'English', 'The root or base part of a word', 'root', 'rute', 'roote', 'rooot'),
  (1, true, 3, 'English', 'The number that comes after ninety-nine', 'hundred', 'hundrid', 'hunderd', 'hundred'''),
  (1, true, 3, 'English', 'The number that comes after nine hundred ninety-nine', 'thousand', 'thousend', 'thowsand', 'thousnd'),
  (1, true, 3, 'English', 'A shape with three sides', 'triangle', 'triangel', 'triangle''', 'triangl'),
  (1, true, 3, 'English', 'A shape with four equal sides', 'square', 'squair', 'sqaure', 'squarre'),
  (1, true, 3, 'English', 'A round shape with no corners', 'circle', 'circel', 'cirlce', 'circkle'),
  (1, true, 3, 'English', 'A shape with four sides where opposite sides are equal length', 'rectangle', 'rectangel', 'rectangl', 'rectanglle'),
  (1, true, 3, 'English', 'The distance around the edge of a shape', 'perimeter', 'parameter', 'perimetter', 'perimiter'),
  (1, true, 3, 'English', 'The amount of space inside a flat shape', 'area', 'aria', 'areea', 'arae'),
  (1, true, 3, 'English', 'A tool used to measure the length of things', 'ruler', 'rular', 'rulor', 'rulerr'),
  (1, true, 3, 'English', 'The path the earth takes as it moves around the sun', 'orbit', 'orbet', 'orrbit', 'orbitt'),
  (1, true, 3, 'English', 'The star at the center of our solar system', 'sun', 'sunn', 'suhn', 'san'),
  (1, true, 3, 'English', 'The object that orbits the earth and shines at night', 'moon', 'moone', 'mune', 'moonn'),
  (1, true, 3, 'English', 'A group of stars that form a pattern in the sky', 'constellation', 'constelation', 'constellasion', 'constelllation'),
  (1, true, 3, 'English', 'The layer of air surrounding the earth', 'atmosphere', 'atmospher', 'atmosphre', 'atmosfere'),
  (1, true, 3, 'English', 'A large group of people who share the same customs', 'culture', 'culchure', 'cultur', 'cultture'),
  (1, true, 3, 'English', 'A celebration that honors a special event or belief', 'festival', 'festivel', 'festivul', 'festivall'),
  (1, true, 3, 'English', 'A custom passed down from parents to children over time', 'tradition', 'tradtion', 'traddition', 'tradision'),
  (1, true, 3, 'English', 'A family member who lived long ago', 'ancestor', 'ancester', 'anscestor', 'ancesstor'),
  (1, true, 3, 'English', 'Working together with others toward a shared goal', 'cooperation', 'cooparation', 'coperation', 'cooperration'),
  (1, true, 3, 'English', 'Feeling thankful for something', 'gratitude', 'gratitud', 'grattitude', 'gratitiude'),
  (1, true, 3, 'English', 'A device used to move things from one place to another', 'vehicle', 'vehicel', 'vehickle', 'vehical'),
  (1, true, 3, 'English', 'A two-wheeled vehicle pedaled by a rider', 'bicycle', 'bycicle', 'bicicle', 'bicyle'),
  (1, true, 3, 'English', 'A vehicle that flies through the air', 'airplane', 'airplain', 'aeroplan', 'airplanne'),
  (1, true, 3, 'Filipino', 'Ang bahagi ng kalangitan na nakikita natin sa araw', 'langit', 'langet', 'langitt', 'langiit'),
  (1, true, 3, 'Filipino', 'Ang lupang tinitirhan natin', 'lupa', 'lupah', 'loopa', 'lupaa'),
  (1, true, 3, 'Filipino', 'Ang hindi nakikitang bagay na dumadaloy sa paligid at ginagamit natin sa paghinga', 'hangin', 'hanggin', 'hanggin''', 'hangen'),
  (1, true, 3, 'Filipino', 'Ang malaking katubigang may maalat na tubig', 'dagat', 'dagaat', 'dahat', 'dagatt'),
  (1, true, 3, 'Filipino', 'Ang mataas na bahagi ng lupa na tumataas sa palibot', 'bundok', 'bundok''', 'bundak', 'bundoc'),
  (1, true, 3, 'Filipino', 'Ang tumatakbong tubig na dumadaloy patungo sa dagat', 'ilog', 'ilogg', 'elog', 'ilug'),
  (1, true, 3, 'Filipino', 'Ang malawak na lugar na puno ng mga puno at hayop', 'kagubatan', 'kagubattan', 'kagubaatan', 'kagubuatan'),
  (1, true, 3, 'Filipino', 'Ang mga likas na bagay sa paligid natin tulad ng puno at hayop', 'kalikasan', 'kalikassan', 'kalikaan', 'kalikhasan'),
  (1, true, 3, 'Filipino', 'Ang pakiramdam ng lamig', 'malamig', 'malamiig', 'malammig', 'malimig'),
  (1, true, 3, 'Filipino', 'Ang pakiramdam ng init', 'mainit', 'mainet', 'mainitt', 'maynit'),
  (1, true, 3, 'Filipino', 'Ang katangian ng lugar na maraming liwanag', 'maliwanag', 'maliwannag', 'maliwanang', 'maliuanag'),
  (1, true, 3, 'Filipino', 'Ang katangian ng lugar na walang liwanag', 'madilim', 'madilem', 'madillim', 'madilm'),
  (1, true, 3, 'Filipino', 'Ang hindi kaaya-ayang amoy', 'mabaho', 'mabahoo', 'mabajo', 'mabahho'),
  (1, true, 3, 'Filipino', 'Ang kaaya-ayang amoy', 'mabango', 'mabanggo', 'mabangoh', 'mabango'''),
  (1, true, 3, 'Filipino', 'Ang katangian ng bagay na hindi makinis kapag hinawakan', 'magaspang', 'magaspag', 'magasspang', 'magaspaang'),
  (1, true, 3, 'Filipino', 'Ang katangian ng bagay na malambot at pantay kapag hinawakan', 'makinis', 'makines', 'makinnis', 'makinys'),
  (1, true, 3, 'Filipino', 'Ang damdamin ng kaligayahan', 'saya', 'sayah', 'sayaa', 'saja'),
  (1, true, 3, 'Filipino', 'Ang damdamin ng kalungkutan', 'lungkot', 'lunkot', 'lungkut', 'lungkott'),
  (1, true, 3, 'Filipino', 'Ang matinding damdaming naiinis o nagagalit', 'galit', 'galet', 'gallit', 'galitt'),
  (1, true, 3, 'Filipino', 'Ang damdamin kapag natatakot sa isang bagay', 'takot', 'takut', 'takkot', 'takot'''),
  (1, true, 3, 'Filipino', 'Ang biglaang pagkagulat sa isang bagay', 'surpresa', 'surprisa', 'surpressa', 'surpreza'),
  (1, true, 3, 'Filipino', 'Ang malalim na damdamin ng pag-ibig sa iba', 'pagmamahal', 'pagmamahall', 'pagmahal', 'pagmamaahal'),
  (1, true, 3, 'Filipino', 'Ang labis na kalungkutan dahil sa pagkawala ng isang mahal sa buhay', 'pighati', 'pighatti', 'pigati', 'pighate'),
  (1, true, 3, 'Filipino', 'Ang pinakamaliit na yunit ng pamahalaan sa Pilipinas', 'barangay', 'baranggay', 'barrangay', 'barangai'),
  (1, true, 3, 'Filipino', 'Ang lugar na pinamamahalaan ng isang mayor', 'munisipyo', 'munisipio', 'munesipyo', 'munnisipyo'),
  (1, true, 3, 'Filipino', 'Ang malaking bahagi ng bansa na binubuo ng maraming bayan', 'probinsya', 'probinsiya', 'probinsya''', 'probinsa'),
  (1, true, 3, 'Filipino', 'Ang malaki at moderno na lugar sa isang bansa', 'lungsod', 'lunsod', 'lungsud', 'lungsod'''),
  (1, true, 3, 'Filipino', 'Ang paggawa ng pagpili sa isang halalan', 'pagboto', 'pagvoto', 'pagbotoh', 'pagbuto'),
  (1, true, 3, 'Filipino', 'Ang taong namumuno sa isang grupo', 'lider', 'leader', 'liider', 'lidor'),
  (1, true, 3, 'Filipino', 'Ang grupo ng mga taong nakatira sa parehong lugar', 'komunidad', 'komunidud', 'kommunidad', 'komunided'),
  (1, true, 3, 'Filipino', 'Ang oras o panahon ng isang partikular na pangyayari', 'pagkakataon', 'pagkakatoan', 'pagkakataun', 'pagkakataong'),
  (1, true, 3, 'Filipino', 'Ang grupo ng mga taong may kaugnayan sa dugo', 'pamilya', 'pamilia', 'pamiliya', 'pamilyah'),
  (1, true, 3, 'Filipino', 'Ang relasyon sa pagitan ng magkakaibigan', 'pagkakaibigan', 'pagkakaibiggan', 'pagkakaibgan', 'pagkaibigan'),
  (1, true, 3, 'Filipino', 'Ang katapatan sa isang tao o pangako', 'katapatan', 'katapattan', 'katapaatan', 'katapaten'),
  (1, true, 3, 'Filipino', 'Ang pagiging matapang sa harap ng panganib', 'tapang', 'tapaang', 'tapanng', 'tapangh'),
  (1, true, 3, 'Filipino', 'Ang paggalang sa nakatatanda', 'paggalang', 'paggalanng', 'pagalang', 'paggallang'),
  (1, true, 3, 'Filipino', 'Ang tulong-tulong na gawain ng magkakapitbahay', 'bayanihan', 'bayanihann', 'bayaniahan', 'bayannihan'),
  (1, true, 3, 'Filipino', 'Ang salitang tumutukoy sa isang tao, lugar, o bagay', 'pangngalan', 'pangalan', 'panngalan', 'pangngalann'),
  (1, true, 3, 'Filipino', 'Ang salitang nagsasaad ng kilos', 'pandiwa', 'pandiiwa', 'pandiwah', 'pandeewa'),
  (1, true, 3, 'Filipino', 'Ang salitang naglalarawan sa isang pangngalan', 'pang-uri', 'panguri', 'pang-uree', 'pang-ure'),
  (1, true, 3, 'Filipino', 'Ang salitang naglalarawan sa pandiwa', 'pang-abay', 'pangabay', 'pang-abbay', 'pang-abai'),
  (1, true, 3, 'Filipino', 'Ang isang tao o bagay na pinag-uusapan sa pangungusap', 'paksa', 'paksah', 'pagsa', 'paksaa'),
  (1, true, 3, 'Filipino', 'Ang lugar at panahon kung saan naganap ang kwento', 'tagpuan', 'tagpoan', 'tagpuann', 'tagpwan'),
  (1, true, 3, 'Filipino', 'Ang taong gumaganap sa isang kwento', 'tauhan', 'tauwhan', 'tauhann', 'tawuhan'),
  (1, true, 3, 'Filipino', 'Ang aral na natututunan mula sa isang kwento', 'aral', 'arral', 'araal', 'arral'''),
  (1, true, 3, 'Filipino', 'Ang kwentong may hayop bilang tauhan na may aral', 'pabula', 'pabola', 'pabulah', 'pabulla'),
  (1, true, 3, 'Filipino', 'Ang kwentong nagpapaliwanag tungkol sa pinagmulan ng isang bagay', 'alamat', 'alammat', 'alamatt', 'allamat'),
  (1, true, 3, 'Filipino', 'Ang taong sumusulat ng mga kwento o aklat', 'manunulat', 'manunulatt', 'manunolat', 'manuulat'),
  (1, true, 3, 'Filipino', 'Ang salitang magkatulad ang kahulugan', 'kasingkahulugan', 'kasingkahulugann', 'kasingkahulgan', 'kasingkaulugan'),
  (1, true, 3, 'Filipino', 'Ang salitang magkasalungat ang kahulugan', 'kasalungat', 'kasalunggat', 'kasalungatt', 'kasalongat'),
  (1, true, 3, 'Filipino', 'Ang bilang na sumusunod sa siyamnapu''t siyam', 'sandaan', 'sandan', 'sandaann', 'sandaaan'),
  (1, true, 3, 'Filipino', 'Ang bilang na sumusunod sa siyam na raan siyamnapu''t siyam', 'sanlibo', 'sanlibbo', 'sanlibu', 'sanleebo'),
  (1, true, 3, 'Filipino', 'Ang hugis na may tatlong gilid', 'tatsulok', 'tatsulokk', 'tatsolok', 'tatsulic'),
  (1, true, 3, 'Filipino', 'Ang hugis na apat ang magkakaparehong gilid', 'parisukat', 'parisukatt', 'parizukat', 'parisokat'),
  (1, true, 3, 'Filipino', 'Ang bilog na hugis na walang sulok', 'bilog', 'bilogg', 'bilug', 'bilog'''),
  (1, true, 3, 'Filipino', 'Ang bituin na siyang pinakamalapit sa mundo', 'araw', 'arraw', 'arau', 'araw'''),
  (1, true, 3, 'Filipino', 'Ang bagay sa kalangitan na nagbibigay liwanag sa gabi', 'buwan', 'buan', 'buwann', 'buwaan'),
  (1, true, 3, 'Filipino', 'Ang mga maliliit na bituin na nakikita sa gabi', 'bituin', 'bituwin', 'bitwin', 'bituinn'),
  (1, true, 3, 'Filipino', 'Ang panahon ng taglamig o malamig na panahon', 'taglamig', 'taglamigg', 'taglammig', 'taglamiig'),
  (1, true, 3, 'Filipino', 'Ang panahon ng tag-init o mainit na panahon', 'taginit', 'tag-init', 'taginitt', 'tagiinit'),
  (1, true, 3, 'Filipino', 'Ang panahon ng maraming ulan', 'tag-ulan', 'tagulan', 'tag-ullan', 'tag-olan'),
  (1, true, 3, 'Filipino', 'Ang lugar na pinagbibilhan ng gulay, isda, at karne', 'palengke', 'palengki', 'palenke', 'palengkke'),
  (1, true, 3, 'Filipino', 'Ang taong nagtatanim ng palay at gulay', 'magsasaka', 'magsasakka', 'magsasakah', 'magasaka'),
  (1, true, 3, 'Filipino', 'Ang taong namamalakaya sa dagat', 'mangingisda', 'mangingisdah', 'manggingisda', 'mangngisda'),
  (1, true, 3, 'Filipino', 'Ang taong nagtuturo sa paaralan', 'guro', 'guroh', 'gooro', 'guru'),
  (1, true, 3, 'Filipino', 'Ang gusaling pinagpapagamutan ng mga maysakit', 'ospital', 'hospital', 'ospitall', 'ospitl'),
  (1, true, 3, 'Filipino', 'Ang unang pagkain sa umaga', 'almusal', 'almosal', 'almusall', 'almusar'),
  (1, true, 3, 'Filipino', 'Ang huling pagkain sa gabi', 'hapunan', 'hapunann', 'hapunnan', 'hapoonan'),
  (1, true, 3, 'Filipino', 'Ang bahay na tinitirhan ng isang pamilya', 'tahanan', 'tahannan', 'tahaanan', 'tahanann'),
  (1, true, 3, 'Filipino', 'Ang kasabihang matalinhaga na nagtuturo ng aral', 'salawikain', 'salawikaen', 'salawikainn', 'salawikian'),
  (1, true, 3, 'Filipino', 'Ang palaisipang may sagot na dapat hulaan', 'bugtong', 'bugtongg', 'bugtung', 'bugtoong'),
  (1, true, 3, 'Filipino', 'Ang paraan ng pagsasabi ng damdamin gamit ang tula', 'tula', 'tulah', 'toola', 'tulla'),
  (1, true, 3, 'Filipino', 'Ang isang uri ng sasakyang de-gulong dalawa', 'bisikleta', 'bisiklita', 'bisikletta', 'bisicleta'),
  (1, true, 3, 'Filipino', 'Ang sasakyang lumilipad sa himpapawid', 'eroplano', 'airplano', 'eroplanno', 'eroplaano'),
  (1, true, 3, 'Filipino', 'Ang pinakamalaking pangkat ng mga tao na may parehong wika at kultura', 'lahi', 'lahee', 'lahi''', 'laahi'),
  (1, true, 3, 'Filipino', 'Ang paraan ng pamumuhay at paniniwala ng isang lipunan', 'kultura', 'kulturra', 'kulttura', 'kultuura'),
  (1, true, 3, 'Filipino', 'Ang kaugaliang sinusunod ng mga tao sa isang lugar', 'kaugalian', 'kaugaliann', 'kaugaliaan', 'kaugalain'),
  (1, true, 3, 'Filipino', 'Ang selebrasyon na ginaganap taon-taon', 'pista', 'pistah', 'pesta', 'pistta'),
  (1, true, 3, 'Filipino', 'Ang paglilinis ng bahay o paligid', 'paglilinis', 'paglilines', 'paglilinnis', 'paglilinys'),
  (1, true, 3, 'Filipino', 'Ang kilos na paghahanda ng pagkain', 'pagluluto', 'pagluluttoh', 'pagluto', 'paglulutoh'),
  (1, true, 3, 'Filipino', 'Ang kilos na paghuhugas ng mga plato', 'paghuhugas', 'paghuhugass', 'paghugas', 'paguhugas'),
  (1, true, 3, 'Filipino', 'Ang tirahan ng mga hayop sa gubat', 'yungib', 'yunggib', 'yungeeb', 'yungib'''),
  (1, true, 3, 'Filipino', 'Ang hayop na may pakpak at kayang lumipad', 'ibon', 'ebon', 'ibonn', 'ibbon'),
  (1, true, 3, 'Filipino', 'Ang hayop na kumakain ng damo at nakatira sa gubat o parang', 'hayop', 'hayup', 'hayopp', 'hayob'),
  (1, true, 3, 'Filipino', 'Ang tinatawag sa uhaw na hindi pa nabusog', 'gutom', 'gotom', 'gutomm', 'gutoom'),
  (1, true, 3, 'Filipino', 'Ang pakiramdam pagkatapos kumain ng sapat', 'busog', 'busug', 'busogg', 'buzog');