INSERT INTO public.mtap_expansion_content
  (question_code, grade, strand, archetype, tier, params, question, options,
   correct_answer, distractor_rationale, solution_steps, technique, scaffold_note,
   time_budget_seconds, visual, generated_by, reviewed)
VALUES
  ('g2-s7-wage_rate_to_total-difficult-0001', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 40, "threshold": 5, "overtime_rate": 60, "hours": 9}'::jsonb, 'Rina earns 40 pesos an hour for the first 5 hours, then 60 pesos an hour after that. How much does she earn for 9 hours of work?', '["440", "540", "360", "380"]'::jsonb, '440', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 5 hours: 40x5=200. Remaining 4 hours: 60x4=240. Total = 440.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s7-wage_rate_to_total-difficult-0002', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 30, "threshold": 4, "overtime_rate": 40, "hours": 6}'::jsonb, 'Rina earns 30 pesos an hour for the first 4 hours, then 40 pesos an hour after that. How much does she earn for 6 hours of work?', '["160", "180", "200", "240"]'::jsonb, '200', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 4 hours: 30x4=120. Remaining 2 hours: 40x2=80. Total = 200.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s7-wage_rate_to_total-difficult-0003', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 40, "threshold": 4, "overtime_rate": 50, "hours": 5}'::jsonb, 'Rina earns 40 pesos an hour for the first 4 hours, then 50 pesos an hour after that. How much does she earn for 5 hours of work?', '["250", "160", "210", "200"]'::jsonb, '210', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 4 hours: 40x4=160. Remaining 1 hours: 50x1=50. Total = 210.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s7-wage_rate_to_total-difficult-0004', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 30, "threshold": 4, "overtime_rate": 41, "hours": 8}'::jsonb, 'Rina earns 30 pesos an hour for the first 4 hours, then 41 pesos an hour after that. How much does she earn for 8 hours of work?', '["240", "243", "284", "328"]'::jsonb, '284', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 4 hours: 30x4=120. Remaining 4 hours: 41x4=164. Total = 284.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s7-wage_rate_to_total-difficult-0005', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 20, "threshold": 5, "overtime_rate": 34, "hours": 9}'::jsonb, 'Rina earns 20 pesos an hour for the first 5 hours, then 34 pesos an hour after that. How much does she earn for 9 hours of work?', '["202", "236", "180", "306"]'::jsonb, '236', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 5 hours: 20x5=100. Remaining 4 hours: 34x4=136. Total = 236.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s7-wage_rate_to_total-difficult-0006', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 30, "threshold": 5, "overtime_rate": 45, "hours": 7}'::jsonb, 'Rina earns 30 pesos an hour for the first 5 hours, then 45 pesos an hour after that. How much does she earn for 7 hours of work?', '["315", "240", "195", "210"]'::jsonb, '240', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 5 hours: 30x5=150. Remaining 2 hours: 45x2=90. Total = 240.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s7-wage_rate_to_total-difficult-0007', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 20, "threshold": 4, "overtime_rate": 32, "hours": 6}'::jsonb, 'Rina earns 20 pesos an hour for the first 4 hours, then 32 pesos an hour after that. How much does she earn for 6 hours of work?', '["120", "112", "192", "144"]'::jsonb, '144', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 4 hours: 20x4=80. Remaining 2 hours: 32x2=64. Total = 144.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true),
  ('g2-s7-wage_rate_to_total-difficult-0008', 2, 7, 'wage_rate_to_total', 'difficult', '{"base_rate": 20, "threshold": 5, "overtime_rate": 40, "hours": 6}'::jsonb, 'Rina earns 20 pesos an hour for the first 5 hours, then 40 pesos an hour after that. How much does she earn for 6 hours of work?', '["140", "120", "240", "100"]'::jsonb, '140', '["used the base rate for all hours, ignoring the overtime rate", "used the overtime rate for all hours, ignoring the base rate", "forgot to include the last overtime hour"]'::jsonb, 'First 5 hours: 20x5=100. Remaining 1 hours: 40x1=40. Total = 140.', NULL, '', 60, NULL, 'template-mtap-g2-v1', true)
ON CONFLICT (question_code) DO NOTHING;
