-- Lexicon Arena Grade 4 -- 200 entries to meet the 200-per-grade target.
insert into public.sq_lexicon_arena (term_id, is_active, grade_level, language, definition, correct_spelling, wrong_a, wrong_b, wrong_c) values
  (1, true, 4, 'English', 'A narrative written in poetic form, often with rhyme and rhythm', 'ballad', 'balad', 'ballard', 'baland'),
  (1, true, 4, 'English', 'A story told in prose that describes imaginary events and people', 'fiction', 'ficton', 'fickshun', 'ficsion'),
  (1, true, 4, 'English', 'Writing based on facts and real events', 'nonfiction', 'nonficton', 'nonfickshun', 'non-fictoin'),
  (1, true, 4, 'English', 'A traditional story explaining natural events, often with gods or heroes', 'myth', 'mith', 'mythe', 'myyth'),
  (1, true, 4, 'English', 'A story passed down orally within a culture', 'folktale', 'folktail', 'foaktale', 'folktael'),
  (1, true, 4, 'English', 'A written account of a person''s life by someone else', 'biography', 'biografy', 'biograpy', 'biograhpy'),
  (1, true, 4, 'English', 'A group of lines forming a unit in a poem', 'stanza', 'stanzah', 'stansa', 'stanzza'),
  (1, true, 4, 'English', 'A comparison between two unlike things without using like or as', 'metaphor', 'metafor', 'metaphore', 'metaphour'),
  (1, true, 4, 'English', 'A comparison using the words like or as', 'simile', 'simily', 'simmile', 'simile'''),
  (1, true, 4, 'English', 'The repetition of the same beginning consonant sound in nearby words', 'alliteration', 'alliterasion', 'aliteration', 'alliteraton'),
  (1, true, 4, 'English', 'Giving human qualities to a non-human thing', 'personification', 'personifcation', 'personificasion', 'personifiction'),
  (1, true, 4, 'English', 'The main character in a story', 'protagonist', 'protaganist', 'protagonest', 'protagonist'''),
  (1, true, 4, 'English', 'The character who opposes the main character', 'antagonist', 'antaganist', 'antagonest', 'antagonisst'),
  (1, true, 4, 'English', 'A tiny particle made of two or more atoms joined together', 'molecule', 'molicule', 'molecul', 'moleculle'),
  (1, true, 4, 'English', 'The process of a liquid changing into a gas', 'evaporation', 'evaporasion', 'evapouration', 'evaporaton'),
  (1, true, 4, 'English', 'The process of a gas changing into a liquid', 'condensation', 'condensasion', 'condensaton', 'condesnation'),
  (1, true, 4, 'English', 'Rain, snow, or hail that falls from clouds', 'precipitation', 'precipitaton', 'precipitasion', 'precepitation'),
  (1, true, 4, 'English', 'To mix a substance completely into a liquid', 'dissolve', 'desolve', 'disolve', 'dissolv'),
  (1, true, 4, 'English', 'A mixture in which one substance is evenly spread in another', 'solution', 'solushun', 'solutoin', 'solucion'),
  (1, true, 4, 'English', 'A combination of two or more substances not chemically joined', 'mixture', 'mixtur', 'mixchure', 'mixtuer'),
  (1, true, 4, 'English', 'The force that pulls objects toward the earth', 'gravity', 'gravety', 'gravitty', 'graviti'),
  (1, true, 4, 'English', 'A force that slows down moving objects when surfaces touch', 'friction', 'frickshun', 'fricton', 'frikction'),
  (1, true, 4, 'English', 'A form of energy from moving charged particles', 'electricity', 'electricty', 'electriciti', 'electrisity'),
  (1, true, 4, 'English', 'A material that allows electricity or heat to pass through it', 'conductor', 'conducter', 'conduktor', 'conductorr'),
  (1, true, 4, 'English', 'A material that blocks the flow of electricity or heat', 'insulator', 'insulater', 'insullator', 'insulatorr'),
  (1, true, 4, 'English', 'The property of attracting iron or steel', 'magnetism', 'magnatism', 'magnetisim', 'magnetissm'),
  (1, true, 4, 'English', 'A sudden and complete change, often in government', 'revolution', 'revolucion', 'revolushun', 'revolutoin'),
  (1, true, 4, 'English', 'The act of one country taking control of another land', 'colonization', 'colonisation', 'colonizaton', 'colonizashun'),
  (1, true, 4, 'English', 'Freedom from control by another country or power', 'independence', 'independance', 'independense', 'independece'),
  (1, true, 4, 'English', 'The act of fighting back against control or force', 'resistance', 'resistence', 'resistanse', 'resisstance'),
  (1, true, 4, 'English', 'Traditions and values passed down from earlier generations', 'heritage', 'heritege', 'heretage', 'heritagee'),
  (1, true, 4, 'English', 'A society with its own culture, government, and achievements', 'civilization', 'civilisation', 'civilizaton', 'civilizashun'),
  (1, true, 4, 'English', 'A system of government where citizens choose their leaders', 'democracy', 'democrasy', 'demokracy', 'democracey'),
  (1, true, 4, 'English', 'A form of government where power belongs to the people through elected officials', 'republic', 'republick', 'republik', 'republicc'),
  (1, true, 4, 'English', 'A law formally passed by a governing body', 'legislation', 'legeslation', 'legislaton', 'legislasion'),
  (1, true, 4, 'English', 'The basic laws that state how a country is governed', 'constitution', 'constitucion', 'constitutoin', 'constitushun'),
  (1, true, 4, 'English', 'The answer obtained when dividing one number by another', 'quotient', 'quotiant', 'quotent', 'quotiennt'),
  (1, true, 4, 'English', 'The amount left over after division', 'remainder', 'remaindar', 'remainer', 'remaindder'),
  (1, true, 4, 'English', 'Equal in value, amount, or meaning', 'equivalent', 'equivalant', 'equivalent''', 'equivelent'),
  (1, true, 4, 'English', 'A fraction where the numerator is greater than or equal to the denominator', 'improper', 'imropper', 'improoper', 'impropper'),
  (1, true, 4, 'English', 'To reduce a fraction to its simplest form', 'simplify', 'simplyfy', 'simplifi', 'simplifyy'),
  (1, true, 4, 'English', 'Close to exact but not perfectly precise', 'approximate', 'approximmate', 'aproximate', 'approximatte'),
  (1, true, 4, 'English', 'The property that lets you add or multiply numbers in any order', 'commutative', 'comutative', 'commutatve', 'commutativ'),
  (1, true, 4, 'English', 'The property that lets you group numbers differently when adding or multiplying', 'associative', 'assosiative', 'associattive', 'assosciative'),
  (1, true, 4, 'English', 'The property that lets you multiply a sum by distributing to each addend', 'distributive', 'distributiv', 'distrubutive', 'distribuutive'),
  (1, true, 4, 'English', 'The process of taking in food needed for growth and health', 'nutrition', 'nutrision', 'nutriton', 'nutritoin'),
  (1, true, 4, 'English', 'Nutrients that give the body energy, found in rice and bread', 'carbohydrates', 'carbohidrates', 'carbohydrats', 'carbohydrattes'),
  (1, true, 4, 'English', 'A nutrient that helps build and repair body tissues', 'protein', 'protien', 'proteine', 'proteinn'),
  (1, true, 4, 'English', 'Nutrients needed in small amounts to keep the body healthy', 'vitamins', 'vitamens', 'vitammins', 'vitamins'''),
  (1, true, 4, 'English', 'Nutrients like calcium and iron needed for body functions', 'minerals', 'minerels', 'minarals', 'minneral'),
  (1, true, 4, 'English', 'Practices that keep an environment clean and free of germs', 'sanitation', 'sanitaton', 'sanitasion', 'sanittation'),
  (1, true, 4, 'English', 'The practice of keeping oneself and surroundings clean', 'hygiene', 'higiene', 'hygeine', 'hygein'),
  (1, true, 4, 'English', 'The body''s system that fights off disease and infection', 'immune', 'imune', 'immuen', 'immunne'),
  (1, true, 4, 'English', 'A substance given to protect the body from a disease', 'vaccine', 'vacine', 'vaccin', 'vaccinne'),
  (1, true, 4, 'English', 'An illness that affects the body or mind', 'disease', 'desease', 'diseese', 'diseasse'),
  (1, true, 4, 'English', 'A word that shows a relationship between a noun and another word, like in or on', 'preposition', 'preposeition', 'preposition''', 'prepositoin'),
  (1, true, 4, 'English', 'A sentence that gives a command or instruction', 'imperative', 'imperatve', 'impirative', 'imperativee'),
  (1, true, 4, 'English', 'A sentence that asks a question', 'interrogative', 'interogative', 'interrogattive', 'interrogativ'),
  (1, true, 4, 'English', 'Words that sound the same but have different meanings and spellings', 'homophones', 'homofones', 'homophons', 'homophonees'),
  (1, true, 4, 'English', 'A word formed by combining two smaller words', 'compound', 'compownd', 'compond', 'compoundd'),
  (1, true, 4, 'English', 'The main idea or message of a story', 'theme', 'theeme', 'themme', 'theem'),
  (1, true, 4, 'English', 'A hint given early in a story about what will happen later', 'foreshadowing', 'foreshaddowing', 'foreshadowwing', 'foreshadoing'),
  (1, true, 4, 'English', 'A section of a story that shows an earlier event', 'flashback', 'flashbak', 'flashbback', 'flasback'),
  (1, true, 4, 'English', 'A comparison using like or as to make writing more vivid', 'imagery', 'immagery', 'imagerry', 'imagry'),
  (1, true, 4, 'English', 'The highest point of tension in a story', 'climax', 'climaxx', 'clymax', 'climaks'),
  (1, true, 4, 'English', 'The point in the plot where the conflict is settled', 'resolution', 'resoluton', 'resolutoin', 'resollution'),
  (1, true, 4, 'English', 'A statement that expresses an opinion rather than a fact', 'opinion', 'opinon', 'oppinion', 'opinionn'),
  (1, true, 4, 'English', 'A statement that can be proven true or false', 'fact', 'fackt', 'facct', 'fac'),
  (1, true, 4, 'English', 'A short and clever saying that gives advice', 'proverb', 'provverb', 'proverbe', 'provurb'),
  (1, true, 4, 'English', 'A number written using digits like 1, 2, 3', 'numeral', 'numaral', 'numarel', 'numerel'),
  (1, true, 4, 'English', 'A pair of numbers used to locate a point on a graph', 'coordinate', 'coordinat', 'coordanate', 'coordinatte'),
  (1, true, 4, 'English', 'A number that a given number can be divided by evenly', 'factor', 'facter', 'factour', 'factorr'),
  (1, true, 4, 'English', 'The result of multiplying two or more numbers', 'product', 'produkt', 'producct', 'prodduct'),
  (1, true, 4, 'English', 'A number that is a result of adding two or more numbers', 'sum', 'summ', 'sumn', 'suum'),
  (1, true, 4, 'English', 'The result of subtracting one number from another', 'difference', 'differance', 'differense', 'difrence'),
  (1, true, 4, 'English', 'A number sentence that shows two amounts are equal', 'equation', 'equaton', 'equashun', 'equasion'),
  (1, true, 4, 'English', 'A collection of data organized in rows and columns', 'table', 'tabel', 'tablle', 'tabble'),
  (1, true, 4, 'English', 'A diagram that uses bars to represent data', 'graph', 'graf', 'graphh', 'grafh'),
  (1, true, 4, 'English', 'The center point of a circle', 'center', 'centar', 'centre''', 'centerr'),
  (1, true, 4, 'English', 'A line segment from the center of a circle to its edge', 'radius', 'radiuss', 'radious', 'raddius'),
  (1, true, 4, 'English', 'A line segment through the center that touches both sides of a circle', 'diameter', 'diametar', 'diametter', 'diameeter'),
  (1, true, 4, 'English', 'A tool used to draw circles', 'compass', 'compas', 'compess', 'compasse'),
  (1, true, 4, 'English', 'A shape with eight sides', 'octagon', 'octagen', 'octaggon', 'octagom'),
  (1, true, 4, 'English', 'A shape with five sides', 'pentagon', 'pentagen', 'pentaggon', 'pentagom'),
  (1, true, 4, 'English', 'A shape with six sides', 'hexagon', 'hexagen', 'hexaggon', 'hexagom'),
  (1, true, 4, 'English', 'A solid shape with six flat square faces', 'cube', 'cub', 'cubbe', 'cuube'),
  (1, true, 4, 'English', 'A solid shape that is round like a ball', 'sphere', 'spher', 'spheree', 'spheare'),
  (1, true, 4, 'English', 'A solid shape with a circular base that narrows to a point', 'cone', 'conne', 'coan', 'conee'),
  (1, true, 4, 'English', 'A solid shape with two circular bases connected by a curved surface', 'cylinder', 'cilinder', 'cylindar', 'cylindder'),
  (1, true, 4, 'English', 'The outer boundary of a two-dimensional shape', 'perimeter', 'parameter', 'perimetter', 'perimiter'),
  (1, true, 4, 'English', 'The amount of space a solid object occupies', 'volume', 'volum', 'volumme', 'voluume'),
  (1, true, 4, 'English', 'A path formed by the movement of a light ray', 'reflection', 'reflecton', 'reflecshun', 'reflektion'),
  (1, true, 4, 'English', 'The bending of light as it passes through different materials', 'refraction', 'refracton', 'refracshun', 'refrakction'),
  (1, true, 4, 'English', 'Light energy that allows us to see', 'luminous', 'luminuos', 'lumminous', 'luminious'),
  (1, true, 4, 'English', 'The transfer of heat through direct contact', 'conduction', 'conducton', 'conducshun', 'condukction'),
  (1, true, 4, 'English', 'The transfer of heat through fluid movement', 'convection', 'convecton', 'convecshun', 'convekction'),
  (1, true, 4, 'English', 'The transfer of energy through waves without matter', 'radiation', 'radiaton', 'radiashun', 'radiattion'),
  (1, true, 4, 'English', 'The layer of gases surrounding the earth', 'atmosphere', 'atmospher', 'atmosphre', 'atmosfere'),
  (1, true, 4, 'English', 'A community of living and non-living things interacting together', 'ecosystem', 'ecosystim', 'ecosytem', 'ecosysten'),
  (1, true, 4, 'English', 'A group of organisms of the same kind living in one area', 'population', 'populaton', 'populashun', 'populattion'),
  (1, true, 4, 'English', 'Different kinds of living things found in an environment', 'biodiversity', 'biodiverssity', 'biodiverstiy', 'bio-diversity'),
  (1, true, 4, 'English', 'A living thing''s role and way of life in its habitat', 'niche', 'nich', 'nichee', 'neach'),
  (1, true, 4, 'English', 'Two organisms living closely together, benefiting each other', 'symbiosis', 'symbiossis', 'simbiosis', 'symbioses'),
  (1, true, 4, 'Filipino', 'Ang uri ng tulang may sukat at tugma, karaniwang inawit', 'kundiman', 'kondiman', 'kunduman', 'kundeman'),
  (1, true, 4, 'Filipino', 'Ang matandang kwento tungkol sa pinagmulan ng isang bagay', 'alamat', 'alammat', 'alamatt', 'allamat'),
  (1, true, 4, 'Filipino', 'Ang dulang isinasagawa sa entablado', 'dula', 'dulah', 'duula', 'dulla'),
  (1, true, 4, 'Filipino', 'Ang paraan ng pagpapahayag ng damdamin gamit ang tugma', 'tula', 'tulah', 'toola', 'tulla'),
  (1, true, 4, 'Filipino', 'Ang matalinhagang kasabihan na may aral', 'salawikain', 'salawikaen', 'salawikainn', 'salawikian'),
  (1, true, 4, 'Filipino', 'Ang palaisipang may sagot na dapat hulaan', 'bugtong', 'bugtongg', 'bugtung', 'bugtoong'),
  (1, true, 4, 'Filipino', 'Ang mahabang tulang kwento tungkol sa bayani', 'epiko', 'epico', 'epikoh', 'epeko'),
  (1, true, 4, 'Filipino', 'Ang kwentong ipinapasa-pasa sa bibig ng mga tao', 'kwentong-bayan', 'kwentong bayan', 'kwentong-bayann', 'kuwentong-bayan'''),
  (1, true, 4, 'Filipino', 'Ang katangi-tanging galaw o asal ng isang tauhan', 'katangian', 'katanggian', 'katangiann', 'katanggiann'),
  (1, true, 4, 'Filipino', 'Ang taong gumaganap sa isang kwento', 'tauhan', 'tauwhan', 'tauhann', 'tawuhan'),
  (1, true, 4, 'Filipino', 'Ang kapaligirang tinitirhan ng mga hayop o halaman', 'kapaligiran', 'kapaligeran', 'kapaligirann', 'kapaaligiran'),
  (1, true, 4, 'Filipino', 'Ang paglipat mula sa isang anyo patungo sa iba', 'pagbabago', 'pagbabaggo', 'pagbaago', 'pagbaabgo'),
  (1, true, 4, 'Filipino', 'Ang bagay na naririnig ng ating tainga', 'tunog', 'tunogg', 'tunug', 'tunoog'),
  (1, true, 4, 'Filipino', 'Ang bagay na nagpapahintulot sa atin na makakita', 'liwanag', 'liwannag', 'liwanang', 'liuanag'),
  (1, true, 4, 'Filipino', 'Ang pakiramdam ng mataas na temperatura', 'init', 'innit', 'inet', 'innet'),
  (1, true, 4, 'Filipino', 'Ang galaw o kilos ng isang bagay mula sa isang lugar patungo sa iba', 'lakad', 'lakadd', 'lakkad', 'lakat'),
  (1, true, 4, 'Filipino', 'Ang lakas na nagpapagalaw o nagpapahinto sa isang bagay', 'puwersa', 'pwersa', 'puersa', 'puwerssa'),
  (1, true, 4, 'Filipino', 'Ang katangian ng bagay na umaakit ng bakal o asero', 'magnetismo', 'magnetissmo', 'magnettismo', 'magnetesmo'),
  (1, true, 4, 'Filipino', 'Ang paghahalo ng dalawa o higit pang sangkap', 'paghaluin', 'paghalowin', 'paghalluin', 'paghaluwin'),
  (1, true, 4, 'Filipino', 'Ang kalayaan mula sa pananakop ng ibang bansa', 'kalayaan', 'kalayaann', 'kalayaaan', 'kalaayan'),
  (1, true, 4, 'Filipino', 'Ang pagkontrol ng isang bansa sa ibang lupain', 'pananakop', 'pananakup', 'pananakopp', 'pannanakop'),
  (1, true, 4, 'Filipino', 'Ang biglaang pag-aalsa laban sa pamahalaan', 'himagsikan', 'himagsikann', 'himagsikkan', 'himagsykan'),
  (1, true, 4, 'Filipino', 'Ang lipunang may sariling kultura at kaunlaran', 'sibilisasyon', 'sibilisasyonn', 'sibilizasyon', 'sibilisassyon'),
  (1, true, 4, 'Filipino', 'Ang taong namumuno sa isang bansa o organisasyon', 'pamunuan', 'pamunowan', 'pamunuann', 'pamunuuan'),
  (1, true, 4, 'Filipino', 'Ang sistema ng pamahalaang pinili ng mamamayan', 'demokratiya', 'demokrasya', 'demokratiyah', 'demokratya'),
  (1, true, 4, 'Filipino', 'Ang sangay ng pamahalaang gumagawa ng batas', 'lehislatura', 'lehislaturra', 'legislatura', 'lehislatuura'),
  (1, true, 4, 'Filipino', 'Ang paraan o hakbang sa paggawa ng isang bagay', 'pamamaraan', 'pamamaraann', 'pamamaraaan', 'pammamaraan'),
  (1, true, 4, 'Filipino', 'Ang proseso ng paglaki o pag-unlad', 'pagpapalaki', 'pagpapalakki', 'pagpapallaki', 'pagpapalakih'),
  (1, true, 4, 'Filipino', 'Ang uri o antas ng isang tao sa lipunan', 'katayuan', 'katayuann', 'katayuaan', 'kataayuan'),
  (1, true, 4, 'Filipino', 'Ang bagay na dapat matamasa ng bawat mamamayan', 'karapatan', 'karapattan', 'karapaatan', 'karapaten'),
  (1, true, 4, 'Filipino', 'Ang tungkuling dapat gampanan ng isang tao', 'obligasyon', 'obligasyonn', 'obligassyon', 'obligasion'),
  (1, true, 4, 'Filipino', 'Ang pagtutulungan ng grupo para sa isang layunin', 'pakikiisa', 'pakikiisah', 'pakikeisa', 'pakikiissa'),
  (1, true, 4, 'Filipino', 'Ang salitang tumutukoy sa isang tao, lugar, o bagay', 'pangngalan', 'pangalan', 'panngalan', 'pangngalann'),
  (1, true, 4, 'Filipino', 'Ang salitang nagsasaad ng kilos', 'pandiwa', 'pandiiwa', 'pandiwah', 'pandeewa'),
  (1, true, 4, 'Filipino', 'Ang salitang naglalarawan sa isang pangngalan', 'pang-uri', 'panguri', 'pang-uree', 'pang-ure'),
  (1, true, 4, 'Filipino', 'Ang salitang naglalarawan sa pandiwa', 'pang-abay', 'pangabay', 'pang-abbay', 'pang-abai'),
  (1, true, 4, 'Filipino', 'Ang pangungusap na nagtatanong', 'patanong', 'pattanong', 'patanoong', 'patannong'),
  (1, true, 4, 'Filipino', 'Ang pangungusap na nag-uutos', 'pautos', 'pa-utos', 'pautoss', 'pautus'),
  (1, true, 4, 'Filipino', 'Ang pinakamahalagang mensahe ng isang kwento', 'aral', 'arral', 'araal', 'arral'''),
  (1, true, 4, 'Filipino', 'Ang lugar at panahon ng pangyayari sa kwento', 'tagpuan', 'tagpoan', 'tagpuann', 'tagpwan'),
  (1, true, 4, 'Filipino', 'Ang suliraning kinakaharap ng tauhan sa kwento', 'suliranin', 'suliraninn', 'sulirannin', 'suliraninh'),
  (1, true, 4, 'Filipino', 'Ang wakas o kalutasan ng isang suliranin sa kwento', 'kalutasan', 'kalutasann', 'kaluttasan', 'kalutassan'),
  (1, true, 4, 'Filipino', 'Ang bilang na resulta ng pagdaragdag', 'kabuuan', 'kabuuann', 'kabuwan', 'kabuuuan'),
  (1, true, 4, 'Filipino', 'Ang bilang na naiwan pagkatapos ibawas', 'natitira', 'natitirah', 'natittira', 'natitirra'),
  (1, true, 4, 'Filipino', 'Ang bilang na resulta ng pagpaparami', 'produkto', 'produktoh', 'produckto', 'produktto'),
  (1, true, 4, 'Filipino', 'Ang bahagi ng buo na inihahati sa magkakaparehong bilang', 'hati', 'hatti', 'hatih', 'hatii'),
  (1, true, 4, 'Filipino', 'Ang hugis na may apat na magkakaparehong gilid', 'parisukat', 'parisukatt', 'parizukat', 'parisokat'),
  (1, true, 4, 'Filipino', 'Ang hugis na may tatlong gilid', 'tatsulok', 'tatsulokk', 'tatsolok', 'tatsulic'),
  (1, true, 4, 'Filipino', 'Ang bilog na hugis na walang sulok', 'bilog', 'bilogg', 'bilug', 'bilog'''),
  (1, true, 4, 'Filipino', 'Ang panukat ng distansya sa paligid ng isang hugis', 'paligid', 'paligidd', 'paligeed', 'paligiid'),
  (1, true, 4, 'Filipino', 'Ang panukat ng sukat ng loob ng isang hugis', 'sukat', 'sukatt', 'sukkat', 'sukat'''),
  (1, true, 4, 'Filipino', 'Ang layer ng hangin na bumabalot sa mundo', 'kapaligirang-lupa', 'kapaligirang lupa', 'kapaligiranglupa', 'kapaaligirang-lupa'),
  (1, true, 4, 'Filipino', 'Ang tinatawag sa uri ng pagkain na nagbibigay lakas', 'pagkain', 'pagkaen', 'pagkainn', 'pagkaan'),
  (1, true, 4, 'Filipino', 'Ang sangkap na tumutulong sa paglaki ng katawan', 'sustansya', 'sustansiya', 'sustansya''', 'sustanssya'),
  (1, true, 4, 'Filipino', 'Ang gawaing pagpapanatiling malinis ng kapaligiran', 'kalinisan', 'kalinisann', 'kalinnisan', 'kaliniisan'),
  (1, true, 4, 'Filipino', 'Ang kalagayan ng katawan na malaya sa sakit', 'kalusugan', 'kalusugann', 'kaluusugan', 'kalusuugan'),
  (1, true, 4, 'Filipino', 'Ang gamot na iniiniksyon upang maiwasan ang sakit', 'bakuna', 'bakunna', 'bakuuna', 'bakunah'),
  (1, true, 4, 'Filipino', 'Ang kalagayan ng katawan na may sakit', 'karamdaman', 'karamdamann', 'karamddaman', 'karamdaaman'),
  (1, true, 4, 'English', 'A word opposite in meaning to another word', 'antonym', 'antonim', 'antynom', 'anttonym'),
  (1, true, 4, 'English', 'A word similar in meaning to another word', 'synonym', 'synonim', 'sinonym', 'synnonym'),
  (1, true, 4, 'English', 'A group of letters added before a word to change its meaning', 'prefix', 'prefixe', 'prefics', 'prefex'),
  (1, true, 4, 'English', 'A group of letters added after a word to change its meaning', 'suffix', 'sufix', 'suffics', 'suffex'),
  (1, true, 4, 'English', 'The smallest part of a word that carries meaning', 'root word', 'rootword', 'root-word''', 'rootwoard'),
  (1, true, 4, 'English', 'A word that names an action performed by someone or something', 'verb', 'verrb', 'verbe', 'verv'),
  (1, true, 4, 'English', 'A word that describes or modifies a noun', 'adjective', 'adjectiv', 'adjectve', 'adjecktive'),
  (1, true, 4, 'English', 'A word used instead of a noun, such as he or they', 'pronoun', 'pronuon', 'pronowne', 'pronoune'),
  (1, true, 4, 'English', 'A punctuation mark used to end a question', 'question mark', 'question-mark', 'questoin mark', 'question markk'),
  (1, true, 4, 'English', 'A punctuation mark that separates items in a list', 'comma', 'comah', 'comma''', 'commma'),
  (1, true, 4, 'Filipino', 'Ang salitang kasalungat ng kahulugan ng ibang salita', 'kasalungat', 'kasalunggat', 'kasalungatt', 'kasalongat'),
  (1, true, 4, 'Filipino', 'Ang salitang magkatulad ang kahulugan sa ibang salita', 'kasingkahulugan', 'kasingkahulugann', 'kasingkahulgan', 'kasingkaulugan'),
  (1, true, 4, 'Filipino', 'Ang bahagi ng salitang idinaragdag sa unahan', 'unlapi', 'unlappi', 'unllapi', 'unlaapi'),
  (1, true, 4, 'Filipino', 'Ang bahagi ng salitang idinaragdag sa hulihan', 'hulapi', 'hulappi', 'hullapi', 'hulaapi'),
  (1, true, 4, 'Filipino', 'Ang bahagi ng salitang idinaragdag sa gitna', 'gitlapi', 'gitlappi', 'gittlapi', 'gitlaapi'),
  (1, true, 4, 'Filipino', 'Ang bantas na ginagamit sa dulo ng tanong', 'tandang pananong', 'tandapananong', 'tandang-pananong''', 'tandangpananong'),
  (1, true, 4, 'Filipino', 'Ang bantas na ginagamit upang paghiwalayin ang mga salita sa listahan', 'kuwit', 'kwit', 'kuwitt', 'kuwitth'),
  (1, true, 4, 'Filipino', 'Ang lugar kung saan ipinanganak ang isang tao', 'kinaganak', 'kinaganakk', 'kinagganak', 'kinagaanak'),
  (1, true, 4, 'Filipino', 'Ang pagsunod sa mga alituntunin o batas', 'pagsunod', 'pagsunodd', 'pagsunud', 'pagsunood'),
  (1, true, 4, 'Filipino', 'Ang pagtutol o hindi pagsang-ayon sa isang bagay', 'pagtutol', 'pagtuttol', 'pagtutool', 'pagtutoll'),
  (1, true, 4, 'Filipino', 'Ang paniniwalang taos-puso sa isang layunin o adhikain', 'paniniwala', 'panniniwala', 'paniniwalah', 'paniniwaala'),
  (1, true, 4, 'Filipino', 'Ang pagpili ng mga kinatawan sa pamahalaan sa pamamagitan ng boto', 'halalan', 'hallalan', 'halalann', 'halallan'),
  (1, true, 4, 'Filipino', 'Ang kapangyarihang taglay ng isang bansa na mamuno sa sarili', 'soberanya', 'soveranya', 'soberaniya', 'soberanyah'),
  (1, true, 4, 'Filipino', 'Ang pinagsamang lakas ng mga bansa laban sa isang layunin', 'alyansa', 'alyanssa', 'aliyansa', 'allyansa'),
  (1, true, 4, 'Filipino', 'Ang panahong sinasakop ng ibang bansa ang Pilipinas', 'kolonyal', 'kolonyall', 'kolonial', 'kolonyaal'),
  (1, true, 4, 'Filipino', 'Ang taong lumalaban para sa kalayaan ng bansa', 'rebolusyonaryo', 'rebolusyonaryoh', 'rebolusyunaryo', 'rebolusyonaryyo'),
  (1, true, 4, 'Filipino', 'Ang liham o dokumentong opisyal na ipinapadala ng pamahalaan', 'proklamasyon', 'proklamasyonn', 'proklamassyon', 'proklamasion'),
  (1, true, 4, 'Filipino', 'Ang bahagi ng bayan na pinamumunuan ng kapitan', 'barangay', 'baranggay', 'barrangay', 'barangai'),
  (1, true, 4, 'Filipino', 'Ang panukat ng timbang ng isang bagay', 'timbang', 'timbangg', 'timbanng', 'timbaang'),
  (1, true, 4, 'Filipino', 'Ang panukat ng haba ng isang bagay', 'haba', 'habah', 'habba', 'habaa'),
  (1, true, 4, 'Filipino', 'Ang panukat ng lalim ng isang bagay', 'lalim', 'lalimm', 'lallim', 'laalim'),
  (1, true, 4, 'Filipino', 'Ang katas na inilalabas ng katawan kapag mainit', 'pawis', 'pawiss', 'pawwis', 'paawis'),
  (1, true, 4, 'Filipino', 'Ang bahagi ng katawan na gumagawa ng dugo', 'balon-dugo', 'balondugo', 'balon-dugoh', 'ballon-dugo'),
  (1, true, 4, 'Filipino', 'Ang sistema ng katawan na tumutulong sa paghinga', 'sistemang paghinga', 'sistemapaghinga', 'sistemang-paghinga''', 'sistemang paghingga'),
  (1, true, 4, 'Filipino', 'Ang tinatawag sa organismong maliit na nagdudulot ng sakit', 'mikrobyo', 'mikrobio', 'mikrobyoh', 'mikkrobyo'),
  (1, true, 4, 'Filipino', 'Ang pangyayaring nagbabago ng anyo ng lupa sa mahabang panahon', 'erosyon', 'erosyonn', 'erossyon', 'erosion'),
  (1, true, 4, 'Filipino', 'Ang tubig na dumadaloy pababa mula sa mataas na lugar', 'talon', 'tallon', 'taloon', 'taalon'),
  (1, true, 4, 'Filipino', 'Ang butas sa lupa na pinagmumulan ng tubig', 'balon', 'ballon', 'baloon', 'baalon'),
  (1, true, 4, 'Filipino', 'Ang panahong may malakas na hangin at ulan', 'bagyo', 'bagyoh', 'baggyo', 'bagyyo');